version: 0.2

environment_variables:
  plaintext:
    DJANGO_SETTINGS_MODULE: core.settings

phases:
  pre_build:
    commands:
      - pip install --upgrade pip wheel setuptools
      - pip install -r requirements.txt

  build:
    commands:
      - python manage.py makemigrations
      - python manage.py migrate

  post_build:
    commands:
      - echo Build completed on `date`
