# Generated by Django 3.2.16 on 2024-03-07 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='delievery_status',
            new_name='delivery_status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.AddField(
            model_name='order',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('CNY', 'CNY'), ('HKD', 'HKD')], default='HKD', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='type',
            field=models.CharField(choices=[('Invoice', 'Invoice'), ('Quotation', 'Quotation')], default='quotation', max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='area_code',
            field=models.CharField(choices=[('+81', '+81 (Japan)'), ('+55', '+55 (Brazil)'), ('+82', '+82 (South Korea)'), ('+971', '+971 (UAE)'), ('+34', '+34 (Spain)'), ('+64', '+64 (New Zealand)'), ('+20', '+20 (Egypt)'), ('+52', '+52 (Mexico)'), ('+91', '+91 (India)'), ('+1', '+1 (Canada)'), ('+1', '+1 (US)'), ('+49', '+49 (Germany)'), ('+966', '+966 (Saudi Arabia)'), ('+61', '+61 (Australia)'), ('+44', '+44 (UK)'), ('+7', '+7 (Russia)'), ('+33', '+33 (France)'), ('+65', '+65 (Singapore)'), ('+39', '+39 (Italy)'), ('+86', '+86 (China)')], max_length=128),
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='amount_trigger',
            field=models.CharField(choices=[('More than', 'More than'), (None, '-------'), ('Less than', 'Less than'), ('Equals to', 'Equals to'), ('Less than and equals to', 'Less than and equals to'), ('More than and equals to', 'More than and equals to')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='quantity_trigger',
            field=models.CharField(choices=[('More than', 'More than'), (None, '-------'), ('Less than', 'Less than'), ('Equals to', 'Equals to'), ('Less than and equals to', 'Less than and equals to'), ('More than and equals to', 'More than and equals to')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('self-pickup', 'Self-Pickup'), ('SF Express', 'SF Express'), ('salesperson delivery', 'salesperson delivery'), ('GOGOVAN', 'GOGOVAN')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'COD'), ('Bank Transfer/Cheque', 'Bank Transfer/Cheque')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('Paid', 'paid'), ('Pending', 'Pending'), ('Failed', 'Failed')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'COD'), ('Bank Transfer/Cheque', 'Bank Transfer/Cheque')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('Partially Delivered', 'Partially Delivered'), ('Delivered', 'Delivered'), ('Pending', 'Pending')], default='Pending', max_length=128),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='discount_type',
            field=models.CharField(choices=[('Rate(%)', 'Rate(%)'), ('Fixed Amount', 'Fixed Amount'), (None, '-------')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='status',
            field=models.CharField(choices=[('Paused', 'Paused'), ('Ended', 'Ended'), ('Valid', 'Valid'), ('Ready to start', 'Ready to start'), ('Cancelled', 'Cancelled')], max_length=128),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='voucher_type',
            field=models.CharField(choices=[('Product Combo', 'Product Combo'), ('Discount Voucher', 'Discount Voucher'), ('Manual Discount', 'Manual Discount'), ('Free Gift', 'Free Gift')], max_length=128),
        ),
    ]
