# Generated by Django 3.2.16 on 2024-03-14 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20240307_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='address_line1',
        ),
        migrations.RemoveField(
            model_name='address',
            name='address_line2',
        ),
        migrations.RemoveField(
            model_name='address',
            name='city',
        ),
        migrations.RemoveField(
            model_name='address',
            name='country',
        ),
        migrations.RemoveField(
            model_name='address',
            name='landmark',
        ),
        migrations.RemoveField(
            model_name='address',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='address',
            name='state',
        ),
        migrations.RemoveField(
            model_name='address',
            name='town',
        ),
        migrations.AddField(
            model_name='address',
            name='address_line',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_comments',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='delivery_comments',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='area_code',
            field=models.CharField(choices=[('+81', '+81 (Japan)'), ('+1', '+1 (Canada)'), ('+49', '+49 (Germany)'), ('+966', '+966 (Saudi Arabia)'), ('+61', '+61 (Australia)'), ('+91', '+91 (India)'), ('+86', '+86 (China)'), ('+82', '+82 (South Korea)'), ('+65', '+65 (Singapore)'), ('+971', '+971 (UAE)'), ('+39', '+39 (Italy)'), ('+34', '+34 (Spain)'), ('+55', '+55 (Brazil)'), ('+44', '+44 (UK)'), ('+64', '+64 (New Zealand)'), ('+33', '+33 (France)'), ('+1', '+1 (US)'), ('+20', '+20 (Egypt)'), ('+52', '+52 (Mexico)'), ('+7', '+7 (Russia)')], max_length=128),
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='amount_trigger',
            field=models.CharField(choices=[('More than', 'More than'), ('Equals to', 'Equals to'), (None, '-------'), ('Less than and equals to', 'Less than and equals to'), ('More than and equals to', 'More than and equals to'), ('Less than', 'Less than')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='quantity_trigger',
            field=models.CharField(choices=[('More than', 'More than'), ('Equals to', 'Equals to'), (None, '-------'), ('Less than and equals to', 'Less than and equals to'), ('More than and equals to', 'More than and equals to'), ('Less than', 'Less than')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Partially Delivered', 'Partially Delivered'), ('Pending', 'Pending')], default='Pending', max_length=128),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='discount_type',
            field=models.CharField(choices=[(None, '-------'), ('Fixed Amount', 'Fixed Amount'), ('Rate(%)', 'Rate(%)')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='status',
            field=models.CharField(choices=[('Ready to start', 'Ready to start'), ('Ended', 'Ended'), ('Paused', 'Paused'), ('Cancelled', 'Cancelled'), ('Valid', 'Valid')], max_length=128),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='voucher_type',
            field=models.CharField(choices=[('Manual Discount', 'Manual Discount'), ('Product Combo', 'Product Combo'), ('Discount Voucher', 'Discount Voucher'), ('Free Gift', 'Free Gift')], max_length=128),
        ),
    ]
