# Generated by Django 3.2.16 on 2024-03-15 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20240314_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='area_code',
            field=models.CharField(choices=[('+1', '+1 (US)'), ('+52', '+52 (Mexico)'), ('+61', '+61 (Australia)'), ('+65', '+65 (Singapore)'), ('+20', '+20 (Egypt)'), ('+86', '+86 (China)'), ('+7', '+7 (Russia)'), ('+1', '+1 (Canada)'), ('+91', '+91 (India)'), ('+49', '+49 (Germany)'), ('+82', '+82 (South Korea)'), ('+64', '+64 (New Zealand)'), ('+34', '+34 (Spain)'), ('+55', '+55 (Brazil)'), ('+39', '+39 (Italy)'), ('+971', '+971 (UAE)'), ('+44', '+44 (UK)'), ('+81', '+81 (Japan)'), ('+966', '+966 (Saudi Arabia)'), ('+33', '+33 (France)')], max_length=128),
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='amount_trigger',
            field=models.CharField(choices=[('Less than', 'Less than'), ('Equals to', 'Equals to'), (None, '-------'), ('More than', 'More than'), ('More than and equals to', 'More than and equals to'), ('Less than and equals to', 'Less than and equals to')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='quantity_trigger',
            field=models.CharField(choices=[('Less than', 'Less than'), ('Equals to', 'Equals to'), (None, '-------'), ('More than', 'More than'), ('More than and equals to', 'More than and equals to'), ('Less than and equals to', 'Less than and equals to')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_comment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='payment_method',
            field=models.CharField(choices=[('Bank Transfer/Cheque', 'Bank Transfer/Cheque'), ('COD', 'COD')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='discount_type',
            field=models.CharField(choices=[('Rate(%)', 'Rate(%)'), ('Fixed Amount', 'Fixed Amount'), (None, '-------')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='status',
            field=models.CharField(choices=[('Paused', 'Paused'), ('Ended', 'Ended'), ('Ready to start', 'Ready to start'), ('Valid', 'Valid'), ('Cancelled', 'Cancelled')], max_length=128),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='voucher_type',
            field=models.CharField(choices=[('Free Gift', 'Free Gift'), ('Manual Discount', 'Manual Discount'), ('Discount Voucher', 'Discount Voucher'), ('Product Combo', 'Product Combo')], max_length=128),
        ),
    ]
