# Generated by Django 3.2.16 on 2024-03-15 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20240315_0456'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='inv_qt_num',
            field=models.CharField(blank=True, help_text='Invoice and Quotation id', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='area_code',
            field=models.CharField(choices=[('+86', '+86 (China)'), ('+52', '+52 (Mexico)'), ('+82', '+82 (South Korea)'), ('+971', '+971 (UAE)'), ('+20', '+20 (Egypt)'), ('+55', '+55 (Brazil)'), ('+39', '+39 (Italy)'), ('+966', '+966 (Saudi Arabia)'), ('+61', '+61 (Australia)'), ('+81', '+81 (Japan)'), ('+7', '+7 (Russia)'), ('+33', '+33 (France)'), ('+91', '+91 (India)'), ('+64', '+64 (New Zealand)'), ('+1', '+1 (US)'), ('+65', '+65 (Singapore)'), ('+44', '+44 (UK)'), ('+34', '+34 (Spain)'), ('+49', '+49 (Germany)'), ('+1', '+1 (Canada)')], max_length=128),
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='amount_trigger',
            field=models.CharField(choices=[('Equals to', 'Equals to'), ('Less than and equals to', 'Less than and equals to'), ('More than and equals to', 'More than and equals to'), ('More than', 'More than'), ('Less than', 'Less than'), (None, '-------')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='quantity_trigger',
            field=models.CharField(choices=[('Equals to', 'Equals to'), ('Less than and equals to', 'Less than and equals to'), ('More than and equals to', 'More than and equals to'), ('More than', 'More than'), ('Less than', 'Less than'), (None, '-------')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Delivered', 'Delivered'), ('Partially Delivered', 'Partially Delivered')], default='Pending', max_length=128),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='type',
            field=models.CharField(choices=[('Purchase', 'Purchase'), ('Quotation', 'Quotation')], max_length=128),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='discount_type',
            field=models.CharField(choices=[(None, '-------'), ('Fixed Amount', 'Fixed Amount'), ('Rate(%)', 'Rate(%)')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='status',
            field=models.CharField(choices=[('Cancelled', 'Cancelled'), ('Valid', 'Valid'), ('Paused', 'Paused'), ('Ready to start', 'Ready to start'), ('Ended', 'Ended')], max_length=128),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='voucher_type',
            field=models.CharField(choices=[('Manual Discount', 'Manual Discount'), ('Free Gift', 'Free Gift'), ('Discount Voucher', 'Discount Voucher'), ('Product Combo', 'Product Combo')], max_length=128),
        ),
    ]
