# Generated by Django 3.2.16 on 2024-03-15 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20240315_0657'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='manual_cost',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='area_code',
            field=models.CharField(choices=[('+44', '+44 (UK)'), ('+91', '+91 (India)'), ('+1', '+1 (Canada)'), ('+64', '+64 (New Zealand)'), ('+20', '+20 (Egypt)'), ('+61', '+61 (Australia)'), ('+52', '+52 (Mexico)'), ('+971', '+971 (UAE)'), ('+49', '+49 (Germany)'), ('+39', '+39 (Italy)'), ('+55', '+55 (Brazil)'), ('+7', '+7 (Russia)'), ('+34', '+34 (Spain)'), ('+82', '+82 (South Korea)'), ('+86', '+86 (China)'), ('+966', '+966 (Saudi Arabia)'), ('+33', '+33 (France)'), ('+1', '+1 (US)'), ('+81', '+81 (Japan)'), ('+65', '+65 (Singapore)')], max_length=128),
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='amount_trigger',
            field=models.CharField(choices=[('Equals to', 'Equals to'), ('More than', 'More than'), (None, '-------'), ('More than and equals to', 'More than and equals to'), ('Less than', 'Less than'), ('Less than and equals to', 'Less than and equals to')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='quantity_trigger',
            field=models.CharField(choices=[('Equals to', 'Equals to'), ('More than', 'More than'), (None, '-------'), ('More than and equals to', 'More than and equals to'), ('Less than', 'Less than'), ('Less than and equals to', 'Less than and equals to')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('Partially Delivered', 'Partially Delivered'), ('Delivered', 'Delivered'), ('Pending', 'Pending')], default='Pending', max_length=128),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='discount_type',
            field=models.CharField(choices=[('Rate(%)', 'Rate(%)'), (None, '-------'), ('Fixed Amount', 'Fixed Amount')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='status',
            field=models.CharField(choices=[('Paused', 'Paused'), ('Ready to start', 'Ready to start'), ('Ended', 'Ended'), ('Valid', 'Valid'), ('Cancelled', 'Cancelled')], max_length=128),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='voucher_type',
            field=models.CharField(choices=[('Product Combo', 'Product Combo'), ('Free Gift', 'Free Gift'), ('Discount Voucher', 'Discount Voucher'), ('Manual Discount', 'Manual Discount')], max_length=128),
        ),
    ]
