# Generated by Django 3.2.16 on 2024-03-15 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20240315_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitems',
            name='inv_qt_num',
        ),
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.CharField(max_length=18, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='area_code',
            field=models.CharField(choices=[('+1', '+1 (US)'), ('+64', '+64 (New Zealand)'), ('+91', '+91 (India)'), ('+966', '+966 (Saudi Arabia)'), ('+39', '+39 (Italy)'), ('+34', '+34 (Spain)'), ('+81', '+81 (Japan)'), ('+86', '+86 (China)'), ('+55', '+55 (Brazil)'), ('+65', '+65 (Singapore)'), ('+971', '+971 (UAE)'), ('+61', '+61 (Australia)'), ('+44', '+44 (UK)'), ('+49', '+49 (Germany)'), ('+7', '+7 (Russia)'), ('+33', '+33 (France)'), ('+1', '+1 (Canada)'), ('+82', '+82 (South Korea)'), ('+20', '+20 (Egypt)'), ('+52', '+52 (Mexico)')], max_length=128),
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='amount_trigger',
            field=models.CharField(choices=[('More than', 'More than'), ('Equals to', 'Equals to'), ('More than and equals to', 'More than and equals to'), ('Less than and equals to', 'Less than and equals to'), ('Less than', 'Less than'), (None, '-------')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='quantity_trigger',
            field=models.CharField(choices=[('More than', 'More than'), ('Equals to', 'Equals to'), ('More than and equals to', 'More than and equals to'), ('Less than and equals to', 'Less than and equals to'), ('Less than', 'Less than'), (None, '-------')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='home.customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Partially Delievered', 'Partially Delievered'), ('Delievered', 'Delievered')], default='Pending', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'COD'), ('Bank Transfer', 'Bank Transfer'), ('Cheque', 'Cheque')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'COD'), ('Bank Transfer/Cheque', 'Bank Transfer/Cheque')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Pending', 'Pending'), ('Partially Delivered', 'Partially Delivered')], default='Pending', max_length=128),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='discount_type',
            field=models.CharField(choices=[('Rate(%)', 'Rate(%)'), (None, '-------'), ('Fixed Amount', 'Fixed Amount')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='status',
            field=models.CharField(choices=[('Ready to start', 'Ready to start'), ('Paused', 'Paused'), ('Cancelled', 'Cancelled'), ('Valid', 'Valid'), ('Ended', 'Ended')], max_length=128),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='voucher_type',
            field=models.CharField(choices=[('Free Gift', 'Free Gift'), ('Discount Voucher', 'Discount Voucher'), ('Manual Discount', 'Manual Discount'), ('Product Combo', 'Product Combo')], max_length=128),
        ),
    ]
