# Generated by Django 3.2.16 on 2024-03-20 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20240318_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('Cancelled', 'cancelled'), ('Pending for approval', 'pending for approval')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='area_code',
            field=models.CharField(choices=[('+20', '+20 (Egypt)'), ('+86', '+86 (China)'), ('+52', '+52 (Mexico)'), ('+65', '+65 (Singapore)'), ('+55', '+55 (Brazil)'), ('+81', '+81 (Japan)'), ('+971', '+971 (UAE)'), ('+1', '+1 (US)'), ('+33', '+33 (France)'), ('+49', '+49 (Germany)'), ('+44', '+44 (UK)'), ('+82', '+82 (South Korea)'), ('+39', '+39 (Italy)'), ('+64', '+64 (New Zealand)'), ('+61', '+61 (Australia)'), ('+91', '+91 (India)'), ('+966', '+966 (Saudi Arabia)'), ('+1', '+1 (Canada)'), ('+34', '+34 (Spain)'), ('+7', '+7 (Russia)')], max_length=128),
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='amount_trigger',
            field=models.CharField(choices=[('Equals to', 'Equals to'), ('Less than and equals to', 'Less than and equals to'), ('Less than', 'Less than'), ('More than', 'More than'), ('More than and equals to', 'More than and equals to'), (None, '-------')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='quantity_trigger',
            field=models.CharField(choices=[('Equals to', 'Equals to'), ('Less than and equals to', 'Less than and equals to'), ('Less than', 'Less than'), ('More than', 'More than'), ('More than and equals to', 'More than and equals to'), (None, '-------')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'COD'), ('Bank Transfer/Cheque', 'Bank Transfer/Cheque')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Pending', 'Pending'), ('Partially Delivered', 'Partially Delivered')], default='Pending', max_length=128),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='discount_type',
            field=models.CharField(choices=[(None, '-------'), ('Fixed Amount', 'Fixed Amount'), ('Rate(%)', 'Rate(%)')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='status',
            field=models.CharField(choices=[('Cancelled', 'Cancelled'), ('Ready to start', 'Ready to start'), ('Paused', 'Paused'), ('Valid', 'Valid'), ('Ended', 'Ended')], max_length=128),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='voucher_type',
            field=models.CharField(choices=[('Free Gift', 'Free Gift'), ('Discount Voucher', 'Discount Voucher'), ('Manual Discount', 'Manual Discount'), ('Product Combo', 'Product Combo')], max_length=128),
        ),
    ]
