# Generated by Django 3.2.16 on 2024-03-20 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20240320_0524'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='area_code',
            field=models.CharField(choices=[('+20', '+20 (Egypt)'), ('+61', '+61 (Australia)'), ('+82', '+82 (South Korea)'), ('+1', '+1 (US)'), ('+64', '+64 (New Zealand)'), ('+39', '+39 (Italy)'), ('+966', '+966 (Saudi Arabia)'), ('+33', '+33 (France)'), ('+86', '+86 (China)'), ('+971', '+971 (UAE)'), ('+34', '+34 (Spain)'), ('+91', '+91 (India)'), ('+65', '+65 (Singapore)'), ('+52', '+52 (Mexico)'), ('+49', '+49 (Germany)'), ('+7', '+7 (Russia)'), ('+81', '+81 (Japan)'), ('+55', '+55 (Brazil)'), ('+1', '+1 (Canada)'), ('+44', '+44 (UK)')], max_length=128),
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='amount_trigger',
            field=models.CharField(choices=[('More than and equals to', 'More than and equals to'), ('Equals to', 'Equals to'), (None, '-------'), ('More than', 'More than'), ('Less than', 'Less than'), ('Less than and equals to', 'Less than and equals to')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='quantity_trigger',
            field=models.CharField(choices=[('More than and equals to', 'More than and equals to'), ('Equals to', 'Equals to'), (None, '-------'), ('More than', 'More than'), ('Less than', 'Less than'), ('Less than and equals to', 'Less than and equals to')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Delivered', 'Delivered'), ('Partially Delivered', 'Partially Delivered')], default='Pending', max_length=128),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='type',
            field=models.CharField(choices=[('Quotation', 'Quotation'), ('Purchase', 'Purchase')], max_length=128),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='discount_type',
            field=models.CharField(choices=[(None, '-------'), ('Rate(%)', 'Rate(%)'), ('Fixed Amount', 'Fixed Amount')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='status',
            field=models.CharField(choices=[('Ended', 'Ended'), ('Paused', 'Paused'), ('Ready to start', 'Ready to start'), ('Valid', 'Valid'), ('Cancelled', 'Cancelled')], max_length=128),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='voucher_type',
            field=models.CharField(choices=[('Discount Voucher', 'Discount Voucher'), ('Free Gift', 'Free Gift'), ('Manual Discount', 'Manual Discount'), ('Product Combo', 'Product Combo')], max_length=128),
        ),
    ]
