# Generated by Django 3.2.16 on 2024-03-20 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20240320_0635'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='old_order',
            field=models.ForeignKey(blank=True, help_text='Add order id when order is submitted for approval.', null=True, on_delete=django.db.models.deletion.CASCADE, to='home.order'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='area_code',
            field=models.CharField(choices=[('+91', '+91 (India)'), ('+65', '+65 (Singapore)'), ('+20', '+20 (Egypt)'), ('+64', '+64 (New Zealand)'), ('+1', '+1 (US)'), ('+34', '+34 (Spain)'), ('+55', '+55 (Brazil)'), ('+33', '+33 (France)'), ('+7', '+7 (Russia)'), ('+1', '+1 (Canada)'), ('+49', '+49 (Germany)'), ('+52', '+52 (Mexico)'), ('+81', '+81 (Japan)'), ('+44', '+44 (UK)'), ('+61', '+61 (Australia)'), ('+971', '+971 (UAE)'), ('+39', '+39 (Italy)'), ('+82', '+82 (South Korea)'), ('+86', '+86 (China)'), ('+966', '+966 (Saudi Arabia)')], max_length=128),
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='amount_trigger',
            field=models.CharField(choices=[('More than', 'More than'), ('Equals to', 'Equals to'), ('More than and equals to', 'More than and equals to'), ('Less than', 'Less than'), (None, '-------'), ('Less than and equals to', 'Less than and equals to')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='quantity_trigger',
            field=models.CharField(choices=[('More than', 'More than'), ('Equals to', 'Equals to'), ('More than and equals to', 'More than and equals to'), ('Less than', 'Less than'), (None, '-------'), ('Less than and equals to', 'Less than and equals to')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Partially Delivered', 'Partially Delivered'), ('Delivered', 'Delivered')], default='Pending', max_length=128),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='type',
            field=models.CharField(choices=[('Purchase', 'Purchase'), ('Quotation', 'Quotation')], max_length=128),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='status',
            field=models.CharField(choices=[('Cancelled', 'Cancelled'), ('Ready to start', 'Ready to start'), ('Paused', 'Paused'), ('Valid', 'Valid'), ('Ended', 'Ended')], max_length=128),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='voucher_type',
            field=models.CharField(choices=[('Free Gift', 'Free Gift'), ('Discount Voucher', 'Discount Voucher'), ('Product Combo', 'Product Combo'), ('Manual Discount', 'Manual Discount')], max_length=128),
        ),
    ]
