# Generated by Django 3.2.16 on 2024-03-20 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20240320_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='area_code',
            field=models.CharField(choices=[('+7', '+7 (Russia)'), ('+61', '+61 (Australia)'), ('+52', '+52 (Mexico)'), ('+20', '+20 (Egypt)'), ('+64', '+64 (New Zealand)'), ('+971', '+971 (UAE)'), ('+65', '+65 (Singapore)'), ('+1', '+1 (Canada)'), ('+39', '+39 (Italy)'), ('+86', '+86 (China)'), ('+34', '+34 (Spain)'), ('+966', '+966 (Saudi Arabia)'), ('+82', '+82 (South Korea)'), ('+33', '+33 (France)'), ('+81', '+81 (Japan)'), ('+1', '+1 (US)'), ('+44', '+44 (UK)'), ('+55', '+55 (Brazil)'), ('+49', '+49 (Germany)'), ('+91', '+91 (India)')], max_length=128),
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='amount_trigger',
            field=models.CharField(choices=[('More than', 'More than'), ('Less than and equals to', 'Less than and equals to'), ('More than and equals to', 'More than and equals to'), (None, '-------'), ('Less than', 'Less than'), ('Equals to', 'Equals to')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='quantity_trigger',
            field=models.CharField(choices=[('More than', 'More than'), ('Less than and equals to', 'Less than and equals to'), ('More than and equals to', 'More than and equals to'), (None, '-------'), ('Less than', 'Less than'), ('Equals to', 'Equals to')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('Cancelled', 'cancelled'), ('Pending for approval', 'pending for approval'), ('Approved', 'approved'), ('Rejected', 'rejected')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Delivered', 'Delivered'), ('Partially Delivered', 'Partially Delivered')], default='Pending', max_length=128),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='discount_type',
            field=models.CharField(choices=[(None, '-------'), ('Fixed Amount', 'Fixed Amount'), ('Rate(%)', 'Rate(%)')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='status',
            field=models.CharField(choices=[('Ready to start', 'Ready to start'), ('Cancelled', 'Cancelled'), ('Valid', 'Valid'), ('Paused', 'Paused'), ('Ended', 'Ended')], max_length=128),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='voucher_type',
            field=models.CharField(choices=[('Product Combo', 'Product Combo'), ('Free Gift', 'Free Gift'), ('Manual Discount', 'Manual Discount'), ('Discount Voucher', 'Discount Voucher')], max_length=128),
        ),
    ]
