# Generated by Django 3.2.16 on 2024-03-20 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20240320_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='approval_comments',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='area_code',
            field=models.CharField(choices=[('+7', '+7 (Russia)'), ('+52', '+52 (Mexico)'), ('+64', '+64 (New Zealand)'), ('+91', '+91 (India)'), ('+81', '+81 (Japan)'), ('+61', '+61 (Australia)'), ('+49', '+49 (Germany)'), ('+1', '+1 (US)'), ('+20', '+20 (Egypt)'), ('+33', '+33 (France)'), ('+82', '+82 (South Korea)'), ('+55', '+55 (Brazil)'), ('+86', '+86 (China)'), ('+34', '+34 (Spain)'), ('+44', '+44 (UK)'), ('+39', '+39 (Italy)'), ('+1', '+1 (Canada)'), ('+971', '+971 (UAE)'), ('+966', '+966 (Saudi Arabia)'), ('+65', '+65 (Singapore)')], max_length=128),
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='amount_trigger',
            field=models.CharField(choices=[('More than', 'More than'), (None, '-------'), ('More than and equals to', 'More than and equals to'), ('Equals to', 'Equals to'), ('Less than and equals to', 'Less than and equals to'), ('Less than', 'Less than')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='quantity_trigger',
            field=models.CharField(choices=[('More than', 'More than'), (None, '-------'), ('More than and equals to', 'More than and equals to'), ('Equals to', 'Equals to'), ('Less than and equals to', 'Less than and equals to'), ('Less than', 'Less than')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('Partially Delivered', 'Partially Delivered'), ('Pending', 'Pending'), ('Delivered', 'Delivered')], default='Pending', max_length=128),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='type',
            field=models.CharField(choices=[('Quotation', 'Quotation'), ('Purchase', 'Purchase')], max_length=128),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='discount_type',
            field=models.CharField(choices=[(None, '-------'), ('Rate(%)', 'Rate(%)'), ('Fixed Amount', 'Fixed Amount')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='status',
            field=models.CharField(choices=[('Ended', 'Ended'), ('Valid', 'Valid'), ('Paused', 'Paused'), ('Cancelled', 'Cancelled'), ('Ready to start', 'Ready to start')], max_length=128),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='voucher_type',
            field=models.CharField(choices=[('Free Gift', 'Free Gift'), ('Product Combo', 'Product Combo'), ('Discount Voucher', 'Discount Voucher'), ('Manual Discount', 'Manual Discount')], max_length=128),
        ),
    ]
