# Generated by Django 3.2.16 on 2024-03-27 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20240321_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='area_code',
            field=models.CharField(choices=[('+34', '+34 (Spain)'), ('+61', '+61 (Australia)'), ('+1', '+1 (US)'), ('+65', '+65 (Singapore)'), ('+64', '+64 (New Zealand)'), ('+39', '+39 (Italy)'), ('+20', '+20 (Egypt)'), ('+7', '+7 (Russia)'), ('+81', '+81 (Japan)'), ('+33', '+33 (France)'), ('+52', '+52 (Mexico)'), ('+1', '+1 (Canada)'), ('+49', '+49 (Germany)'), ('+55', '+55 (Brazil)'), ('+86', '+86 (China)'), ('+971', '+971 (UAE)'), ('+91', '+91 (India)'), ('+44', '+44 (UK)'), ('+966', '+966 (Saudi Arabia)'), ('+82', '+82 (South Korea)')], max_length=128),
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='amount_trigger',
            field=models.CharField(choices=[(None, '-------'), ('More than', 'More than'), ('More than and equals to', 'More than and equals to'), ('Less than and equals to', 'Less than and equals to'), ('Less than', 'Less than'), ('Equals to', 'Equals to')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='quantity_trigger',
            field=models.CharField(choices=[(None, '-------'), ('More than', 'More than'), ('More than and equals to', 'More than and equals to'), ('Less than and equals to', 'Less than and equals to'), ('Less than', 'Less than'), ('Equals to', 'Equals to')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(blank=True, default='pending payment', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Pending', 'Pending'), ('Partially Delivered', 'Partially Delivered')], default='Pending', max_length=128),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='type',
            field=models.CharField(choices=[('Quotation', 'Quotation'), ('Purchase', 'Purchase')], max_length=128),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='discount_type',
            field=models.CharField(choices=[('Fixed Amount', 'Fixed Amount'), ('Rate(%)', 'Rate(%)'), (None, '-------')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='status',
            field=models.CharField(choices=[('Ready to start', 'Ready to start'), ('Ended', 'Ended'), ('Cancelled', 'Cancelled'), ('Paused', 'Paused'), ('Valid', 'Valid')], max_length=128),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='voucher_type',
            field=models.CharField(choices=[('Manual Discount', 'Manual Discount'), ('Product Combo', 'Product Combo'), ('Discount Voucher', 'Discount Voucher'), ('Free Gift', 'Free Gift')], max_length=128),
        ),
    ]
