# Generated by Django 3.2.16 on 2024-03-27 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20240327_0603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.AlterField(
            model_name='customer',
            name='area_code',
            field=models.CharField(choices=[('+971', '+971 (UAE)'), ('+86', '+86 (China)'), ('+39', '+39 (Italy)'), ('+65', '+65 (Singapore)'), ('+91', '+91 (India)'), ('+7', '+7 (Russia)'), ('+34', '+34 (Spain)'), ('+52', '+52 (Mexico)'), ('+33', '+33 (France)'), ('+61', '+61 (Australia)'), ('+82', '+82 (South Korea)'), ('+49', '+49 (Germany)'), ('+81', '+81 (Japan)'), ('+55', '+55 (Brazil)'), ('+966', '+966 (Saudi Arabia)'), ('+20', '+20 (Egypt)'), ('+1', '+1 (US)'), ('+44', '+44 (UK)'), ('+1', '+1 (Canada)'), ('+64', '+64 (New Zealand)')], max_length=128),
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='amount_trigger',
            field=models.CharField(choices=[(None, '-------'), ('Equals to', 'Equals to'), ('More than and equals to', 'More than and equals to'), ('More than', 'More than'), ('Less than', 'Less than'), ('Less than and equals to', 'Less than and equals to')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='quantity_trigger',
            field=models.CharField(choices=[(None, '-------'), ('Equals to', 'Equals to'), ('More than and equals to', 'More than and equals to'), ('More than', 'More than'), ('Less than', 'Less than'), ('Less than and equals to', 'Less than and equals to')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('Partially Delivered', 'Partially Delivered'), ('Delivered', 'Delivered'), ('Pending', 'Pending')], default='Pending', max_length=128),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='discount_type',
            field=models.CharField(choices=[('Rate(%)', 'Rate(%)'), (None, '-------'), ('Fixed Amount', 'Fixed Amount')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='status',
            field=models.CharField(choices=[('Ready to start', 'Ready to start'), ('Cancelled', 'Cancelled'), ('Paused', 'Paused'), ('Valid', 'Valid'), ('Ended', 'Ended')], max_length=128),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='voucher_type',
            field=models.CharField(choices=[('Discount Voucher', 'Discount Voucher'), ('Product Combo', 'Product Combo'), ('Free Gift', 'Free Gift'), ('Manual Discount', 'Manual Discount')], max_length=128),
        ),
    ]
