# Generated by Django 3.2.16 on 2024-03-28 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20240327_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='area_code',
            field=models.CharField(choices=[('+34', '+34 (Spain)'), ('+55', '+55 (Brazil)'), ('+65', '+65 (Singapore)'), ('+7', '+7 (Russia)'), ('+39', '+39 (Italy)'), ('+966', '+966 (Saudi Arabia)'), ('+86', '+86 (China)'), ('+91', '+91 (India)'), ('+49', '+49 (Germany)'), ('+61', '+61 (Australia)'), ('+33', '+33 (France)'), ('+82', '+82 (South Korea)'), ('+44', '+44 (UK)'), ('+52', '+52 (Mexico)'), ('+64', '+64 (New Zealand)'), ('+1', '+1 (US)'), ('+1', '+1 (Canada)'), ('+971', '+971 (UAE)'), ('+20', '+20 (Egypt)'), ('+81', '+81 (Japan)')], max_length=128),
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='amount_trigger',
            field=models.CharField(choices=[('More than', 'More than'), ('Less than and equals to', 'Less than and equals to'), ('More than and equals to', 'More than and equals to'), (None, '-------'), ('Equals to', 'Equals to'), ('Less than', 'Less than')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='quantity_trigger',
            field=models.CharField(choices=[('More than', 'More than'), ('Less than and equals to', 'Less than and equals to'), ('More than and equals to', 'More than and equals to'), (None, '-------'), ('Equals to', 'Equals to'), ('Less than', 'Less than')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='type',
            field=models.CharField(choices=[('Invoice', 'Invoice'), ('Quotation', 'Quotation')], default='Invoice', max_length=50),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Partially Delivered', 'Partially Delivered'), ('Delivered', 'Delivered')], default='Pending', max_length=128),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='discount_type',
            field=models.CharField(choices=[('Fixed Amount', 'Fixed Amount'), (None, '-------'), ('Rate(%)', 'Rate(%)')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='status',
            field=models.CharField(choices=[('Ready to start', 'Ready to start'), ('Cancelled', 'Cancelled'), ('Ended', 'Ended'), ('Paused', 'Paused'), ('Valid', 'Valid')], max_length=128),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='voucher_type',
            field=models.CharField(choices=[('Discount Voucher', 'Discount Voucher'), ('Product Combo', 'Product Combo'), ('Manual Discount', 'Manual Discount'), ('Free Gift', 'Free Gift')], max_length=128),
        ),
    ]
