# Generated by Django 3.2.16 on 2024-03-28 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20240328_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='area_code',
            field=models.CharField(choices=[('+86', '+86 (China)'), ('+61', '+61 (Australia)'), ('+82', '+82 (South Korea)'), ('+52', '+52 (Mexico)'), ('+55', '+55 (Brazil)'), ('+64', '+64 (New Zealand)'), ('+49', '+49 (Germany)'), ('+91', '+91 (India)'), ('+20', '+20 (Egypt)'), ('+44', '+44 (UK)'), ('+7', '+7 (Russia)'), ('+34', '+34 (Spain)'), ('+39', '+39 (Italy)'), ('+33', '+33 (France)'), ('+1', '+1 (Canada)'), ('+81', '+81 (Japan)'), ('+971', '+971 (UAE)'), ('+1', '+1 (US)'), ('+966', '+966 (Saudi Arabia)'), ('+65', '+65 (Singapore)')], max_length=128),
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='amount_trigger',
            field=models.CharField(choices=[('Less than', 'Less than'), (None, '-------'), ('More than', 'More than'), ('Equals to', 'Equals to'), ('More than and equals to', 'More than and equals to'), ('Less than and equals to', 'Less than and equals to')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='quantity_trigger',
            field=models.CharField(choices=[('Less than', 'Less than'), (None, '-------'), ('More than', 'More than'), ('Equals to', 'Equals to'), ('More than and equals to', 'More than and equals to'), ('Less than and equals to', 'Less than and equals to')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='payment_method',
            field=models.CharField(choices=[('Bank Transfer/Cheque', 'Bank Transfer/Cheque'), ('COD', 'COD')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Pending', 'Pending'), ('Partially Delivered', 'Partially Delivered')], default='Pending', max_length=128),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='status',
            field=models.CharField(choices=[('Cancelled', 'Cancelled'), ('Paused', 'Paused'), ('Valid', 'Valid'), ('Ready to start', 'Ready to start'), ('Ended', 'Ended')], max_length=128),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='voucher_type',
            field=models.CharField(choices=[('Discount Voucher', 'Discount Voucher'), ('Free Gift', 'Free Gift'), ('Manual Discount', 'Manual Discount'), ('Product Combo', 'Product Combo')], max_length=128),
        ),
    ]
