# Generated by Django 3.2.16 on 2024-04-01 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20240328_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='can_change_sales_person',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='is_notify',
            field=models.BooleanField(default=False, help_text='Only true when user is click to submit while creating order.'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='area_code',
            field=models.CharField(choices=[('+91', '+91 (India)'), ('+81', '+81 (Japan)'), ('+61', '+61 (Australia)'), ('+55', '+55 (Brazil)'), ('+82', '+82 (South Korea)'), ('+7', '+7 (Russia)'), ('+971', '+971 (UAE)'), ('+34', '+34 (Spain)'), ('+64', '+64 (New Zealand)'), ('+65', '+65 (Singapore)'), ('+33', '+33 (France)'), ('+20', '+20 (Egypt)'), ('+44', '+44 (UK)'), ('+1', '+1 (US)'), ('+49', '+49 (Germany)'), ('+1', '+1 (Canada)'), ('+39', '+39 (Italy)'), ('+966', '+966 (Saudi Arabia)'), ('+86', '+86 (China)'), ('+52', '+52 (Mexico)')], max_length=128),
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='amount_trigger',
            field=models.CharField(choices=[('Less than and equals to', 'Less than and equals to'), ('Less than', 'Less than'), ('More than', 'More than'), ('Equals to', 'Equals to'), ('More than and equals to', 'More than and equals to'), (None, '-------')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='quantity_trigger',
            field=models.CharField(choices=[('Less than and equals to', 'Less than and equals to'), ('Less than', 'Less than'), ('More than', 'More than'), ('Equals to', 'Equals to'), ('More than and equals to', 'More than and equals to'), (None, '-------')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Partially Delivered', 'Partially Delivered'), ('Pending', 'Pending')], default='Pending', max_length=128),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='type',
            field=models.CharField(choices=[('Purchase', 'Purchase'), ('Quotation', 'Quotation')], max_length=128),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='discount_type',
            field=models.CharField(choices=[('Fixed Amount', 'Fixed Amount'), ('Rate(%)', 'Rate(%)'), (None, '-------')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='status',
            field=models.CharField(choices=[('Paused', 'Paused'), ('Ready to start', 'Ready to start'), ('Valid', 'Valid'), ('Ended', 'Ended'), ('Cancelled', 'Cancelled')], max_length=128),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='voucher_type',
            field=models.CharField(choices=[('Product Combo', 'Product Combo'), ('Free Gift', 'Free Gift'), ('Manual Discount', 'Manual Discount'), ('Discount Voucher', 'Discount Voucher')], max_length=128),
        ),
    ]
