# Generated by Django 3.2.16 on 2024-04-02 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20240401_1230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='can_change_sales_person',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_notify',
        ),
        migrations.AlterField(
            model_name='customer',
            name='area_code',
            field=models.CharField(choices=[('+91', '+91 (India)'), ('+33', '+33 (France)'), ('+1', '+1 (Canada)'), ('+1', '+1 (US)'), ('+966', '+966 (Saudi Arabia)'), ('+55', '+55 (Brazil)'), ('+65', '+65 (Singapore)'), ('+82', '+82 (South Korea)'), ('+44', '+44 (UK)'), ('+7', '+7 (Russia)'), ('+81', '+81 (Japan)'), ('+971', '+971 (UAE)'), ('+64', '+64 (New Zealand)'), ('+49', '+49 (Germany)'), ('+34', '+34 (Spain)'), ('+20', '+20 (Egypt)'), ('+61', '+61 (Australia)'), ('+52', '+52 (Mexico)'), ('+86', '+86 (China)'), ('+39', '+39 (Italy)')], max_length=128),
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='amount_trigger',
            field=models.CharField(choices=[('More than', 'More than'), ('Equals to', 'Equals to'), ('Less than', 'Less than'), ('Less than and equals to', 'Less than and equals to'), ('More than and equals to', 'More than and equals to'), (None, '-------')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='quantity_trigger',
            field=models.CharField(choices=[('More than', 'More than'), ('Equals to', 'Equals to'), ('Less than', 'Less than'), ('Less than and equals to', 'Less than and equals to'), ('More than and equals to', 'More than and equals to'), (None, '-------')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Pending', 'Pending'), ('Partially Delivered', 'Partially Delivered')], default='Pending', max_length=128),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='type',
            field=models.CharField(choices=[('Quotation', 'Quotation'), ('Purchase', 'Purchase')], max_length=128),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='discount_type',
            field=models.CharField(choices=[('Rate(%)', 'Rate(%)'), ('Fixed Amount', 'Fixed Amount'), (None, '-------')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='status',
            field=models.CharField(choices=[('Paused', 'Paused'), ('Valid', 'Valid'), ('Ready to start', 'Ready to start'), ('Cancelled', 'Cancelled'), ('Ended', 'Ended')], max_length=128),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='voucher_type',
            field=models.CharField(choices=[('Product Combo', 'Product Combo'), ('Discount Voucher', 'Discount Voucher'), ('Free Gift', 'Free Gift'), ('Manual Discount', 'Manual Discount')], max_length=128),
        ),
    ]
