# Generated by Django 3.2.16 on 2024-04-02 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_auto_20240402_0423'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='can_change_sales_person',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='area_code',
            field=models.CharField(choices=[('+39', '+39 (Italy)'), ('+65', '+65 (Singapore)'), ('+52', '+52 (Mexico)'), ('+86', '+86 (China)'), ('+966', '+966 (Saudi Arabia)'), ('+91', '+91 (India)'), ('+81', '+81 (Japan)'), ('+44', '+44 (UK)'), ('+61', '+61 (Australia)'), ('+971', '+971 (UAE)'), ('+49', '+49 (Germany)'), ('+82', '+82 (South Korea)'), ('+1', '+1 (Canada)'), ('+1', '+1 (US)'), ('+64', '+64 (New Zealand)'), ('+20', '+20 (Egypt)'), ('+7', '+7 (Russia)'), ('+55', '+55 (Brazil)'), ('+34', '+34 (Spain)'), ('+33', '+33 (France)')], max_length=128),
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='amount_trigger',
            field=models.CharField(choices=[('Less than and equals to', 'Less than and equals to'), ('Equals to', 'Equals to'), ('More than', 'More than'), ('More than and equals to', 'More than and equals to'), ('Less than', 'Less than'), (None, '-------')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='quantity_trigger',
            field=models.CharField(choices=[('Less than and equals to', 'Less than and equals to'), ('Equals to', 'Equals to'), ('More than', 'More than'), ('More than and equals to', 'More than and equals to'), ('Less than', 'Less than'), (None, '-------')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'COD'), ('Bank Transfer/Cheque', 'Bank Transfer/Cheque')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='status',
            field=models.CharField(choices=[('Cancelled', 'Cancelled'), ('Ready to start', 'Ready to start'), ('Ended', 'Ended'), ('Paused', 'Paused'), ('Valid', 'Valid')], max_length=128),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='voucher_type',
            field=models.CharField(choices=[('Discount Voucher', 'Discount Voucher'), ('Manual Discount', 'Manual Discount'), ('Free Gift', 'Free Gift'), ('Product Combo', 'Product Combo')], max_length=128),
        ),
        migrations.CreateModel(
            name='Order_notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.order')),
            ],
        ),
    ]
