# Generated by Django 3.2.16 on 2024-04-03 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_auto_20240402_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_approve',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='area_code',
            field=models.CharField(choices=[('+65', '+65 (Singapore)'), ('+52', '+52 (Mexico)'), ('+55', '+55 (Brazil)'), ('+86', '+86 (China)'), ('+44', '+44 (UK)'), ('+64', '+64 (New Zealand)'), ('+33', '+33 (France)'), ('+971', '+971 (UAE)'), ('+81', '+81 (Japan)'), ('+61', '+61 (Australia)'), ('+34', '+34 (Spain)'), ('+966', '+966 (Saudi Arabia)'), ('+39', '+39 (Italy)'), ('+82', '+82 (South Korea)'), ('+49', '+49 (Germany)'), ('+91', '+91 (India)'), ('+7', '+7 (Russia)'), ('+20', '+20 (Egypt)'), ('+1', '+1 (US)'), ('+1', '+1 (Canada)')], max_length=128),
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='amount_trigger',
            field=models.CharField(choices=[('More than', 'More than'), ('Equals to', 'Equals to'), (None, '-------'), ('More than and equals to', 'More than and equals to'), ('Less than and equals to', 'Less than and equals to'), ('Less than', 'Less than')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='quantity_trigger',
            field=models.CharField(choices=[('More than', 'More than'), ('Equals to', 'Equals to'), (None, '-------'), ('More than and equals to', 'More than and equals to'), ('Less than and equals to', 'Less than and equals to'), ('Less than', 'Less than')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='order_notification',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='payment_method',
            field=models.CharField(choices=[('Bank Transfer/Cheque', 'Bank Transfer/Cheque'), ('COD', 'COD')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Partially Delivered', 'Partially Delivered'), ('Pending', 'Pending')], default='Pending', max_length=128),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='type',
            field=models.CharField(choices=[('Purchase', 'Purchase'), ('Quotation', 'Quotation')], max_length=128),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='discount_type',
            field=models.CharField(choices=[(None, '-------'), ('Rate(%)', 'Rate(%)'), ('Fixed Amount', 'Fixed Amount')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='status',
            field=models.CharField(choices=[('Valid', 'Valid'), ('Ready to start', 'Ready to start'), ('Ended', 'Ended'), ('Cancelled', 'Cancelled'), ('Paused', 'Paused')], max_length=128),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='voucher_type',
            field=models.CharField(choices=[('Manual Discount', 'Manual Discount'), ('Product Combo', 'Product Combo'), ('Discount Voucher', 'Discount Voucher'), ('Free Gift', 'Free Gift')], max_length=128),
        ),
    ]
