# Generated by Django 3.2.16 on 2024-04-05 05:06

import apps.home.model.supplier
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20240403_1010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='phone_number',
            new_name='contact_person_1',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='address_line1',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='address_line2',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='city',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='code',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='country',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='english_name',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='landmark',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='name',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='state',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='town',
        ),
        migrations.AddField(
            model_name='supplier',
            name='company_name',
            field=models.CharField(default='test', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplier',
            name='contact_person_2',
            field=models.CharField(blank=True, max_length=128, null=True, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Only Numbers are allowed.')]),
        ),
        migrations.AddField(
            model_name='supplier',
            name='contact_type',
            field=models.CharField(default='HK', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplier',
            name='currency',
            field=models.CharField(default='HKD', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplier',
            name='location',
            field=models.CharField(default='test', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplier',
            name='phone_1',
            field=models.CharField(blank=True, max_length=128, null=True, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Only Numbers are allowed.')]),
        ),
        migrations.AddField(
            model_name='supplier',
            name='phone_2',
            field=models.CharField(blank=True, max_length=128, null=True, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Only Numbers are allowed.')]),
        ),
        migrations.AddField(
            model_name='supplier',
            name='prefix',
            field=models.CharField(default='+91', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplier',
            name='product_type',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplier',
            name='purchasing_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='remark',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='supplier_id',
            field=models.CharField(default=123456, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplier',
            name='supplier_type',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplier',
            name='website',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='area_code',
            field=models.CharField(choices=[('+52', '+52 (Mexico)'), ('+34', '+34 (Spain)'), ('+61', '+61 (Australia)'), ('+20', '+20 (Egypt)'), ('+65', '+65 (Singapore)'), ('+1', '+1 (US)'), ('+966', '+966 (Saudi Arabia)'), ('+55', '+55 (Brazil)'), ('+86', '+86 (China)'), ('+33', '+33 (France)'), ('+82', '+82 (South Korea)'), ('+91', '+91 (India)'), ('+49', '+49 (Germany)'), ('+64', '+64 (New Zealand)'), ('+1', '+1 (Canada)'), ('+81', '+81 (Japan)'), ('+44', '+44 (UK)'), ('+7', '+7 (Russia)'), ('+39', '+39 (Italy)'), ('+971', '+971 (UAE)')], max_length=128),
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='amount_trigger',
            field=models.CharField(choices=[('Less than', 'Less than'), ('More than', 'More than'), (None, '-------'), ('Equals to', 'Equals to'), ('Less than and equals to', 'Less than and equals to'), ('More than and equals to', 'More than and equals to')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='quantity_trigger',
            field=models.CharField(choices=[('Less than', 'Less than'), ('More than', 'More than'), (None, '-------'), ('Equals to', 'Equals to'), ('Less than and equals to', 'Less than and equals to'), ('More than and equals to', 'More than and equals to')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'COD'), ('Bank Transfer/Cheque', 'Bank Transfer/Cheque')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Delivered', 'Delivered'), ('Partially Delivered', 'Partially Delivered')], default='Pending', max_length=128),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='type',
            field=models.CharField(choices=[('Quotation', 'Quotation'), ('Purchase', 'Purchase')], max_length=128),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='status',
            field=models.CharField(choices=[('Paused', 'Paused'), ('Ready to start', 'Ready to start'), ('Ended', 'Ended'), ('Cancelled', 'Cancelled'), ('Valid', 'Valid')], max_length=128),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='voucher_type',
            field=models.CharField(choices=[('Free Gift', 'Free Gift'), ('Discount Voucher', 'Discount Voucher'), ('Manual Discount', 'Manual Discount'), ('Product Combo', 'Product Combo')], max_length=128),
        ),
        migrations.CreateModel(
            name='Supplier_Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to=apps.home.model.supplier.get_file_path)),
                ('file_name', models.CharField(blank=True, max_length=500, null=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.supplier')),
            ],
        ),
    ]
