# Generated by Django 3.2.16 on 2024-04-05 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_auto_20240405_0630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='area_code',
            field=models.CharField(choices=[('+65', '+65 (Singapore)'), ('+20', '+20 (Egypt)'), ('+44', '+44 (UK)'), ('+1', '+1 (US)'), ('+7', '+7 (Russia)'), ('+966', '+966 (Saudi Arabia)'), ('+39', '+39 (Italy)'), ('+1', '+1 (Canada)'), ('+61', '+61 (Australia)'), ('+52', '+52 (Mexico)'), ('+81', '+81 (Japan)'), ('+34', '+34 (Spain)'), ('+55', '+55 (Brazil)'), ('+64', '+64 (New Zealand)'), ('+86', '+86 (China)'), ('+91', '+91 (India)'), ('+33', '+33 (France)'), ('+971', '+971 (UAE)'), ('+82', '+82 (South Korea)'), ('+49', '+49 (Germany)')], max_length=128),
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='amount_trigger',
            field=models.CharField(choices=[('More than and equals to', 'More than and equals to'), ('Equals to', 'Equals to'), ('Less than', 'Less than'), ('More than', 'More than'), (None, '-------'), ('Less than and equals to', 'Less than and equals to')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='quantity_trigger',
            field=models.CharField(choices=[('More than and equals to', 'More than and equals to'), ('Equals to', 'Equals to'), ('Less than', 'Less than'), ('More than', 'More than'), (None, '-------'), ('Less than and equals to', 'Less than and equals to')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'COD'), ('Bank Transfer/Cheque', 'Bank Transfer/Cheque')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='prefix',
            field=models.CharField(choices=[('+65', '+65 (Singapore)'), ('+20', '+20 (Egypt)'), ('+44', '+44 (UK)'), ('+1', '+1 (US)'), ('+7', '+7 (Russia)'), ('+966', '+966 (Saudi Arabia)'), ('+39', '+39 (Italy)'), ('+1', '+1 (Canada)'), ('+61', '+61 (Australia)'), ('+52', '+52 (Mexico)'), ('+81', '+81 (Japan)'), ('+34', '+34 (Spain)'), ('+55', '+55 (Brazil)'), ('+64', '+64 (New Zealand)'), ('+86', '+86 (China)'), ('+91', '+91 (India)'), ('+33', '+33 (France)'), ('+971', '+971 (UAE)'), ('+82', '+82 (South Korea)'), ('+49', '+49 (Germany)')], max_length=250),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='discount_type',
            field=models.CharField(choices=[(None, '-------'), ('Rate(%)', 'Rate(%)'), ('Fixed Amount', 'Fixed Amount')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='status',
            field=models.CharField(choices=[('Valid', 'Valid'), ('Ended', 'Ended'), ('Paused', 'Paused'), ('Cancelled', 'Cancelled'), ('Ready to start', 'Ready to start')], max_length=128),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='voucher_type',
            field=models.CharField(choices=[('Free Gift', 'Free Gift'), ('Product Combo', 'Product Combo'), ('Manual Discount', 'Manual Discount'), ('Discount Voucher', 'Discount Voucher')], max_length=128),
        ),
    ]
