# Generated by Django 3.2.16 on 2024-04-05 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0026_auto_20240405_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='authentication.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='area_code',
            field=models.CharField(choices=[('+39', '+39 (Italy)'), ('+86', '+86 (China)'), ('+81', '+81 (Japan)'), ('+52', '+52 (Mexico)'), ('+65', '+65 (Singapore)'), ('+64', '+64 (New Zealand)'), ('+966', '+966 (Saudi Arabia)'), ('+971', '+971 (UAE)'), ('+20', '+20 (Egypt)'), ('+7', '+7 (Russia)'), ('+34', '+34 (Spain)'), ('+1', '+1 (Canada)'), ('+1', '+1 (US)'), ('+33', '+33 (France)'), ('+82', '+82 (South Korea)'), ('+49', '+49 (Germany)'), ('+61', '+61 (Australia)'), ('+55', '+55 (Brazil)'), ('+44', '+44 (UK)'), ('+91', '+91 (India)')], max_length=128),
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='amount_trigger',
            field=models.CharField(choices=[('Less than and equals to', 'Less than and equals to'), ('Equals to', 'Equals to'), ('More than', 'More than'), ('More than and equals to', 'More than and equals to'), ('Less than', 'Less than'), (None, '-------')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='quantity_trigger',
            field=models.CharField(choices=[('Less than and equals to', 'Less than and equals to'), ('Equals to', 'Equals to'), ('More than', 'More than'), ('More than and equals to', 'More than and equals to'), ('Less than', 'Less than'), (None, '-------')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Pending', 'Pending'), ('Partially Delivered', 'Partially Delivered')], default='Pending', max_length=128),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='type',
            field=models.CharField(choices=[('Quotation', 'Quotation'), ('Purchase', 'Purchase')], max_length=128),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='prefix',
            field=models.CharField(choices=[('+39', '+39 (Italy)'), ('+86', '+86 (China)'), ('+81', '+81 (Japan)'), ('+52', '+52 (Mexico)'), ('+65', '+65 (Singapore)'), ('+64', '+64 (New Zealand)'), ('+966', '+966 (Saudi Arabia)'), ('+971', '+971 (UAE)'), ('+20', '+20 (Egypt)'), ('+7', '+7 (Russia)'), ('+34', '+34 (Spain)'), ('+1', '+1 (Canada)'), ('+1', '+1 (US)'), ('+33', '+33 (France)'), ('+82', '+82 (South Korea)'), ('+49', '+49 (Germany)'), ('+61', '+61 (Australia)'), ('+55', '+55 (Brazil)'), ('+44', '+44 (UK)'), ('+91', '+91 (India)')], max_length=250),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='status',
            field=models.CharField(choices=[('Ready to start', 'Ready to start'), ('Paused', 'Paused'), ('Ended', 'Ended'), ('Cancelled', 'Cancelled'), ('Valid', 'Valid')], max_length=128),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='voucher_type',
            field=models.CharField(choices=[('Free Gift', 'Free Gift'), ('Manual Discount', 'Manual Discount'), ('Product Combo', 'Product Combo'), ('Discount Voucher', 'Discount Voucher')], max_length=128),
        ),
        migrations.CreateModel(
            name='SystemParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('system_parameter', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=250)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
