# Generated by Django 3.2.16 on 2024-04-08 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_auto_20240405_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='area_code',
            field=models.CharField(choices=[('+49', '+49 (Germany)'), ('+34', '+34 (Spain)'), ('+86', '+86 (China)'), ('+971', '+971 (UAE)'), ('+20', '+20 (Egypt)'), ('+7', '+7 (Russia)'), ('+966', '+966 (Saudi Arabia)'), ('+1', '+1 (Canada)'), ('+33', '+33 (France)'), ('+91', '+91 (India)'), ('+61', '+61 (Australia)'), ('+52', '+52 (Mexico)'), ('+44', '+44 (UK)'), ('+1', '+1 (US)'), ('+55', '+55 (Brazil)'), ('+39', '+39 (Italy)'), ('+65', '+65 (Singapore)'), ('+81', '+81 (Japan)'), ('+82', '+82 (South Korea)'), ('+64', '+64 (New Zealand)')], max_length=128),
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='amount_trigger',
            field=models.CharField(choices=[('More than', 'More than'), ('Less than and equals to', 'Less than and equals to'), ('Equals to', 'Equals to'), (None, '-------'), ('More than and equals to', 'More than and equals to'), ('Less than', 'Less than')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='quantity_trigger',
            field=models.CharField(choices=[('More than', 'More than'), ('Less than and equals to', 'Less than and equals to'), ('Equals to', 'Equals to'), (None, '-------'), ('More than and equals to', 'More than and equals to'), ('Less than', 'Less than')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='payment_method',
            field=models.CharField(choices=[('Bank Transfer/Cheque', 'Bank Transfer/Cheque'), ('COD', 'COD')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Partially Delivered', 'Partially Delivered'), ('Pending', 'Pending')], default='Pending', max_length=128),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='prefix',
            field=models.CharField(choices=[('+49', '+49 (Germany)'), ('+34', '+34 (Spain)'), ('+86', '+86 (China)'), ('+971', '+971 (UAE)'), ('+20', '+20 (Egypt)'), ('+7', '+7 (Russia)'), ('+966', '+966 (Saudi Arabia)'), ('+1', '+1 (Canada)'), ('+33', '+33 (France)'), ('+91', '+91 (India)'), ('+61', '+61 (Australia)'), ('+52', '+52 (Mexico)'), ('+44', '+44 (UK)'), ('+1', '+1 (US)'), ('+55', '+55 (Brazil)'), ('+39', '+39 (Italy)'), ('+65', '+65 (Singapore)'), ('+81', '+81 (Japan)'), ('+82', '+82 (South Korea)'), ('+64', '+64 (New Zealand)')], max_length=250),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplier_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='discount_type',
            field=models.CharField(choices=[(None, '-------'), ('Fixed Amount', 'Fixed Amount'), ('Rate(%)', 'Rate(%)')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='status',
            field=models.CharField(choices=[('Valid', 'Valid'), ('Ended', 'Ended'), ('Ready to start', 'Ready to start'), ('Paused', 'Paused'), ('Cancelled', 'Cancelled')], max_length=128),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='voucher_type',
            field=models.CharField(choices=[('Product Combo', 'Product Combo'), ('Discount Voucher', 'Discount Voucher'), ('Manual Discount', 'Manual Discount'), ('Free Gift', 'Free Gift')], max_length=128),
        ),
    ]
