# Generated by Django 3.2.16 on 2024-04-10 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_auto_20240408_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='area_code',
            field=models.CharField(choices=[('+1', '+1 (Canada)'), ('+44', '+44 (UK)'), ('+33', '+33 (France)'), ('+1', '+1 (US)'), ('+49', '+49 (Germany)'), ('+7', '+7 (Russia)'), ('+82', '+82 (South Korea)'), ('+971', '+971 (UAE)'), ('+64', '+64 (New Zealand)'), ('+52', '+52 (Mexico)'), ('+55', '+55 (Brazil)'), ('+86', '+86 (China)'), ('+81', '+81 (Japan)'), ('+20', '+20 (Egypt)'), ('+39', '+39 (Italy)'), ('+34', '+34 (Spain)'), ('+61', '+61 (Australia)'), ('+966', '+966 (Saudi Arabia)'), ('+91', '+91 (India)'), ('+65', '+65 (Singapore)')], max_length=128),
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='amount_trigger',
            field=models.CharField(choices=[('Less than and equals to', 'Less than and equals to'), ('Equals to', 'Equals to'), ('Less than', 'Less than'), ('More than', 'More than'), ('More than and equals to', 'More than and equals to'), (None, '-------')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='quantity_trigger',
            field=models.CharField(choices=[('Less than and equals to', 'Less than and equals to'), ('Equals to', 'Equals to'), ('Less than', 'Less than'), ('More than', 'More than'), ('More than and equals to', 'More than and equals to'), (None, '-------')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Partially Delivered', 'Partially Delivered'), ('Delivered', 'Delivered')], default='Pending', max_length=128),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='prefix',
            field=models.CharField(choices=[('+1', '+1 (Canada)'), ('+44', '+44 (UK)'), ('+33', '+33 (France)'), ('+1', '+1 (US)'), ('+49', '+49 (Germany)'), ('+7', '+7 (Russia)'), ('+82', '+82 (South Korea)'), ('+971', '+971 (UAE)'), ('+64', '+64 (New Zealand)'), ('+52', '+52 (Mexico)'), ('+55', '+55 (Brazil)'), ('+86', '+86 (China)'), ('+81', '+81 (Japan)'), ('+20', '+20 (Egypt)'), ('+39', '+39 (Italy)'), ('+34', '+34 (Spain)'), ('+61', '+61 (Australia)'), ('+966', '+966 (Saudi Arabia)'), ('+91', '+91 (India)'), ('+65', '+65 (Singapore)')], max_length=250),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='discount_type',
            field=models.CharField(choices=[('Fixed Amount', 'Fixed Amount'), (None, '-------'), ('Rate(%)', 'Rate(%)')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='status',
            field=models.CharField(choices=[('Paused', 'Paused'), ('Ready to start', 'Ready to start'), ('Valid', 'Valid'), ('Cancelled', 'Cancelled'), ('Ended', 'Ended')], max_length=128),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='voucher_type',
            field=models.CharField(choices=[('Free Gift', 'Free Gift'), ('Discount Voucher', 'Discount Voucher'), ('Product Combo', 'Product Combo'), ('Manual Discount', 'Manual Discount')], max_length=128),
        ),
    ]
