# Generated by Django 3.2.16 on 2024-04-10 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_auto_20240410_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='area_code',
            field=models.CharField(choices=[('+971', '+971 (UAE)'), ('+34', '+34 (Spain)'), ('+39', '+39 (Italy)'), ('+966', '+966 (Saudi Arabia)'), ('+61', '+61 (Australia)'), ('+91', '+91 (India)'), ('+81', '+81 (Japan)'), ('+20', '+20 (Egypt)'), ('+55', '+55 (Brazil)'), ('+1', '+1 (Canada)'), ('+65', '+65 (Singapore)'), ('+1', '+1 (US)'), ('+44', '+44 (UK)'), ('+49', '+49 (Germany)'), ('+86', '+86 (China)'), ('+52', '+52 (Mexico)'), ('+7', '+7 (Russia)'), ('+82', '+82 (South Korea)'), ('+64', '+64 (New Zealand)'), ('+33', '+33 (France)')], max_length=128),
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='amount_trigger',
            field=models.CharField(choices=[('More than', 'More than'), ('More than and equals to', 'More than and equals to'), ('Less than and equals to', 'Less than and equals to'), ('Less than', 'Less than'), (None, '-------'), ('Equals to', 'Equals to')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='quantity_trigger',
            field=models.CharField(choices=[('More than', 'More than'), ('More than and equals to', 'More than and equals to'), ('Less than and equals to', 'Less than and equals to'), ('Less than', 'Less than'), (None, '-------'), ('Equals to', 'Equals to')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='payment_method',
            field=models.CharField(choices=[('Bank Transfer/Cheque', 'Bank Transfer/Cheque'), ('COD', 'COD')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('Partially Delivered', 'Partially Delivered'), ('Delivered', 'Delivered'), ('Pending', 'Pending')], default='Pending', max_length=128),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='type',
            field=models.CharField(choices=[('Purchase', 'Purchase'), ('Quotation', 'Quotation')], max_length=128),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='prefix',
            field=models.CharField(choices=[('+971', '+971 (UAE)'), ('+34', '+34 (Spain)'), ('+39', '+39 (Italy)'), ('+966', '+966 (Saudi Arabia)'), ('+61', '+61 (Australia)'), ('+91', '+91 (India)'), ('+81', '+81 (Japan)'), ('+20', '+20 (Egypt)'), ('+55', '+55 (Brazil)'), ('+1', '+1 (Canada)'), ('+65', '+65 (Singapore)'), ('+1', '+1 (US)'), ('+44', '+44 (UK)'), ('+49', '+49 (Germany)'), ('+86', '+86 (China)'), ('+52', '+52 (Mexico)'), ('+7', '+7 (Russia)'), ('+82', '+82 (South Korea)'), ('+64', '+64 (New Zealand)'), ('+33', '+33 (France)')], max_length=250),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='status',
            field=models.CharField(choices=[('Ended', 'Ended'), ('Paused', 'Paused'), ('Ready to start', 'Ready to start'), ('Cancelled', 'Cancelled'), ('Valid', 'Valid')], max_length=128),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='voucher_type',
            field=models.CharField(choices=[('Manual Discount', 'Manual Discount'), ('Free Gift', 'Free Gift'), ('Product Combo', 'Product Combo'), ('Discount Voucher', 'Discount Voucher')], max_length=128),
        ),
    ]
