# Generated by Django 3.2.16 on 2024-04-11 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_auto_20240410_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='area_code',
            field=models.CharField(choices=[('+49', '+49 (Germany)'), ('+65', '+65 (Singapore)'), ('+34', '+34 (Spain)'), ('+81', '+81 (Japan)'), ('+971', '+971 (UAE)'), ('+86', '+86 (China)'), ('+61', '+61 (Australia)'), ('+33', '+33 (France)'), ('+82', '+82 (South Korea)'), ('+1', '+1 (Canada)'), ('+44', '+44 (UK)'), ('+55', '+55 (Brazil)'), ('+91', '+91 (India)'), ('+64', '+64 (New Zealand)'), ('+7', '+7 (Russia)'), ('+1', '+1 (US)'), ('+39', '+39 (Italy)'), ('+20', '+20 (Egypt)'), ('+52', '+52 (Mexico)'), ('+966', '+966 (Saudi Arabia)')], max_length=128),
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='amount_trigger',
            field=models.CharField(choices=[('Equals to', 'Equals to'), (None, '-------'), ('Less than', 'Less than'), ('Less than and equals to', 'Less than and equals to'), ('More than', 'More than'), ('More than and equals to', 'More than and equals to')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='quantity_trigger',
            field=models.CharField(choices=[('Equals to', 'Equals to'), (None, '-------'), ('Less than', 'Less than'), ('Less than and equals to', 'Less than and equals to'), ('More than', 'More than'), ('More than and equals to', 'More than and equals to')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'COD'), ('Bank Transfer/Cheque', 'Bank Transfer/Cheque')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('Partially Delivered', 'Partially Delivered'), ('Pending', 'Pending'), ('Delivered', 'Delivered')], default='Pending', max_length=128),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='type',
            field=models.CharField(choices=[('Quotation', 'Quotation'), ('Purchase', 'Purchase')], max_length=128),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='contact_person_1',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='contact_person_2',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='prefix',
            field=models.CharField(choices=[('+49', '+49 (Germany)'), ('+65', '+65 (Singapore)'), ('+34', '+34 (Spain)'), ('+81', '+81 (Japan)'), ('+971', '+971 (UAE)'), ('+86', '+86 (China)'), ('+61', '+61 (Australia)'), ('+33', '+33 (France)'), ('+82', '+82 (South Korea)'), ('+1', '+1 (Canada)'), ('+44', '+44 (UK)'), ('+55', '+55 (Brazil)'), ('+91', '+91 (India)'), ('+64', '+64 (New Zealand)'), ('+7', '+7 (Russia)'), ('+1', '+1 (US)'), ('+39', '+39 (Italy)'), ('+20', '+20 (Egypt)'), ('+52', '+52 (Mexico)'), ('+966', '+966 (Saudi Arabia)')], max_length=250),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='status',
            field=models.CharField(choices=[('Cancelled', 'Cancelled'), ('Valid', 'Valid'), ('Ready to start', 'Ready to start'), ('Paused', 'Paused'), ('Ended', 'Ended')], max_length=128),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='voucher_type',
            field=models.CharField(choices=[('Product Combo', 'Product Combo'), ('Free Gift', 'Free Gift'), ('Discount Voucher', 'Discount Voucher'), ('Manual Discount', 'Manual Discount')], max_length=128),
        ),
    ]
