# Generated by Django 3.2.16 on 2024-04-15 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_auto_20240411_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_notification',
            name='approval_for',
            field=models.CharField(default='sales_person', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='area_code',
            field=models.CharField(choices=[('+91', '+91 (India)'), ('+55', '+55 (Brazil)'), ('+1', '+1 (Canada)'), ('+82', '+82 (South Korea)'), ('+1', '+1 (US)'), ('+81', '+81 (Japan)'), ('+86', '+86 (China)'), ('+33', '+33 (France)'), ('+44', '+44 (UK)'), ('+39', '+39 (Italy)'), ('+61', '+61 (Australia)'), ('+64', '+64 (New Zealand)'), ('+7', '+7 (Russia)'), ('+49', '+49 (Germany)'), ('+34', '+34 (Spain)'), ('+966', '+966 (Saudi Arabia)'), ('+52', '+52 (Mexico)'), ('+971', '+971 (UAE)'), ('+20', '+20 (Egypt)'), ('+65', '+65 (Singapore)')], max_length=128),
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='amount_trigger',
            field=models.CharField(choices=[('More than', 'More than'), ('Equals to', 'Equals to'), ('Less than', 'Less than'), ('More than and equals to', 'More than and equals to'), (None, '-------'), ('Less than and equals to', 'Less than and equals to')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='quantity_trigger',
            field=models.CharField(choices=[('More than', 'More than'), ('Equals to', 'Equals to'), ('Less than', 'Less than'), ('More than and equals to', 'More than and equals to'), (None, '-------'), ('Less than and equals to', 'Less than and equals to')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='payment_method',
            field=models.CharField(choices=[('Bank Transfer/Cheque', 'Bank Transfer/Cheque'), ('COD', 'COD')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Pending', 'Pending'), ('Partially Delivered', 'Partially Delivered')], default='Pending', max_length=128),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='type',
            field=models.CharField(choices=[('Purchase', 'Purchase'), ('Quotation', 'Quotation')], max_length=128),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='prefix',
            field=models.CharField(choices=[('+91', '+91 (India)'), ('+55', '+55 (Brazil)'), ('+1', '+1 (Canada)'), ('+82', '+82 (South Korea)'), ('+1', '+1 (US)'), ('+81', '+81 (Japan)'), ('+86', '+86 (China)'), ('+33', '+33 (France)'), ('+44', '+44 (UK)'), ('+39', '+39 (Italy)'), ('+61', '+61 (Australia)'), ('+64', '+64 (New Zealand)'), ('+7', '+7 (Russia)'), ('+49', '+49 (Germany)'), ('+34', '+34 (Spain)'), ('+966', '+966 (Saudi Arabia)'), ('+52', '+52 (Mexico)'), ('+971', '+971 (UAE)'), ('+20', '+20 (Egypt)'), ('+65', '+65 (Singapore)')], max_length=250),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='discount_type',
            field=models.CharField(choices=[('Fixed Amount', 'Fixed Amount'), ('Rate(%)', 'Rate(%)'), (None, '-------')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='status',
            field=models.CharField(choices=[('Ended', 'Ended'), ('Ready to start', 'Ready to start'), ('Valid', 'Valid'), ('Cancelled', 'Cancelled'), ('Paused', 'Paused')], max_length=128),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='voucher_type',
            field=models.CharField(choices=[('Manual Discount', 'Manual Discount'), ('Product Combo', 'Product Combo'), ('Discount Voucher', 'Discount Voucher'), ('Free Gift', 'Free Gift')], max_length=128),
        ),
    ]
