# Generated by Django 3.2.16 on 2024-04-17 06:54

import apps.home.model.customer
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0033_auto_20240415_0950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='area_code',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='contact_1',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='contact_2',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='english_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='industry_category',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='url',
        ),
        migrations.AddField(
            model_name='address',
            name='address_2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='address_3',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='contact_person_1',
            field=models.CharField(default='test', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='contact_person_2',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='country',
            field=models.CharField(default='india', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='currency',
            field=models.CharField(default='INR', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='district_in_hk',
            field=models.CharField(default='test', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='industry_type',
            field=models.CharField(default='test', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='prefix',
            field=models.CharField(default='+91', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='source',
            field=models.CharField(default='test', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='status',
            field=models.CharField(default='draft', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='address_line',
            field=models.CharField(default='test address', max_length=500, verbose_name='Main address'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='company_english_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='delivery_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='landline',
            field=models.CharField(default='1231324', max_length=128, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Only Numbers are allowed.')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=128, null=True, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Only Numbers are allowed.')]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number_2',
            field=models.CharField(blank=True, max_length=128, null=True, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Only Numbers are allowed.')]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='sale_person',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='authentication.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='amount_trigger',
            field=models.CharField(choices=[('Equals to', 'Equals to'), ('Less than', 'Less than'), ('More than and equals to', 'More than and equals to'), (None, '-------'), ('Less than and equals to', 'Less than and equals to'), ('More than', 'More than')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='quantity_trigger',
            field=models.CharField(choices=[('Equals to', 'Equals to'), ('Less than', 'Less than'), ('More than and equals to', 'More than and equals to'), (None, '-------'), ('Less than and equals to', 'Less than and equals to'), ('More than', 'More than')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'COD'), ('Bank Transfer/Cheque', 'Bank Transfer/Cheque')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('Partially Delivered', 'Partially Delivered'), ('Delivered', 'Delivered'), ('Pending', 'Pending')], default='Pending', max_length=128),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='type',
            field=models.CharField(choices=[('Quotation', 'Quotation'), ('Purchase', 'Purchase')], max_length=128),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='prefix',
            field=models.CharField(choices=[('+52', '+52 (Mexico)'), ('+61', '+61 (Australia)'), ('+33', '+33 (France)'), ('+64', '+64 (New Zealand)'), ('+971', '+971 (UAE)'), ('+55', '+55 (Brazil)'), ('+65', '+65 (Singapore)'), ('+1', '+1 (Canada)'), ('+82', '+82 (South Korea)'), ('+34', '+34 (Spain)'), ('+81', '+81 (Japan)'), ('+7', '+7 (Russia)'), ('+49', '+49 (Germany)'), ('+966', '+966 (Saudi Arabia)'), ('+86', '+86 (China)'), ('+91', '+91 (India)'), ('+44', '+44 (UK)'), ('+39', '+39 (Italy)'), ('+1', '+1 (US)'), ('+20', '+20 (Egypt)')], max_length=250),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='discount_type',
            field=models.CharField(choices=[('Rate(%)', 'Rate(%)'), (None, '-------'), ('Fixed Amount', 'Fixed Amount')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='status',
            field=models.CharField(choices=[('Valid', 'Valid'), ('Paused', 'Paused'), ('Ended', 'Ended'), ('Ready to start', 'Ready to start'), ('Cancelled', 'Cancelled')], max_length=128),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='voucher_type',
            field=models.CharField(choices=[('Manual Discount', 'Manual Discount'), ('Product Combo', 'Product Combo'), ('Free Gift', 'Free Gift'), ('Discount Voucher', 'Discount Voucher')], max_length=128),
        ),
        migrations.CreateModel(
            name='Customer_Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to=apps.home.model.customer.get_file_path)),
                ('file_name', models.CharField(blank=True, max_length=500, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.customer')),
            ],
        ),
    ]
