# Generated by Django 3.2.16 on 2024-04-17 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_auto_20240417_0654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountvoucher',
            name='amount_trigger',
            field=models.CharField(choices=[('Less than', 'Less than'), ('Equals to', 'Equals to'), ('Less than and equals to', 'Less than and equals to'), ('More than', 'More than'), (None, '-------'), ('More than and equals to', 'More than and equals to')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='quantity_trigger',
            field=models.CharField(choices=[('Less than', 'Less than'), ('Equals to', 'Equals to'), ('Less than and equals to', 'Less than and equals to'), ('More than', 'More than'), (None, '-------'), ('More than and equals to', 'More than and equals to')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Delivered', 'Delivered'), ('Partially Delivered', 'Partially Delivered')], default='Pending', max_length=128),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='prefix',
            field=models.CharField(choices=[('+44', '+44 (UK)'), ('+7', '+7 (Russia)'), ('+1', '+1 (Canada)'), ('+966', '+966 (Saudi Arabia)'), ('+86', '+86 (China)'), ('+52', '+52 (Mexico)'), ('+64', '+64 (New Zealand)'), ('+20', '+20 (Egypt)'), ('+82', '+82 (South Korea)'), ('+39', '+39 (Italy)'), ('+91', '+91 (India)'), ('+61', '+61 (Australia)'), ('+55', '+55 (Brazil)'), ('+1', '+1 (US)'), ('+971', '+971 (UAE)'), ('+34', '+34 (Spain)'), ('+33', '+33 (France)'), ('+81', '+81 (Japan)'), ('+49', '+49 (Germany)'), ('+65', '+65 (Singapore)')], max_length=250),
        ),
        migrations.AlterField(
            model_name='systemparameters',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='discount_type',
            field=models.CharField(choices=[(None, '-------'), ('Rate(%)', 'Rate(%)'), ('Fixed Amount', 'Fixed Amount')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='status',
            field=models.CharField(choices=[('Paused', 'Paused'), ('Cancelled', 'Cancelled'), ('Ended', 'Ended'), ('Ready to start', 'Ready to start'), ('Valid', 'Valid')], max_length=128),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='voucher_type',
            field=models.CharField(choices=[('Free Gift', 'Free Gift'), ('Discount Voucher', 'Discount Voucher'), ('Manual Discount', 'Manual Discount'), ('Product Combo', 'Product Combo')], max_length=128),
        ),
    ]
