# Generated by Django 3.2.16 on 2024-04-17 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_auto_20240417_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='english_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='name',
            field=models.CharField(default='test', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='amount_trigger',
            field=models.CharField(choices=[('Less than and equals to', 'Less than and equals to'), ('Less than', 'Less than'), ('More than and equals to', 'More than and equals to'), ('Equals to', 'Equals to'), (None, '-------'), ('More than', 'More than')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='quantity_trigger',
            field=models.CharField(choices=[('Less than and equals to', 'Less than and equals to'), ('Less than', 'Less than'), ('More than and equals to', 'More than and equals to'), ('Equals to', 'Equals to'), (None, '-------'), ('More than', 'More than')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('Partially Delivered', 'Partially Delivered'), ('Delivered', 'Delivered'), ('Pending', 'Pending')], default='Pending', max_length=128),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='prefix',
            field=models.CharField(choices=[('+44', '+44 (UK)'), ('+1', '+1 (US)'), ('+91', '+91 (India)'), ('+86', '+86 (China)'), ('+20', '+20 (Egypt)'), ('+7', '+7 (Russia)'), ('+966', '+966 (Saudi Arabia)'), ('+971', '+971 (UAE)'), ('+55', '+55 (Brazil)'), ('+33', '+33 (France)'), ('+81', '+81 (Japan)'), ('+52', '+52 (Mexico)'), ('+34', '+34 (Spain)'), ('+82', '+82 (South Korea)'), ('+39', '+39 (Italy)'), ('+61', '+61 (Australia)'), ('+1', '+1 (Canada)'), ('+64', '+64 (New Zealand)'), ('+49', '+49 (Germany)'), ('+65', '+65 (Singapore)')], max_length=250),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='discount_type',
            field=models.CharField(choices=[('Rate(%)', 'Rate(%)'), ('Fixed Amount', 'Fixed Amount'), (None, '-------')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='status',
            field=models.CharField(choices=[('Ended', 'Ended'), ('Valid', 'Valid'), ('Cancelled', 'Cancelled'), ('Ready to start', 'Ready to start'), ('Paused', 'Paused')], max_length=128),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='voucher_type',
            field=models.CharField(choices=[('Manual Discount', 'Manual Discount'), ('Free Gift', 'Free Gift'), ('Product Combo', 'Product Combo'), ('Discount Voucher', 'Discount Voucher')], max_length=128),
        ),
    ]
