# Generated by Django 3.2.16 on 2024-04-18 05:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0036_auto_20240417_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='authentication.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='amount_trigger',
            field=models.CharField(choices=[('More than', 'More than'), ('Less than and equals to', 'Less than and equals to'), ('More than and equals to', 'More than and equals to'), (None, '-------'), ('Less than', 'Less than'), ('Equals to', 'Equals to')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='quantity_trigger',
            field=models.CharField(choices=[('More than', 'More than'), ('Less than and equals to', 'Less than and equals to'), ('More than and equals to', 'More than and equals to'), (None, '-------'), ('Less than', 'Less than'), ('Equals to', 'Equals to')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Partially Delivered', 'Partially Delivered'), ('Pending', 'Pending')], default='Pending', max_length=128),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='type',
            field=models.CharField(choices=[('Purchase', 'Purchase'), ('Quotation', 'Quotation')], max_length=128),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='prefix',
            field=models.CharField(choices=[('+61', '+61 (Australia)'), ('+64', '+64 (New Zealand)'), ('+7', '+7 (Russia)'), ('+65', '+65 (Singapore)'), ('+971', '+971 (UAE)'), ('+91', '+91 (India)'), ('+39', '+39 (Italy)'), ('+82', '+82 (South Korea)'), ('+20', '+20 (Egypt)'), ('+966', '+966 (Saudi Arabia)'), ('+33', '+33 (France)'), ('+86', '+86 (China)'), ('+52', '+52 (Mexico)'), ('+81', '+81 (Japan)'), ('+1', '+1 (Canada)'), ('+1', '+1 (US)'), ('+55', '+55 (Brazil)'), ('+44', '+44 (UK)'), ('+34', '+34 (Spain)'), ('+49', '+49 (Germany)')], max_length=250),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='status',
            field=models.CharField(choices=[('Valid', 'Valid'), ('Ended', 'Ended'), ('Paused', 'Paused'), ('Ready to start', 'Ready to start'), ('Cancelled', 'Cancelled')], max_length=128),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='voucher_type',
            field=models.CharField(choices=[('Discount Voucher', 'Discount Voucher'), ('Free Gift', 'Free Gift'), ('Product Combo', 'Product Combo'), ('Manual Discount', 'Manual Discount')], max_length=128),
        ),
    ]
