# Generated by Django 3.2.16 on 2024-04-18 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_auto_20240418_0551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('potential_customer', 'Potential Customer'), ('converted_customer', 'Converted Customer'), ('paid_customer', 'Paid Customer'), ('inactive_customer', 'Inactive Customer')], max_length=128),
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='amount_trigger',
            field=models.CharField(choices=[('Equals to', 'Equals to'), ('Less than and equals to', 'Less than and equals to'), (None, '-------'), ('More than', 'More than'), ('More than and equals to', 'More than and equals to'), ('Less than', 'Less than')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='quantity_trigger',
            field=models.CharField(choices=[('Equals to', 'Equals to'), ('Less than and equals to', 'Less than and equals to'), (None, '-------'), ('More than', 'More than'), ('More than and equals to', 'More than and equals to'), ('Less than', 'Less than')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('Partially Delivered', 'Partially Delivered'), ('Delivered', 'Delivered'), ('Pending', 'Pending')], default='Pending', max_length=128),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='prefix',
            field=models.CharField(choices=[('+65', '+65 (Singapore)'), ('+1', '+1 (Canada)'), ('+39', '+39 (Italy)'), ('+52', '+52 (Mexico)'), ('+33', '+33 (France)'), ('+20', '+20 (Egypt)'), ('+81', '+81 (Japan)'), ('+86', '+86 (China)'), ('+7', '+7 (Russia)'), ('+91', '+91 (India)'), ('+44', '+44 (UK)'), ('+966', '+966 (Saudi Arabia)'), ('+1', '+1 (US)'), ('+55', '+55 (Brazil)'), ('+64', '+64 (New Zealand)'), ('+34', '+34 (Spain)'), ('+49', '+49 (Germany)'), ('+61', '+61 (Australia)'), ('+971', '+971 (UAE)'), ('+82', '+82 (South Korea)')], max_length=250),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='discount_type',
            field=models.CharField(choices=[('Rate(%)', 'Rate(%)'), (None, '-------'), ('Fixed Amount', 'Fixed Amount')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='status',
            field=models.CharField(choices=[('Ready to start', 'Ready to start'), ('Paused', 'Paused'), ('Ended', 'Ended'), ('Valid', 'Valid'), ('Cancelled', 'Cancelled')], max_length=128),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='voucher_type',
            field=models.CharField(choices=[('Free Gift', 'Free Gift'), ('Manual Discount', 'Manual Discount'), ('Product Combo', 'Product Combo'), ('Discount Voucher', 'Discount Voucher')], max_length=128),
        ),
    ]
