# Generated by Django 3.2.16 on 2024-04-23 10:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_auto_20240418_0608'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='accumlated_sales',
            field=models.CharField(blank=True, max_length=500, null=True, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Only Numbers are allowed.')]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('potential customer', 'Potential Customer'), ('converted customer', 'Converted Customer'), ('paid customer', 'Paid Customer'), ('inactive customer', 'Inactive Customer')], max_length=128),
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='amount_trigger',
            field=models.CharField(choices=[('More than', 'More than'), ('Equals to', 'Equals to'), ('Less than and equals to', 'Less than and equals to'), ('More than and equals to', 'More than and equals to'), ('Less than', 'Less than'), (None, '-------')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='quantity_trigger',
            field=models.CharField(choices=[('More than', 'More than'), ('Equals to', 'Equals to'), ('Less than and equals to', 'Less than and equals to'), ('More than and equals to', 'More than and equals to'), ('Less than', 'Less than'), (None, '-------')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'COD'), ('Bank Transfer/Cheque', 'Bank Transfer/Cheque')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='prefix',
            field=models.CharField(choices=[('+49', '+49 (Germany)'), ('+81', '+81 (Japan)'), ('+91', '+91 (India)'), ('+64', '+64 (New Zealand)'), ('+33', '+33 (France)'), ('+34', '+34 (Spain)'), ('+1', '+1 (Canada)'), ('+20', '+20 (Egypt)'), ('+55', '+55 (Brazil)'), ('+1', '+1 (US)'), ('+971', '+971 (UAE)'), ('+86', '+86 (China)'), ('+39', '+39 (Italy)'), ('+44', '+44 (UK)'), ('+52', '+52 (Mexico)'), ('+61', '+61 (Australia)'), ('+65', '+65 (Singapore)'), ('+7', '+7 (Russia)'), ('+82', '+82 (South Korea)'), ('+966', '+966 (Saudi Arabia)')], max_length=250),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='discount_type',
            field=models.CharField(choices=[('Rate(%)', 'Rate(%)'), ('Fixed Amount', 'Fixed Amount'), (None, '-------')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='status',
            field=models.CharField(choices=[('Valid', 'Valid'), ('Ready to start', 'Ready to start'), ('Ended', 'Ended'), ('Paused', 'Paused'), ('Cancelled', 'Cancelled')], max_length=128),
        ),
    ]
