# Generated by Django 3.2.16 on 2024-04-23 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0040_auto_20240423_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='sale_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='amount_trigger',
            field=models.CharField(choices=[('Equals to', 'Equals to'), ('More than and equals to', 'More than and equals to'), (None, '-------'), ('More than', 'More than'), ('Less than', 'Less than'), ('Less than and equals to', 'Less than and equals to')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='quantity_trigger',
            field=models.CharField(choices=[('Equals to', 'Equals to'), ('More than and equals to', 'More than and equals to'), (None, '-------'), ('More than', 'More than'), ('Less than', 'Less than'), ('Less than and equals to', 'Less than and equals to')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='prefix',
            field=models.CharField(choices=[('+966', '+966 (Saudi Arabia)'), ('+55', '+55 (Brazil)'), ('+34', '+34 (Spain)'), ('+7', '+7 (Russia)'), ('+49', '+49 (Germany)'), ('+61', '+61 (Australia)'), ('+1', '+1 (US)'), ('+33', '+33 (France)'), ('+971', '+971 (UAE)'), ('+91', '+91 (India)'), ('+39', '+39 (Italy)'), ('+82', '+82 (South Korea)'), ('+52', '+52 (Mexico)'), ('+64', '+64 (New Zealand)'), ('+44', '+44 (UK)'), ('+20', '+20 (Egypt)'), ('+65', '+65 (Singapore)'), ('+86', '+86 (China)'), ('+1', '+1 (Canada)'), ('+81', '+81 (Japan)')], max_length=250),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='discount_type',
            field=models.CharField(choices=[('Fixed Amount', 'Fixed Amount'), ('Rate(%)', 'Rate(%)'), (None, '-------')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='status',
            field=models.CharField(choices=[('Ended', 'Ended'), ('Ready to start', 'Ready to start'), ('Paused', 'Paused'), ('Cancelled', 'Cancelled'), ('Valid', 'Valid')], max_length=128),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='voucher_type',
            field=models.CharField(choices=[('Free Gift', 'Free Gift'), ('Manual Discount', 'Manual Discount'), ('Discount Voucher', 'Discount Voucher'), ('Product Combo', 'Product Combo')], max_length=128),
        ),
    ]
