# Generated by Django 3.2.16 on 2024-04-23 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0041_auto_20240423_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='amount_trigger',
            field=models.CharField(choices=[('More than and equals to', 'More than and equals to'), ('Less than and equals to', 'Less than and equals to'), ('Less than', 'Less than'), (None, '-------'), ('Equals to', 'Equals to'), ('More than', 'More than')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='quantity_trigger',
            field=models.CharField(choices=[('More than and equals to', 'More than and equals to'), ('Less than and equals to', 'Less than and equals to'), ('Less than', 'Less than'), (None, '-------'), ('Equals to', 'Equals to'), ('More than', 'More than')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='payment_method',
            field=models.CharField(choices=[('Bank Transfer/Cheque', 'Bank Transfer/Cheque'), ('COD', 'COD')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='prefix',
            field=models.CharField(choices=[('+91', '+91 (India)'), ('+55', '+55 (Brazil)'), ('+49', '+49 (Germany)'), ('+64', '+64 (New Zealand)'), ('+81', '+81 (Japan)'), ('+7', '+7 (Russia)'), ('+20', '+20 (Egypt)'), ('+44', '+44 (UK)'), ('+1', '+1 (Canada)'), ('+86', '+86 (China)'), ('+39', '+39 (Italy)'), ('+52', '+52 (Mexico)'), ('+971', '+971 (UAE)'), ('+61', '+61 (Australia)'), ('+34', '+34 (Spain)'), ('+65', '+65 (Singapore)'), ('+33', '+33 (France)'), ('+1', '+1 (US)'), ('+966', '+966 (Saudi Arabia)'), ('+82', '+82 (South Korea)')], max_length=250),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='discount_type',
            field=models.CharField(choices=[('Fixed Amount', 'Fixed Amount'), (None, '-------'), ('Rate(%)', 'Rate(%)')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='status',
            field=models.CharField(choices=[('Paused', 'Paused'), ('Valid', 'Valid'), ('Ended', 'Ended'), ('Ready to start', 'Ready to start'), ('Cancelled', 'Cancelled')], max_length=128),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='voucher_type',
            field=models.CharField(choices=[('Product Combo', 'Product Combo'), ('Free Gift', 'Free Gift'), ('Discount Voucher', 'Discount Voucher'), ('Manual Discount', 'Manual Discount')], max_length=128),
        ),
    ]
