# Generated by Django 3.2.16 on 2024-04-24 09:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_auto_20240423_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='landline',
            field=models.CharField(blank=True, max_length=128, null=True, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Only Numbers are allowed.')]),
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='amount_trigger',
            field=models.CharField(choices=[(None, '-------'), ('More than and equals to', 'More than and equals to'), ('Equals to', 'Equals to'), ('Less than', 'Less than'), ('Less than and equals to', 'Less than and equals to'), ('More than', 'More than')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='quantity_trigger',
            field=models.CharField(choices=[(None, '-------'), ('More than and equals to', 'More than and equals to'), ('Equals to', 'Equals to'), ('Less than', 'Less than'), ('Less than and equals to', 'Less than and equals to'), ('More than', 'More than')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'COD'), ('Bank Transfer/Cheque', 'Bank Transfer/Cheque')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Partially Delivered', 'Partially Delivered'), ('Pending', 'Pending')], default='Pending', max_length=128),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='type',
            field=models.CharField(choices=[('Purchase', 'Purchase'), ('Quotation', 'Quotation')], max_length=128),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='prefix',
            field=models.CharField(choices=[('+52', '+52 (Mexico)'), ('+39', '+39 (Italy)'), ('+65', '+65 (Singapore)'), ('+86', '+86 (China)'), ('+971', '+971 (UAE)'), ('+61', '+61 (Australia)'), ('+7', '+7 (Russia)'), ('+55', '+55 (Brazil)'), ('+20', '+20 (Egypt)'), ('+64', '+64 (New Zealand)'), ('+82', '+82 (South Korea)'), ('+1', '+1 (US)'), ('+966', '+966 (Saudi Arabia)'), ('+1', '+1 (Canada)'), ('+81', '+81 (Japan)'), ('+34', '+34 (Spain)'), ('+44', '+44 (UK)'), ('+49', '+49 (Germany)'), ('+33', '+33 (France)'), ('+91', '+91 (India)')], max_length=250),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='discount_type',
            field=models.CharField(choices=[(None, '-------'), ('Rate(%)', 'Rate(%)'), ('Fixed Amount', 'Fixed Amount')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='status',
            field=models.CharField(choices=[('Cancelled', 'Cancelled'), ('Ended', 'Ended'), ('Valid', 'Valid'), ('Paused', 'Paused'), ('Ready to start', 'Ready to start')], max_length=128),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='voucher_type',
            field=models.CharField(choices=[('Free Gift', 'Free Gift'), ('Product Combo', 'Product Combo'), ('Discount Voucher', 'Discount Voucher'), ('Manual Discount', 'Manual Discount')], max_length=128),
        ),
    ]
