# Generated by Django 3.2.16 on 2024-04-29 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0043_auto_20240424_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountvoucher',
            name='amount_trigger',
            field=models.CharField(choices=[('Less than', 'Less than'), ('More than', 'More than'), (None, '-------'), ('Less than and equals to', 'Less than and equals to'), ('More than and equals to', 'More than and equals to'), ('Equals to', 'Equals to')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='quantity_trigger',
            field=models.CharField(choices=[('Less than', 'Less than'), ('More than', 'More than'), (None, '-------'), ('Less than and equals to', 'Less than and equals to'), ('More than and equals to', 'More than and equals to'), ('Equals to', 'Equals to')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='type',
            field=models.CharField(choices=[('Quotation', 'Quotation'), ('Purchase', 'Purchase')], max_length=128),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='prefix',
            field=models.CharField(choices=[('+65', '+65 (Singapore)'), ('+91', '+91 (India)'), ('+33', '+33 (France)'), ('+39', '+39 (Italy)'), ('+52', '+52 (Mexico)'), ('+86', '+86 (China)'), ('+64', '+64 (New Zealand)'), ('+34', '+34 (Spain)'), ('+971', '+971 (UAE)'), ('+81', '+81 (Japan)'), ('+44', '+44 (UK)'), ('+20', '+20 (Egypt)'), ('+1', '+1 (Canada)'), ('+82', '+82 (South Korea)'), ('+7', '+7 (Russia)'), ('+1', '+1 (US)'), ('+55', '+55 (Brazil)'), ('+61', '+61 (Australia)'), ('+49', '+49 (Germany)'), ('+966', '+966 (Saudi Arabia)')], max_length=250),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='discount_type',
            field=models.CharField(choices=[('Fixed Amount', 'Fixed Amount'), (None, '-------'), ('Rate(%)', 'Rate(%)')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='status',
            field=models.CharField(choices=[('Ready to start', 'Ready to start'), ('Paused', 'Paused'), ('Ended', 'Ended'), ('Cancelled', 'Cancelled'), ('Valid', 'Valid')], max_length=128),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='voucher_type',
            field=models.CharField(choices=[('Product Combo', 'Product Combo'), ('Manual Discount', 'Manual Discount'), ('Free Gift', 'Free Gift'), ('Discount Voucher', 'Discount Voucher')], max_length=128),
        ),
        migrations.CreateModel(
            name='SystemParametersForId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('value', models.TextField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.customer')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
