# Generated by Django 3.2.16 on 2024-04-29 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0044_auto_20240429_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountvoucher',
            name='amount_trigger',
            field=models.CharField(choices=[('More than and equals to', 'More than and equals to'), ('Less than', 'Less than'), (None, '-------'), ('More than', 'More than'), ('Less than and equals to', 'Less than and equals to'), ('Equals to', 'Equals to')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='quantity_trigger',
            field=models.CharField(choices=[('More than and equals to', 'More than and equals to'), ('Less than', 'Less than'), (None, '-------'), ('More than', 'More than'), ('Less than and equals to', 'Less than and equals to'), ('Equals to', 'Equals to')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='payment_method',
            field=models.CharField(choices=[('Bank Transfer/Cheque', 'Bank Transfer/Cheque'), ('COD', 'COD')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Pending', 'Pending'), ('Partially Delivered', 'Partially Delivered')], default='Pending', max_length=128),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='prefix',
            field=models.CharField(choices=[('+20', '+20 (Egypt)'), ('+86', '+86 (China)'), ('+65', '+65 (Singapore)'), ('+7', '+7 (Russia)'), ('+55', '+55 (Brazil)'), ('+971', '+971 (UAE)'), ('+1', '+1 (Canada)'), ('+1', '+1 (US)'), ('+39', '+39 (Italy)'), ('+34', '+34 (Spain)'), ('+82', '+82 (South Korea)'), ('+966', '+966 (Saudi Arabia)'), ('+61', '+61 (Australia)'), ('+44', '+44 (UK)'), ('+33', '+33 (France)'), ('+52', '+52 (Mexico)'), ('+81', '+81 (Japan)'), ('+91', '+91 (India)'), ('+49', '+49 (Germany)'), ('+64', '+64 (New Zealand)')], max_length=250),
        ),
        migrations.AlterField(
            model_name='systemparametersforid',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.category'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='discount_type',
            field=models.CharField(choices=[('Rate(%)', 'Rate(%)'), ('Fixed Amount', 'Fixed Amount'), (None, '-------')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='status',
            field=models.CharField(choices=[('Cancelled', 'Cancelled'), ('Ended', 'Ended'), ('Paused', 'Paused'), ('Valid', 'Valid'), ('Ready to start', 'Ready to start')], max_length=128),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='voucher_type',
            field=models.CharField(choices=[('Discount Voucher', 'Discount Voucher'), ('Free Gift', 'Free Gift'), ('Product Combo', 'Product Combo'), ('Manual Discount', 'Manual Discount')], max_length=128),
        ),
    ]
