# Generated by Django 3.2.16 on 2024-05-01 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0047_auto_20240430_0851'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_id',
            new_name='product_no',
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='amount_trigger',
            field=models.CharField(choices=[('Less than and equals to', 'Less than and equals to'), ('Less than', 'Less than'), ('More than', 'More than'), ('Equals to', 'Equals to'), (None, '-------'), ('More than and equals to', 'More than and equals to')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='quantity_trigger',
            field=models.CharField(choices=[('Less than and equals to', 'Less than and equals to'), ('Less than', 'Less than'), ('More than', 'More than'), ('Equals to', 'Equals to'), (None, '-------'), ('More than and equals to', 'More than and equals to')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Partially Delivered', 'Partially Delivered'), ('Delivered', 'Delivered')], default='Pending', max_length=128),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='type',
            field=models.CharField(choices=[('Quotation', 'Quotation'), ('Purchase', 'Purchase')], max_length=128),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='prefix',
            field=models.CharField(choices=[('+55', '+55 (Brazil)'), ('+52', '+52 (Mexico)'), ('+971', '+971 (UAE)'), ('+33', '+33 (France)'), ('+86', '+86 (China)'), ('+1', '+1 (Canada)'), ('+1', '+1 (US)'), ('+44', '+44 (UK)'), ('+34', '+34 (Spain)'), ('+61', '+61 (Australia)'), ('+82', '+82 (South Korea)'), ('+39', '+39 (Italy)'), ('+7', '+7 (Russia)'), ('+49', '+49 (Germany)'), ('+20', '+20 (Egypt)'), ('+91', '+91 (India)'), ('+65', '+65 (Singapore)'), ('+81', '+81 (Japan)'), ('+966', '+966 (Saudi Arabia)'), ('+64', '+64 (New Zealand)')], max_length=250),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='discount_type',
            field=models.CharField(choices=[('Fixed Amount', 'Fixed Amount'), (None, '-------'), ('Rate(%)', 'Rate(%)')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='status',
            field=models.CharField(choices=[('Ready to start', 'Ready to start'), ('Ended', 'Ended'), ('Paused', 'Paused'), ('Cancelled', 'Cancelled'), ('Valid', 'Valid')], max_length=128),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='voucher_type',
            field=models.CharField(choices=[('Discount Voucher', 'Discount Voucher'), ('Product Combo', 'Product Combo'), ('Manual Discount', 'Manual Discount'), ('Free Gift', 'Free Gift')], max_length=128),
        ),
    ]
