# Generated by Django 3.2.16 on 2024-05-01 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0048_auto_20240501_0619'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_no',
            new_name='product_id',
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='amount_trigger',
            field=models.CharField(choices=[('More than and equals to', 'More than and equals to'), ('More than', 'More than'), ('Less than', 'Less than'), ('Less than and equals to', 'Less than and equals to'), (None, '-------'), ('Equals to', 'Equals to')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='quantity_trigger',
            field=models.CharField(choices=[('More than and equals to', 'More than and equals to'), ('More than', 'More than'), ('Less than', 'Less than'), ('Less than and equals to', 'Less than and equals to'), (None, '-------'), ('Equals to', 'Equals to')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='payment_method',
            field=models.CharField(choices=[('Bank Transfer/Cheque', 'Bank Transfer/Cheque'), ('COD', 'COD')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('Partially Delivered', 'Partially Delivered'), ('Delivered', 'Delivered'), ('Pending', 'Pending')], default='Pending', max_length=128),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='prefix',
            field=models.CharField(choices=[('+61', '+61 (Australia)'), ('+65', '+65 (Singapore)'), ('+966', '+966 (Saudi Arabia)'), ('+86', '+86 (China)'), ('+34', '+34 (Spain)'), ('+44', '+44 (UK)'), ('+39', '+39 (Italy)'), ('+82', '+82 (South Korea)'), ('+971', '+971 (UAE)'), ('+52', '+52 (Mexico)'), ('+7', '+7 (Russia)'), ('+20', '+20 (Egypt)'), ('+81', '+81 (Japan)'), ('+55', '+55 (Brazil)'), ('+64', '+64 (New Zealand)'), ('+91', '+91 (India)'), ('+1', '+1 (US)'), ('+49', '+49 (Germany)'), ('+1', '+1 (Canada)'), ('+33', '+33 (France)')], max_length=250),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='status',
            field=models.CharField(choices=[('Valid', 'Valid'), ('Ended', 'Ended'), ('Paused', 'Paused'), ('Ready to start', 'Ready to start'), ('Cancelled', 'Cancelled')], max_length=128),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='voucher_type',
            field=models.CharField(choices=[('Manual Discount', 'Manual Discount'), ('Discount Voucher', 'Discount Voucher'), ('Free Gift', 'Free Gift'), ('Product Combo', 'Product Combo')], max_length=128),
        ),
    ]
