# Generated by Django 3.2.16 on 2024-05-01 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0049_auto_20240501_0621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountvoucher',
            name='amount_trigger',
            field=models.CharField(choices=[('Equals to', 'Equals to'), ('More than and equals to', 'More than and equals to'), ('Less than', 'Less than'), (None, '-------'), ('More than', 'More than'), ('Less than and equals to', 'Less than and equals to')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='quantity_trigger',
            field=models.CharField(choices=[('Equals to', 'Equals to'), ('More than and equals to', 'More than and equals to'), ('Less than', 'Less than'), (None, '-------'), ('More than', 'More than'), ('Less than and equals to', 'Less than and equals to')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Partially Delivered', 'Partially Delivered'), ('Delivered', 'Delivered')], default='Pending', max_length=128),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='prefix',
            field=models.CharField(choices=[('+971', '+971 (UAE)'), ('+86', '+86 (China)'), ('+55', '+55 (Brazil)'), ('+966', '+966 (Saudi Arabia)'), ('+33', '+33 (France)'), ('+44', '+44 (UK)'), ('+65', '+65 (Singapore)'), ('+61', '+61 (Australia)'), ('+34', '+34 (Spain)'), ('+49', '+49 (Germany)'), ('+52', '+52 (Mexico)'), ('+1', '+1 (US)'), ('+20', '+20 (Egypt)'), ('+64', '+64 (New Zealand)'), ('+39', '+39 (Italy)'), ('+7', '+7 (Russia)'), ('+91', '+91 (India)'), ('+1', '+1 (Canada)'), ('+81', '+81 (Japan)'), ('+82', '+82 (South Korea)')], max_length=250),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='discount_type',
            field=models.CharField(choices=[(None, '-------'), ('Fixed Amount', 'Fixed Amount'), ('Rate(%)', 'Rate(%)')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='status',
            field=models.CharField(choices=[('Ended', 'Ended'), ('Paused', 'Paused'), ('Valid', 'Valid'), ('Cancelled', 'Cancelled'), ('Ready to start', 'Ready to start')], max_length=128),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='voucher_type',
            field=models.CharField(choices=[('Discount Voucher', 'Discount Voucher'), ('Free Gift', 'Free Gift'), ('Manual Discount', 'Manual Discount'), ('Product Combo', 'Product Combo')], max_length=128),
        ),
    ]
