# Generated by Django 3.2.16 on 2024-05-01 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0050_auto_20240501_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountvoucher',
            name='amount_trigger',
            field=models.CharField(choices=[('More than and equals to', 'More than and equals to'), (None, '-------'), ('Less than and equals to', 'Less than and equals to'), ('More than', 'More than'), ('Equals to', 'Equals to'), ('Less than', 'Less than')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='quantity_trigger',
            field=models.CharField(choices=[('More than and equals to', 'More than and equals to'), (None, '-------'), ('Less than and equals to', 'Less than and equals to'), ('More than', 'More than'), ('Equals to', 'Equals to'), ('Less than', 'Less than')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_weight',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('Partially Delivered', 'Partially Delivered'), ('Pending', 'Pending'), ('Delivered', 'Delivered')], default='Pending', max_length=128),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='prefix',
            field=models.CharField(choices=[('+86', '+86 (China)'), ('+971', '+971 (UAE)'), ('+20', '+20 (Egypt)'), ('+55', '+55 (Brazil)'), ('+81', '+81 (Japan)'), ('+1', '+1 (Canada)'), ('+65', '+65 (Singapore)'), ('+91', '+91 (India)'), ('+82', '+82 (South Korea)'), ('+52', '+52 (Mexico)'), ('+7', '+7 (Russia)'), ('+966', '+966 (Saudi Arabia)'), ('+39', '+39 (Italy)'), ('+34', '+34 (Spain)'), ('+61', '+61 (Australia)'), ('+49', '+49 (Germany)'), ('+44', '+44 (UK)'), ('+64', '+64 (New Zealand)'), ('+33', '+33 (France)'), ('+1', '+1 (US)')], max_length=250),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='discount_type',
            field=models.CharField(choices=[('Rate(%)', 'Rate(%)'), (None, '-------'), ('Fixed Amount', 'Fixed Amount')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='status',
            field=models.CharField(choices=[('Ended', 'Ended'), ('Ready to start', 'Ready to start'), ('Valid', 'Valid'), ('Paused', 'Paused'), ('Cancelled', 'Cancelled')], max_length=128),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='voucher_type',
            field=models.CharField(choices=[('Product Combo', 'Product Combo'), ('Free Gift', 'Free Gift'), ('Discount Voucher', 'Discount Voucher'), ('Manual Discount', 'Manual Discount')], max_length=128),
        ),
    ]
