# Generated by Django 3.2.16 on 2024-05-01 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0051_auto_20240501_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountvoucher',
            name='amount_trigger',
            field=models.CharField(choices=[('Equals to', 'Equals to'), ('Less than', 'Less than'), (None, '-------'), ('More than', 'More than'), ('More than and equals to', 'More than and equals to'), ('Less than and equals to', 'Less than and equals to')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='quantity_trigger',
            field=models.CharField(choices=[('Equals to', 'Equals to'), ('Less than', 'Less than'), (None, '-------'), ('More than', 'More than'), ('More than and equals to', 'More than and equals to'), ('Less than and equals to', 'Less than and equals to')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Partially Delivered', 'Partially Delivered'), ('Delivered', 'Delivered')], default='Pending', max_length=128),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='prefix',
            field=models.CharField(choices=[('+7', '+7 (Russia)'), ('+966', '+966 (Saudi Arabia)'), ('+971', '+971 (UAE)'), ('+49', '+49 (Germany)'), ('+34', '+34 (Spain)'), ('+39', '+39 (Italy)'), ('+61', '+61 (Australia)'), ('+33', '+33 (France)'), ('+20', '+20 (Egypt)'), ('+65', '+65 (Singapore)'), ('+86', '+86 (China)'), ('+82', '+82 (South Korea)'), ('+44', '+44 (UK)'), ('+1', '+1 (Canada)'), ('+52', '+52 (Mexico)'), ('+1', '+1 (US)'), ('+64', '+64 (New Zealand)'), ('+91', '+91 (India)'), ('+55', '+55 (Brazil)'), ('+81', '+81 (Japan)')], max_length=250),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='discount_type',
            field=models.CharField(choices=[(None, '-------'), ('Fixed Amount', 'Fixed Amount'), ('Rate(%)', 'Rate(%)')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='status',
            field=models.CharField(choices=[('Paused', 'Paused'), ('Cancelled', 'Cancelled'), ('Ready to start', 'Ready to start'), ('Ended', 'Ended'), ('Valid', 'Valid')], max_length=128),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='voucher_type',
            field=models.CharField(choices=[('Manual Discount', 'Manual Discount'), ('Free Gift', 'Free Gift'), ('Product Combo', 'Product Combo'), ('Discount Voucher', 'Discount Voucher')], max_length=128),
        ),
    ]
