# Generated by Django 3.2.16 on 2024-05-02 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0052_auto_20240501_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total_cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='amount_trigger',
            field=models.CharField(choices=[('More than', 'More than'), ('More than and equals to', 'More than and equals to'), (None, '-------'), ('Less than and equals to', 'Less than and equals to'), ('Less than', 'Less than'), ('Equals to', 'Equals to')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='quantity_trigger',
            field=models.CharField(choices=[('More than', 'More than'), ('More than and equals to', 'More than and equals to'), (None, '-------'), ('Less than and equals to', 'Less than and equals to'), ('Less than', 'Less than'), ('Equals to', 'Equals to')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Partially Delivered', 'Partially Delivered'), ('Pending', 'Pending')], default='Pending', max_length=128),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='prefix',
            field=models.CharField(choices=[('+55', '+55 (Brazil)'), ('+1', '+1 (US)'), ('+966', '+966 (Saudi Arabia)'), ('+20', '+20 (Egypt)'), ('+39', '+39 (Italy)'), ('+91', '+91 (India)'), ('+1', '+1 (Canada)'), ('+82', '+82 (South Korea)'), ('+81', '+81 (Japan)'), ('+61', '+61 (Australia)'), ('+971', '+971 (UAE)'), ('+64', '+64 (New Zealand)'), ('+86', '+86 (China)'), ('+7', '+7 (Russia)'), ('+49', '+49 (Germany)'), ('+65', '+65 (Singapore)'), ('+34', '+34 (Spain)'), ('+33', '+33 (France)'), ('+44', '+44 (UK)'), ('+52', '+52 (Mexico)')], max_length=250),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='discount_type',
            field=models.CharField(choices=[(None, '-------'), ('Rate(%)', 'Rate(%)'), ('Fixed Amount', 'Fixed Amount')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='status',
            field=models.CharField(choices=[('Cancelled', 'Cancelled'), ('Ended', 'Ended'), ('Paused', 'Paused'), ('Valid', 'Valid'), ('Ready to start', 'Ready to start')], max_length=128),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='voucher_type',
            field=models.CharField(choices=[('Product Combo', 'Product Combo'), ('Discount Voucher', 'Discount Voucher'), ('Manual Discount', 'Manual Discount'), ('Free Gift', 'Free Gift')], max_length=128),
        ),
    ]
