# Generated by Django 3.2.16 on 2024-05-21 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0054_auto_20240506_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountvoucher',
            name='amount_trigger',
            field=models.CharField(choices=[('Equals to', 'Equals to'), ('Less than and equals to', 'Less than and equals to'), ('More than', 'More than'), ('Less than', 'Less than'), ('More than and equals to', 'More than and equals to'), (None, '-------')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='quantity_trigger',
            field=models.CharField(choices=[('Equals to', 'Equals to'), ('Less than and equals to', 'Less than and equals to'), ('More than', 'More than'), ('Less than', 'Less than'), ('More than and equals to', 'More than and equals to'), (None, '-------')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('Partially Delivered', 'Partially Delivered'), ('Pending', 'Pending'), ('Delivered', 'Delivered')], default='Pending', max_length=128),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='prefix',
            field=models.CharField(choices=[('+33', '+33 (France)'), ('+20', '+20 (Egypt)'), ('+1', '+1 (US)'), ('+966', '+966 (Saudi Arabia)'), ('+82', '+82 (South Korea)'), ('+39', '+39 (Italy)'), ('+971', '+971 (UAE)'), ('+34', '+34 (Spain)'), ('+49', '+49 (Germany)'), ('+55', '+55 (Brazil)'), ('+86', '+86 (China)'), ('+1', '+1 (Canada)'), ('+7', '+7 (Russia)'), ('+61', '+61 (Australia)'), ('+91', '+91 (India)'), ('+52', '+52 (Mexico)'), ('+44', '+44 (UK)'), ('+81', '+81 (Japan)'), ('+64', '+64 (New Zealand)'), ('+65', '+65 (Singapore)')], max_length=250),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='status',
            field=models.CharField(choices=[('Ended', 'Ended'), ('Paused', 'Paused'), ('Valid', 'Valid'), ('Ready to start', 'Ready to start'), ('Cancelled', 'Cancelled')], max_length=128),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='voucher_type',
            field=models.CharField(choices=[('Free Gift', 'Free Gift'), ('Discount Voucher', 'Discount Voucher'), ('Product Combo', 'Product Combo'), ('Manual Discount', 'Manual Discount')], max_length=128),
        ),
        migrations.CreateModel(
            name='ExceptionLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('error_type', models.CharField(blank=True, max_length=500, null=True)),
                ('error_msg', models.TextField(blank=True, null=True)),
                ('traceback', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
