# Generated by Django 3.2.16 on 2024-06-13 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0056_auto_20240603_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='address_2_chinese',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='address_3_chinese',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='address_line_chinese',
            field=models.CharField(default='test', max_length=500, verbose_name='Main address in chinese'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='contact_person_1_chinese',
            field=models.CharField(default='test', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='contact_person_2_chinese',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='company_english_name',
            field=models.CharField(default='test', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='amount_trigger',
            field=models.CharField(choices=[('Less than and equals to', 'Less than and equals to'), (None, '-------'), ('More than and equals to', 'More than and equals to'), ('Less than', 'Less than'), ('More than', 'More than'), ('Equals to', 'Equals to')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='quantity_trigger',
            field=models.CharField(choices=[('Less than and equals to', 'Less than and equals to'), (None, '-------'), ('More than and equals to', 'More than and equals to'), ('Less than', 'Less than'), ('More than', 'More than'), ('Equals to', 'Equals to')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='payment_method',
            field=models.CharField(choices=[('Bank Transfer/Cheque', 'Bank Transfer/Cheque'), ('COD', 'COD')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Partially Delivered', 'Partially Delivered'), ('Delivered', 'Delivered')], default='Pending', max_length=128),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='type',
            field=models.CharField(choices=[('Purchase', 'Purchase'), ('Quotation', 'Quotation')], max_length=128),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='prefix',
            field=models.CharField(choices=[('+64', '+64 (New Zealand)'), ('+91', '+91 (India)'), ('+65', '+65 (Singapore)'), ('+7', '+7 (Russia)'), ('+20', '+20 (Egypt)'), ('+39', '+39 (Italy)'), ('+44', '+44 (UK)'), ('+61', '+61 (Australia)'), ('+86', '+86 (China)'), ('+1', '+1 (US)'), ('+971', '+971 (UAE)'), ('+81', '+81 (Japan)'), ('+34', '+34 (Spain)'), ('+82', '+82 (South Korea)'), ('+49', '+49 (Germany)'), ('+966', '+966 (Saudi Arabia)'), ('+55', '+55 (Brazil)'), ('+1', '+1 (Canada)'), ('+52', '+52 (Mexico)'), ('+33', '+33 (France)')], max_length=250),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='discount_type',
            field=models.CharField(choices=[(None, '-------'), ('Fixed Amount', 'Fixed Amount'), ('Rate(%)', 'Rate(%)')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='status',
            field=models.CharField(choices=[('Ended', 'Ended'), ('Cancelled', 'Cancelled'), ('Paused', 'Paused'), ('Valid', 'Valid'), ('Ready to start', 'Ready to start')], max_length=128),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='voucher_type',
            field=models.CharField(choices=[('Product Combo', 'Product Combo'), ('Free Gift', 'Free Gift'), ('Discount Voucher', 'Discount Voucher'), ('Manual Discount', 'Manual Discount')], max_length=128),
        ),
    ]
