# Generated by Django 3.2.16 on 2024-06-17 04:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0057_auto_20240613_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(default=123456789, max_length=128, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Only Numbers are allowed.')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='amount_trigger',
            field=models.CharField(choices=[('Less than', 'Less than'), (None, '-------'), ('Equals to', 'Equals to'), ('More than', 'More than'), ('More than and equals to', 'More than and equals to'), ('Less than and equals to', 'Less than and equals to')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='quantity_trigger',
            field=models.CharField(choices=[('Less than', 'Less than'), (None, '-------'), ('Equals to', 'Equals to'), ('More than', 'More than'), ('More than and equals to', 'More than and equals to'), ('Less than and equals to', 'Less than and equals to')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('Partially Delivered', 'Partially Delivered'), ('Delivered', 'Delivered'), ('Pending', 'Pending')], default='Pending', max_length=128),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='type',
            field=models.CharField(choices=[('Quotation', 'Quotation'), ('Purchase', 'Purchase')], max_length=128),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='prefix',
            field=models.CharField(choices=[('+44', '+44 (UK)'), ('+1', '+1 (US)'), ('+82', '+82 (South Korea)'), ('+7', '+7 (Russia)'), ('+49', '+49 (Germany)'), ('+81', '+81 (Japan)'), ('+966', '+966 (Saudi Arabia)'), ('+1', '+1 (Canada)'), ('+64', '+64 (New Zealand)'), ('+52', '+52 (Mexico)'), ('+65', '+65 (Singapore)'), ('+34', '+34 (Spain)'), ('+91', '+91 (India)'), ('+20', '+20 (Egypt)'), ('+33', '+33 (France)'), ('+39', '+39 (Italy)'), ('+971', '+971 (UAE)'), ('+55', '+55 (Brazil)'), ('+86', '+86 (China)'), ('+61', '+61 (Australia)')], max_length=250),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='discount_type',
            field=models.CharField(choices=[('Fixed Amount', 'Fixed Amount'), (None, '-------'), ('Rate(%)', 'Rate(%)')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='status',
            field=models.CharField(choices=[('Ended', 'Ended'), ('Valid', 'Valid'), ('Cancelled', 'Cancelled'), ('Paused', 'Paused'), ('Ready to start', 'Ready to start')], max_length=128),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='voucher_type',
            field=models.CharField(choices=[('Discount Voucher', 'Discount Voucher'), ('Product Combo', 'Product Combo'), ('Manual Discount', 'Manual Discount'), ('Free Gift', 'Free Gift')], max_length=128),
        ),
    ]
