# Generated by Django 3.2.16 on 2024-07-02 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0058_auto_20240617_1020'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvenoryPurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('inventory_po_id', models.CharField(blank=True, max_length=500, null=True, unique=True)),
                ('total_purchase_cost', models.FloatField()),
                ('special_disocunt', models.FloatField(blank=True, null=True)),
                ('total_cost', models.FloatField()),
                ('status', models.CharField(choices=[('Draft', 'draft'), ('Pending Stock In', 'pending stock in'), ('Cancelled', 'cancelled'), ('Stocked In', 'stocked in')], max_length=100)),
                ('expected_arrival_date', models.DateTimeField(blank=True, null=True)),
                ('delivery_fee', models.FloatField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='actual_quantity',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='last_purchase_date',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='last_sales_date',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='safety_quantity',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='total_damaged_quantity',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='total_purchased_quantity',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='total_shipping_quantity',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='total_sold_quantity',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='total_stock_in_quantity',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='total_stock_out_quantity',
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='amount_trigger',
            field=models.CharField(choices=[(None, '-------'), ('Less than', 'Less than'), ('Equals to', 'Equals to'), ('More than', 'More than'), ('Less than and equals to', 'Less than and equals to'), ('More than and equals to', 'More than and equals to')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='quantity_trigger',
            field=models.CharField(choices=[(None, '-------'), ('Less than', 'Less than'), ('Equals to', 'Equals to'), ('More than', 'More than'), ('Less than and equals to', 'Less than and equals to'), ('More than and equals to', 'More than and equals to')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'COD'), ('Bank Transfer/Cheque', 'Bank Transfer/Cheque')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Delivered', 'Delivered'), ('Partially Delivered', 'Partially Delivered')], default='Pending', max_length=128),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='prefix',
            field=models.CharField(choices=[('+64', '+64 (New Zealand)'), ('+34', '+34 (Spain)'), ('+82', '+82 (South Korea)'), ('+7', '+7 (Russia)'), ('+55', '+55 (Brazil)'), ('+52', '+52 (Mexico)'), ('+86', '+86 (China)'), ('+39', '+39 (Italy)'), ('+91', '+91 (India)'), ('+44', '+44 (UK)'), ('+81', '+81 (Japan)'), ('+1', '+1 (Canada)'), ('+49', '+49 (Germany)'), ('+61', '+61 (Australia)'), ('+65', '+65 (Singapore)'), ('+971', '+971 (UAE)'), ('+20', '+20 (Egypt)'), ('+33', '+33 (France)'), ('+966', '+966 (Saudi Arabia)'), ('+1', '+1 (US)')], max_length=250),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='discount_type',
            field=models.CharField(choices=[(None, '-------'), ('Fixed Amount', 'Fixed Amount'), ('Rate(%)', 'Rate(%)')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='status',
            field=models.CharField(choices=[('Cancelled', 'Cancelled'), ('Paused', 'Paused'), ('Ended', 'Ended'), ('Valid', 'Valid'), ('Ready to start', 'Ready to start')], max_length=128),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='voucher_type',
            field=models.CharField(choices=[('Free Gift', 'Free Gift'), ('Manual Discount', 'Manual Discount'), ('Discount Voucher', 'Discount Voucher'), ('Product Combo', 'Product Combo')], max_length=128),
        ),
        migrations.CreateModel(
            name='StockMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('move_type', models.CharField(choices=[('Exchange', 'exchange'), ('Depreciation', 'depreciation'), ('Sample', 'sample'), ('Others', 'others')], max_length=100)),
                ('remark', models.CharField(blank=True, max_length=500, null=True)),
                ('quantity', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StockInOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('stockin_order_id', models.CharField(blank=True, max_length=500, null=True, unique=True)),
                ('depreciation', models.IntegerField(blank=True, null=True)),
                ('actual_stock_in', models.IntegerField(blank=True, null=True)),
                ('stock_in_remark', models.IntegerField(blank=True, null=True)),
                ('inventory_po', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.invenorypurchaseorder')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InventoryPurchaseOrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('item_name_chinese', models.CharField(max_length=200)),
                ('item_name_english', models.CharField(blank=True, max_length=200, null=True)),
                ('item_specification', models.CharField(blank=True, max_length=100, null=True)),
                ('item_currency', models.CharField(max_length=100)),
                ('supplier_name', models.CharField(max_length=200)),
                ('purchase_cost', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('subtotal', models.FloatField()),
                ('remark', models.CharField(blank=True, max_length=500, null=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.product')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.supplier')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='invenorypurchaseorder',
            name='inventory_purchase_items',
            field=models.ManyToManyField(to='home.InventoryPurchaseOrderItems'),
        ),
    ]
