# Generated by Django 3.2.16 on 2024-07-09 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0059_auto_20240702_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='invenorypurchaseorder',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='amount_trigger',
            field=models.CharField(choices=[('More than', 'More than'), (None, '-------'), ('Less than', 'Less than'), ('Less than and equals to', 'Less than and equals to'), ('More than and equals to', 'More than and equals to'), ('Equals to', 'Equals to')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='quantity_trigger',
            field=models.CharField(choices=[('More than', 'More than'), (None, '-------'), ('Less than', 'Less than'), ('Less than and equals to', 'Less than and equals to'), ('More than and equals to', 'More than and equals to'), ('Equals to', 'Equals to')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='payment_method',
            field=models.CharField(choices=[('Bank Transfer/Cheque', 'Bank Transfer/Cheque'), ('COD', 'COD')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='prefix',
            field=models.CharField(choices=[('+64', '+64 (New Zealand)'), ('+65', '+65 (Singapore)'), ('+1', '+1 (US)'), ('+81', '+81 (Japan)'), ('+82', '+82 (South Korea)'), ('+49', '+49 (Germany)'), ('+7', '+7 (Russia)'), ('+55', '+55 (Brazil)'), ('+34', '+34 (Spain)'), ('+966', '+966 (Saudi Arabia)'), ('+44', '+44 (UK)'), ('+971', '+971 (UAE)'), ('+20', '+20 (Egypt)'), ('+39', '+39 (Italy)'), ('+33', '+33 (France)'), ('+91', '+91 (India)'), ('+86', '+86 (China)'), ('+1', '+1 (Canada)'), ('+52', '+52 (Mexico)'), ('+61', '+61 (Australia)')], max_length=250),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='discount_type',
            field=models.CharField(choices=[('Fixed Amount', 'Fixed Amount'), (None, '-------'), ('Rate(%)', 'Rate(%)')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='status',
            field=models.CharField(choices=[('Ended', 'Ended'), ('Ready to start', 'Ready to start'), ('Paused', 'Paused'), ('Valid', 'Valid'), ('Cancelled', 'Cancelled')], max_length=128),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='voucher_type',
            field=models.CharField(choices=[('Manual Discount', 'Manual Discount'), ('Discount Voucher', 'Discount Voucher'), ('Product Combo', 'Product Combo'), ('Free Gift', 'Free Gift')], max_length=128),
        ),
    ]
