# Generated by Django 3.2.16 on 2024-07-10 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0060_auto_20240709_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='invenorypurchaseorder',
            name='total_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='amount_trigger',
            field=models.CharField(choices=[('Less than and equals to', 'Less than and equals to'), ('More than', 'More than'), ('More than and equals to', 'More than and equals to'), (None, '-------'), ('Less than', 'Less than'), ('Equals to', 'Equals to')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='quantity_trigger',
            field=models.CharField(choices=[('Less than and equals to', 'Less than and equals to'), ('More than', 'More than'), ('More than and equals to', 'More than and equals to'), (None, '-------'), ('Less than', 'Less than'), ('Equals to', 'Equals to')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='type',
            field=models.CharField(choices=[('Purchase', 'Purchase'), ('Quotation', 'Quotation')], max_length=128),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='prefix',
            field=models.CharField(choices=[('+91', '+91 (India)'), ('+34', '+34 (Spain)'), ('+64', '+64 (New Zealand)'), ('+49', '+49 (Germany)'), ('+61', '+61 (Australia)'), ('+65', '+65 (Singapore)'), ('+33', '+33 (France)'), ('+81', '+81 (Japan)'), ('+82', '+82 (South Korea)'), ('+52', '+52 (Mexico)'), ('+971', '+971 (UAE)'), ('+1', '+1 (US)'), ('+1', '+1 (Canada)'), ('+39', '+39 (Italy)'), ('+20', '+20 (Egypt)'), ('+44', '+44 (UK)'), ('+55', '+55 (Brazil)'), ('+7', '+7 (Russia)'), ('+86', '+86 (China)'), ('+966', '+966 (Saudi Arabia)')], max_length=250),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='discount_type',
            field=models.CharField(choices=[(None, '-------'), ('Rate(%)', 'Rate(%)'), ('Fixed Amount', 'Fixed Amount')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='status',
            field=models.CharField(choices=[('Cancelled', 'Cancelled'), ('Paused', 'Paused'), ('Ended', 'Ended'), ('Valid', 'Valid'), ('Ready to start', 'Ready to start')], max_length=128),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='voucher_type',
            field=models.CharField(choices=[('Product Combo', 'Product Combo'), ('Free Gift', 'Free Gift'), ('Manual Discount', 'Manual Discount'), ('Discount Voucher', 'Discount Voucher')], max_length=128),
        ),
    ]
