# Generated by Django 3.2.16 on 2024-07-11 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0061_auto_20240710_1810'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InvenoryPurchaseOrder',
            new_name='InventoryPurchaseOrder',
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='amount_trigger',
            field=models.CharField(choices=[('Less than and equals to', 'Less than and equals to'), ('Equals to', 'Equals to'), ('More than', 'More than'), (None, '-------'), ('Less than', 'Less than'), ('More than and equals to', 'More than and equals to')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='quantity_trigger',
            field=models.CharField(choices=[('Less than and equals to', 'Less than and equals to'), ('Equals to', 'Equals to'), ('More than', 'More than'), (None, '-------'), ('Less than', 'Less than'), ('More than and equals to', 'More than and equals to')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'COD'), ('Bank Transfer/Cheque', 'Bank Transfer/Cheque')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('Partially Delivered', 'Partially Delivered'), ('Delivered', 'Delivered'), ('Pending', 'Pending')], default='Pending', max_length=128),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='type',
            field=models.CharField(choices=[('Quotation', 'Quotation'), ('Purchase', 'Purchase')], max_length=128),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='prefix',
            field=models.CharField(choices=[('+1', '+1 (Canada)'), ('+52', '+52 (Mexico)'), ('+7', '+7 (Russia)'), ('+33', '+33 (France)'), ('+64', '+64 (New Zealand)'), ('+55', '+55 (Brazil)'), ('+1', '+1 (US)'), ('+91', '+91 (India)'), ('+86', '+86 (China)'), ('+39', '+39 (Italy)'), ('+44', '+44 (UK)'), ('+82', '+82 (South Korea)'), ('+65', '+65 (Singapore)'), ('+49', '+49 (Germany)'), ('+971', '+971 (UAE)'), ('+61', '+61 (Australia)'), ('+966', '+966 (Saudi Arabia)'), ('+81', '+81 (Japan)'), ('+34', '+34 (Spain)'), ('+20', '+20 (Egypt)')], max_length=250),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='discount_type',
            field=models.CharField(choices=[(None, '-------'), ('Fixed Amount', 'Fixed Amount'), ('Rate(%)', 'Rate(%)')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='status',
            field=models.CharField(choices=[('Valid', 'Valid'), ('Cancelled', 'Cancelled'), ('Paused', 'Paused'), ('Ready to start', 'Ready to start'), ('Ended', 'Ended')], max_length=128),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='voucher_type',
            field=models.CharField(choices=[('Discount Voucher', 'Discount Voucher'), ('Free Gift', 'Free Gift'), ('Product Combo', 'Product Combo'), ('Manual Discount', 'Manual Discount')], max_length=128),
        ),
    ]
