# Generated by Django 3.2.16 on 2024-07-26 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0063_auto_20240724_1754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorypurchaseorder',
            name='status',
        ),
        migrations.AddField(
            model_name='inventorypurchaseorderitems',
            name='status',
            field=models.CharField(choices=[('Draft', 'draft'), ('Pending Stock In', 'pending stock in'), ('Cancelled', 'cancelled'), ('Stocked In', 'stocked in')], default='Draft', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='amount_trigger',
            field=models.CharField(choices=[('Less than and equals to', 'Less than and equals to'), ('Equals to', 'Equals to'), ('Less than', 'Less than'), (None, '-------'), ('More than', 'More than'), ('More than and equals to', 'More than and equals to')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='quantity_trigger',
            field=models.CharField(choices=[('Less than and equals to', 'Less than and equals to'), ('Equals to', 'Equals to'), ('Less than', 'Less than'), (None, '-------'), ('More than', 'More than'), ('More than and equals to', 'More than and equals to')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='payment_method',
            field=models.CharField(choices=[('Bank Transfer/Cheque', 'Bank Transfer/Cheque'), ('COD', 'COD')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Delivered', 'Delivered'), ('Partially Delivered', 'Partially Delivered')], default='Pending', max_length=128),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='prefix',
            field=models.CharField(choices=[('+34', '+34 (Spain)'), ('+91', '+91 (India)'), ('+55', '+55 (Brazil)'), ('+1', '+1 (Canada)'), ('+65', '+65 (Singapore)'), ('+1', '+1 (US)'), ('+39', '+39 (Italy)'), ('+7', '+7 (Russia)'), ('+20', '+20 (Egypt)'), ('+966', '+966 (Saudi Arabia)'), ('+82', '+82 (South Korea)'), ('+44', '+44 (UK)'), ('+81', '+81 (Japan)'), ('+971', '+971 (UAE)'), ('+49', '+49 (Germany)'), ('+33', '+33 (France)'), ('+64', '+64 (New Zealand)'), ('+86', '+86 (China)'), ('+52', '+52 (Mexico)'), ('+61', '+61 (Australia)')], max_length=250),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='discount_type',
            field=models.CharField(choices=[('Fixed Amount', 'Fixed Amount'), ('Rate(%)', 'Rate(%)'), (None, '-------')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='status',
            field=models.CharField(choices=[('Ended', 'Ended'), ('Ready to start', 'Ready to start'), ('Paused', 'Paused'), ('Cancelled', 'Cancelled'), ('Valid', 'Valid')], max_length=128),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='voucher_type',
            field=models.CharField(choices=[('Product Combo', 'Product Combo'), ('Free Gift', 'Free Gift'), ('Discount Voucher', 'Discount Voucher'), ('Manual Discount', 'Manual Discount')], max_length=128),
        ),
    ]
