# Generated by Django 3.2.16 on 2024-07-26 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0064_auto_20240726_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountvoucher',
            name='amount_trigger',
            field=models.CharField(choices=[('Equals to', 'Equals to'), ('Less than', 'Less than'), ('Less than and equals to', 'Less than and equals to'), ('More than', 'More than'), (None, '-------'), ('More than and equals to', 'More than and equals to')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='quantity_trigger',
            field=models.CharField(choices=[('Equals to', 'Equals to'), ('Less than', 'Less than'), ('Less than and equals to', 'Less than and equals to'), ('More than', 'More than'), (None, '-------'), ('More than and equals to', 'More than and equals to')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'COD'), ('Bank Transfer/Cheque', 'Bank Transfer/Cheque')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('Partially Delivered', 'Partially Delivered'), ('Delivered', 'Delivered'), ('Pending', 'Pending')], default='Pending', max_length=128),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='prefix',
            field=models.CharField(choices=[('+49', '+49 (Germany)'), ('+81', '+81 (Japan)'), ('+82', '+82 (South Korea)'), ('+39', '+39 (Italy)'), ('+971', '+971 (UAE)'), ('+1', '+1 (US)'), ('+65', '+65 (Singapore)'), ('+33', '+33 (France)'), ('+34', '+34 (Spain)'), ('+86', '+86 (China)'), ('+1', '+1 (Canada)'), ('+91', '+91 (India)'), ('+61', '+61 (Australia)'), ('+7', '+7 (Russia)'), ('+52', '+52 (Mexico)'), ('+966', '+966 (Saudi Arabia)'), ('+64', '+64 (New Zealand)'), ('+20', '+20 (Egypt)'), ('+44', '+44 (UK)'), ('+55', '+55 (Brazil)')], max_length=250),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='discount_type',
            field=models.CharField(choices=[(None, '-------'), ('Fixed Amount', 'Fixed Amount'), ('Rate(%)', 'Rate(%)')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='status',
            field=models.CharField(choices=[('Ready to start', 'Ready to start'), ('Cancelled', 'Cancelled'), ('Ended', 'Ended'), ('Valid', 'Valid'), ('Paused', 'Paused')], max_length=128),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='voucher_type',
            field=models.CharField(choices=[('Product Combo', 'Product Combo'), ('Manual Discount', 'Manual Discount'), ('Free Gift', 'Free Gift'), ('Discount Voucher', 'Discount Voucher')], max_length=128),
        ),
    ]
