# Generated by Django 3.2.16 on 2024-07-29 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0065_auto_20240726_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockinorder',
            name='stock_move',
        ),
        migrations.AddField(
            model_name='stockmove',
            name='stockin_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home.stockinorder'),
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='amount_trigger',
            field=models.CharField(choices=[(None, '-------'), ('Equals to', 'Equals to'), ('Less than', 'Less than'), ('More than', 'More than'), ('Less than and equals to', 'Less than and equals to'), ('More than and equals to', 'More than and equals to')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='quantity_trigger',
            field=models.CharField(choices=[(None, '-------'), ('Equals to', 'Equals to'), ('Less than', 'Less than'), ('More than', 'More than'), ('Less than and equals to', 'Less than and equals to'), ('More than and equals to', 'More than and equals to')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Delivered', 'Delivered'), ('Partially Delivered', 'Partially Delivered')], default='Pending', max_length=128),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='prefix',
            field=models.CharField(choices=[('+1', '+1 (Canada)'), ('+44', '+44 (UK)'), ('+34', '+34 (Spain)'), ('+49', '+49 (Germany)'), ('+82', '+82 (South Korea)'), ('+1', '+1 (US)'), ('+55', '+55 (Brazil)'), ('+7', '+7 (Russia)'), ('+52', '+52 (Mexico)'), ('+39', '+39 (Italy)'), ('+81', '+81 (Japan)'), ('+966', '+966 (Saudi Arabia)'), ('+91', '+91 (India)'), ('+20', '+20 (Egypt)'), ('+64', '+64 (New Zealand)'), ('+971', '+971 (UAE)'), ('+86', '+86 (China)'), ('+65', '+65 (Singapore)'), ('+61', '+61 (Australia)'), ('+33', '+33 (France)')], max_length=250),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='discount_type',
            field=models.CharField(choices=[('Rate(%)', 'Rate(%)'), (None, '-------'), ('Fixed Amount', 'Fixed Amount')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='status',
            field=models.CharField(choices=[('Ended', 'Ended'), ('Ready to start', 'Ready to start'), ('Valid', 'Valid'), ('Cancelled', 'Cancelled'), ('Paused', 'Paused')], max_length=128),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='voucher_type',
            field=models.CharField(choices=[('Free Gift', 'Free Gift'), ('Manual Discount', 'Manual Discount'), ('Discount Voucher', 'Discount Voucher'), ('Product Combo', 'Product Combo')], max_length=128),
        ),
    ]
