# Generated by Django 3.2.16 on 2024-07-29 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0066_auto_20240729_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountvoucher',
            name='amount_trigger',
            field=models.CharField(choices=[('More than and equals to', 'More than and equals to'), (None, '-------'), ('Equals to', 'Equals to'), ('Less than', 'Less than'), ('More than', 'More than'), ('Less than and equals to', 'Less than and equals to')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='quantity_trigger',
            field=models.CharField(choices=[('More than and equals to', 'More than and equals to'), (None, '-------'), ('Equals to', 'Equals to'), ('Less than', 'Less than'), ('More than', 'More than'), ('Less than and equals to', 'Less than and equals to')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Partially Delivered', 'Partially Delivered'), ('Delivered', 'Delivered')], default='Pending', max_length=128),
        ),
        migrations.AlterField(
            model_name='stockinorder',
            name='stock_in_remark',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='prefix',
            field=models.CharField(choices=[('+971', '+971 (UAE)'), ('+1', '+1 (US)'), ('+49', '+49 (Germany)'), ('+44', '+44 (UK)'), ('+82', '+82 (South Korea)'), ('+52', '+52 (Mexico)'), ('+39', '+39 (Italy)'), ('+1', '+1 (Canada)'), ('+65', '+65 (Singapore)'), ('+55', '+55 (Brazil)'), ('+7', '+7 (Russia)'), ('+34', '+34 (Spain)'), ('+966', '+966 (Saudi Arabia)'), ('+61', '+61 (Australia)'), ('+33', '+33 (France)'), ('+91', '+91 (India)'), ('+64', '+64 (New Zealand)'), ('+81', '+81 (Japan)'), ('+86', '+86 (China)'), ('+20', '+20 (Egypt)')], max_length=250),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='status',
            field=models.CharField(choices=[('Valid', 'Valid'), ('Cancelled', 'Cancelled'), ('Ended', 'Ended'), ('Ready to start', 'Ready to start'), ('Paused', 'Paused')], max_length=128),
        ),
    ]
