# Generated by Django 3.2.16 on 2024-07-29 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0067_auto_20240729_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockinorder',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='amount_trigger',
            field=models.CharField(choices=[('More than and equals to', 'More than and equals to'), ('Less than', 'Less than'), ('Less than and equals to', 'Less than and equals to'), ('Equals to', 'Equals to'), (None, '-------'), ('More than', 'More than')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='quantity_trigger',
            field=models.CharField(choices=[('More than and equals to', 'More than and equals to'), ('Less than', 'Less than'), ('Less than and equals to', 'Less than and equals to'), ('Equals to', 'Equals to'), (None, '-------'), ('More than', 'More than')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='prefix',
            field=models.CharField(choices=[('+20', '+20 (Egypt)'), ('+39', '+39 (Italy)'), ('+34', '+34 (Spain)'), ('+966', '+966 (Saudi Arabia)'), ('+64', '+64 (New Zealand)'), ('+81', '+81 (Japan)'), ('+86', '+86 (China)'), ('+82', '+82 (South Korea)'), ('+55', '+55 (Brazil)'), ('+52', '+52 (Mexico)'), ('+44', '+44 (UK)'), ('+1', '+1 (US)'), ('+49', '+49 (Germany)'), ('+61', '+61 (Australia)'), ('+65', '+65 (Singapore)'), ('+7', '+7 (Russia)'), ('+91', '+91 (India)'), ('+1', '+1 (Canada)'), ('+33', '+33 (France)'), ('+971', '+971 (UAE)')], max_length=250),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='discount_type',
            field=models.CharField(choices=[('Fixed Amount', 'Fixed Amount'), ('Rate(%)', 'Rate(%)'), (None, '-------')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='status',
            field=models.CharField(choices=[('Valid', 'Valid'), ('Paused', 'Paused'), ('Cancelled', 'Cancelled'), ('Ended', 'Ended'), ('Ready to start', 'Ready to start')], max_length=128),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='voucher_type',
            field=models.CharField(choices=[('Free Gift', 'Free Gift'), ('Discount Voucher', 'Discount Voucher'), ('Manual Discount', 'Manual Discount'), ('Product Combo', 'Product Combo')], max_length=128),
        ),
    ]
