# Generated by Django 3.2.16 on 2024-08-28 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0068_auto_20240729_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountvoucher',
            name='amount_trigger',
            field=models.CharField(choices=[('Equals to', 'Equals to'), ('More than and equals to', 'More than and equals to'), ('Less than', 'Less than'), (None, '-------'), ('More than', 'More than'), ('Less than and equals to', 'Less than and equals to')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='quantity_trigger',
            field=models.CharField(choices=[('Equals to', 'Equals to'), ('More than and equals to', 'More than and equals to'), ('Less than', 'Less than'), (None, '-------'), ('More than', 'More than'), ('Less than and equals to', 'Less than and equals to')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='inventorypurchaseorder',
            name='expected_arrival_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='payment_method',
            field=models.CharField(choices=[('Bank Transfer/Cheque', 'Bank Transfer/Cheque'), ('COD', 'COD')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Pending', 'Pending'), ('Partially Delivered', 'Partially Delivered')], default='Pending', max_length=128),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='prefix',
            field=models.CharField(choices=[('+55', '+55 (Brazil)'), ('+1', '+1 (Canada)'), ('+91', '+91 (India)'), ('+82', '+82 (South Korea)'), ('+52', '+52 (Mexico)'), ('+34', '+34 (Spain)'), ('+81', '+81 (Japan)'), ('+966', '+966 (Saudi Arabia)'), ('+64', '+64 (New Zealand)'), ('+61', '+61 (Australia)'), ('+1', '+1 (US)'), ('+65', '+65 (Singapore)'), ('+971', '+971 (UAE)'), ('+33', '+33 (France)'), ('+7', '+7 (Russia)'), ('+20', '+20 (Egypt)'), ('+44', '+44 (UK)'), ('+86', '+86 (China)'), ('+49', '+49 (Germany)'), ('+39', '+39 (Italy)')], max_length=250),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='discount_type',
            field=models.CharField(choices=[(None, '-------'), ('Rate(%)', 'Rate(%)'), ('Fixed Amount', 'Fixed Amount')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='status',
            field=models.CharField(choices=[('Valid', 'Valid'), ('Ended', 'Ended'), ('Ready to start', 'Ready to start'), ('Cancelled', 'Cancelled'), ('Paused', 'Paused')], max_length=128),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='voucher_type',
            field=models.CharField(choices=[('Discount Voucher', 'Discount Voucher'), ('Product Combo', 'Product Combo'), ('Free Gift', 'Free Gift'), ('Manual Discount', 'Manual Discount')], max_length=128),
        ),
    ]
