# Generated by Django 3.2.16 on 2024-08-29 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0069_auto_20240828_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountvoucher',
            name='amount_trigger',
            field=models.CharField(choices=[(None, '-------'), ('Less than', 'Less than'), ('Less than and equals to', 'Less than and equals to'), ('More than and equals to', 'More than and equals to'), ('Equals to', 'Equals to'), ('More than', 'More than')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='quantity_trigger',
            field=models.CharField(choices=[(None, '-------'), ('Less than', 'Less than'), ('Less than and equals to', 'Less than and equals to'), ('More than and equals to', 'More than and equals to'), ('Equals to', 'Equals to'), ('More than', 'More than')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('Partially Delivered', 'Partially Delivered'), ('Pending', 'Pending'), ('Delivered', 'Delivered')], default='Pending', max_length=128),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='type',
            field=models.CharField(choices=[('Purchase', 'Purchase'), ('Quotation', 'Quotation')], max_length=128),
        ),
        migrations.AlterField(
            model_name='stockinorder',
            name='stockin_order_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='prefix',
            field=models.CharField(choices=[('+86', '+86 (China)'), ('+91', '+91 (India)'), ('+49', '+49 (Germany)'), ('+52', '+52 (Mexico)'), ('+55', '+55 (Brazil)'), ('+1', '+1 (US)'), ('+33', '+33 (France)'), ('+20', '+20 (Egypt)'), ('+64', '+64 (New Zealand)'), ('+971', '+971 (UAE)'), ('+44', '+44 (UK)'), ('+34', '+34 (Spain)'), ('+65', '+65 (Singapore)'), ('+39', '+39 (Italy)'), ('+61', '+61 (Australia)'), ('+966', '+966 (Saudi Arabia)'), ('+81', '+81 (Japan)'), ('+82', '+82 (South Korea)'), ('+1', '+1 (Canada)'), ('+7', '+7 (Russia)')], max_length=250),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='discount_type',
            field=models.CharField(choices=[('Rate(%)', 'Rate(%)'), (None, '-------'), ('Fixed Amount', 'Fixed Amount')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='status',
            field=models.CharField(choices=[('Ready to start', 'Ready to start'), ('Valid', 'Valid'), ('Cancelled', 'Cancelled'), ('Ended', 'Ended'), ('Paused', 'Paused')], max_length=128),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='voucher_type',
            field=models.CharField(choices=[('Free Gift', 'Free Gift'), ('Product Combo', 'Product Combo'), ('Manual Discount', 'Manual Discount'), ('Discount Voucher', 'Discount Voucher')], max_length=128),
        ),
    ]
