# Generated by Django 3.2.16 on 2024-09-06 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0070_auto_20240829_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(blank=True, choices=[('Redlivery', 'Redlivery'), ('Redlivery - Broken', 'Redlivery - Broken'), ('Redelivery & Return', 'Redelivery & Return'), ('Return', 'Return')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderitems',
            name='delivered_qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='amount_trigger',
            field=models.CharField(choices=[('More than and equals to', 'More than and equals to'), ('Less than and equals to', 'Less than and equals to'), ('More than', 'More than'), ('Less than', 'Less than'), ('Equals to', 'Equals to'), (None, '-------')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='quantity_trigger',
            field=models.CharField(choices=[('More than and equals to', 'More than and equals to'), ('Less than and equals to', 'Less than and equals to'), ('More than', 'More than'), ('Less than', 'Less than'), ('Equals to', 'Equals to'), (None, '-------')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Delivered', 'Delivered'), ('Partially Delivered', 'Partially Delivered')], default='Pending', max_length=128),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='prefix',
            field=models.CharField(choices=[('+65', '+65 (Singapore)'), ('+39', '+39 (Italy)'), ('+81', '+81 (Japan)'), ('+52', '+52 (Mexico)'), ('+34', '+34 (Spain)'), ('+82', '+82 (South Korea)'), ('+61', '+61 (Australia)'), ('+55', '+55 (Brazil)'), ('+1', '+1 (Canada)'), ('+86', '+86 (China)'), ('+44', '+44 (UK)'), ('+20', '+20 (Egypt)'), ('+91', '+91 (India)'), ('+49', '+49 (Germany)'), ('+966', '+966 (Saudi Arabia)'), ('+33', '+33 (France)'), ('+7', '+7 (Russia)'), ('+64', '+64 (New Zealand)'), ('+1', '+1 (US)'), ('+971', '+971 (UAE)')], max_length=250),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='discount_type',
            field=models.CharField(choices=[('Fixed Amount', 'Fixed Amount'), ('Rate(%)', 'Rate(%)'), (None, '-------')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='status',
            field=models.CharField(choices=[('Valid', 'Valid'), ('Cancelled', 'Cancelled'), ('Paused', 'Paused'), ('Ready to start', 'Ready to start'), ('Ended', 'Ended')], max_length=128),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='voucher_type',
            field=models.CharField(choices=[('Discount Voucher', 'Discount Voucher'), ('Free Gift', 'Free Gift'), ('Manual Discount', 'Manual Discount'), ('Product Combo', 'Product Combo')], max_length=128),
        ),
    ]
