# Generated by Django 3.2.16 on 2024-09-06 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0071_auto_20240906_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_fee',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='amount_trigger',
            field=models.CharField(choices=[('More than and equals to', 'More than and equals to'), ('More than', 'More than'), ('Less than', 'Less than'), (None, '-------'), ('Equals to', 'Equals to'), ('Less than and equals to', 'Less than and equals to')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='quantity_trigger',
            field=models.CharField(choices=[('More than and equals to', 'More than and equals to'), ('More than', 'More than'), ('Less than', 'Less than'), (None, '-------'), ('Equals to', 'Equals to'), ('Less than and equals to', 'Less than and equals to')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'COD'), ('Bank Transfer/Cheque', 'Bank Transfer/Cheque')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Partially Delivered', 'Partially Delivered'), ('Pending', 'Pending')], default='Pending', max_length=128),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='type',
            field=models.CharField(choices=[('Quotation', 'Quotation'), ('Purchase', 'Purchase')], max_length=128),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='prefix',
            field=models.CharField(choices=[('+49', '+49 (Germany)'), ('+64', '+64 (New Zealand)'), ('+44', '+44 (UK)'), ('+20', '+20 (Egypt)'), ('+61', '+61 (Australia)'), ('+52', '+52 (Mexico)'), ('+1', '+1 (US)'), ('+55', '+55 (Brazil)'), ('+39', '+39 (Italy)'), ('+33', '+33 (France)'), ('+1', '+1 (Canada)'), ('+91', '+91 (India)'), ('+966', '+966 (Saudi Arabia)'), ('+971', '+971 (UAE)'), ('+65', '+65 (Singapore)'), ('+81', '+81 (Japan)'), ('+7', '+7 (Russia)'), ('+34', '+34 (Spain)'), ('+86', '+86 (China)'), ('+82', '+82 (South Korea)')], max_length=250),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='status',
            field=models.CharField(choices=[('Valid', 'Valid'), ('Ready to start', 'Ready to start'), ('Ended', 'Ended'), ('Cancelled', 'Cancelled'), ('Paused', 'Paused')], max_length=128),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='voucher_type',
            field=models.CharField(choices=[('Product Combo', 'Product Combo'), ('Manual Discount', 'Manual Discount'), ('Discount Voucher', 'Discount Voucher'), ('Free Gift', 'Free Gift')], max_length=128),
        ),
    ]
