# Generated by Django 3.2.16 on 2024-09-09 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0073_auto_20240909_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountvoucher',
            name='amount_trigger',
            field=models.CharField(choices=[('Less than and equals to', 'Less than and equals to'), ('More than and equals to', 'More than and equals to'), ('Less than', 'Less than'), (None, '-------'), ('More than', 'More than'), ('Equals to', 'Equals to')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='quantity_trigger',
            field=models.CharField(choices=[('Less than and equals to', 'Less than and equals to'), ('More than and equals to', 'More than and equals to'), ('Less than', 'Less than'), (None, '-------'), ('More than', 'More than'), ('Equals to', 'Equals to')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(choices=[('Pending Delivery', 'Pending Delivery'), ('Partially Delivered', 'Partially Delivered'), ('Delivering', 'Delivering'), ('Delivered', 'Delivered'), ('Handling', 'Handling'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Out of Stock', 'Out of Stock'), ('Partial Out of Stock', 'Partial Out of Stock')], default='Pending Delivery', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'COD'), ('Bank Transfer/Cheque', 'Bank Transfer/Cheque')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('Partially Delivered', 'Partially Delivered'), ('Pending', 'Pending'), ('Delivered', 'Delivered')], default='Pending', max_length=128),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='prefix',
            field=models.CharField(choices=[('+34', '+34 (Spain)'), ('+49', '+49 (Germany)'), ('+82', '+82 (South Korea)'), ('+966', '+966 (Saudi Arabia)'), ('+61', '+61 (Australia)'), ('+52', '+52 (Mexico)'), ('+65', '+65 (Singapore)'), ('+86', '+86 (China)'), ('+64', '+64 (New Zealand)'), ('+39', '+39 (Italy)'), ('+20', '+20 (Egypt)'), ('+44', '+44 (UK)'), ('+1', '+1 (US)'), ('+91', '+91 (India)'), ('+55', '+55 (Brazil)'), ('+1', '+1 (Canada)'), ('+7', '+7 (Russia)'), ('+33', '+33 (France)'), ('+971', '+971 (UAE)'), ('+81', '+81 (Japan)')], max_length=250),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='discount_type',
            field=models.CharField(choices=[('Rate(%)', 'Rate(%)'), (None, '-------'), ('Fixed Amount', 'Fixed Amount')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='status',
            field=models.CharField(choices=[('Valid', 'Valid'), ('Paused', 'Paused'), ('Ended', 'Ended'), ('Ready to start', 'Ready to start'), ('Cancelled', 'Cancelled')], max_length=128),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='voucher_type',
            field=models.CharField(choices=[('Discount Voucher', 'Discount Voucher'), ('Free Gift', 'Free Gift'), ('Manual Discount', 'Manual Discount'), ('Product Combo', 'Product Combo')], max_length=128),
        ),
    ]
