# Generated by Django 3.2.16 on 2024-09-09 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0074_auto_20240909_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitems',
            name='delivery_status',
            field=models.CharField(choices=[('Pending Delivery', 'Pending Delivery'), ('Partially Delivered', 'Partially Delivered'), ('Delivering', 'Delivering'), ('Delivered', 'Delivered'), ('Handling', 'Handling'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Out of Stock', 'Out of Stock'), ('Partial Out of Stock', 'Partial Out of Stock')], default='Pending Delivery', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='amount_trigger',
            field=models.CharField(choices=[(None, '-------'), ('Equals to', 'Equals to'), ('Less than and equals to', 'Less than and equals to'), ('More than and equals to', 'More than and equals to'), ('More than', 'More than'), ('Less than', 'Less than')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='quantity_trigger',
            field=models.CharField(choices=[(None, '-------'), ('Equals to', 'Equals to'), ('Less than and equals to', 'Less than and equals to'), ('More than and equals to', 'More than and equals to'), ('More than', 'More than'), ('Less than', 'Less than')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Delivered', 'Delivered'), ('Partially Delivered', 'Partially Delivered')], default='Pending', max_length=128),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='type',
            field=models.CharField(choices=[('Purchase', 'Purchase'), ('Quotation', 'Quotation')], max_length=128),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='prefix',
            field=models.CharField(choices=[('+82', '+82 (South Korea)'), ('+52', '+52 (Mexico)'), ('+44', '+44 (UK)'), ('+966', '+966 (Saudi Arabia)'), ('+55', '+55 (Brazil)'), ('+34', '+34 (Spain)'), ('+33', '+33 (France)'), ('+91', '+91 (India)'), ('+971', '+971 (UAE)'), ('+64', '+64 (New Zealand)'), ('+7', '+7 (Russia)'), ('+1', '+1 (US)'), ('+39', '+39 (Italy)'), ('+20', '+20 (Egypt)'), ('+49', '+49 (Germany)'), ('+1', '+1 (Canada)'), ('+61', '+61 (Australia)'), ('+86', '+86 (China)'), ('+81', '+81 (Japan)'), ('+65', '+65 (Singapore)')], max_length=250),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='discount_type',
            field=models.CharField(choices=[(None, '-------'), ('Rate(%)', 'Rate(%)'), ('Fixed Amount', 'Fixed Amount')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='status',
            field=models.CharField(choices=[('Paused', 'Paused'), ('Valid', 'Valid'), ('Cancelled', 'Cancelled'), ('Ended', 'Ended'), ('Ready to start', 'Ready to start')], max_length=128),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='voucher_type',
            field=models.CharField(choices=[('Product Combo', 'Product Combo'), ('Manual Discount', 'Manual Discount'), ('Discount Voucher', 'Discount Voucher'), ('Free Gift', 'Free Gift')], max_length=128),
        ),
    ]
