# Generated by Django 3.2.16 on 2024-09-11 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0075_auto_20240909_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitems',
            name='delivered_qty',
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='amount_trigger',
            field=models.CharField(choices=[('Less than and equals to', 'Less than and equals to'), ('Equals to', 'Equals to'), ('Less than', 'Less than'), (None, '-------'), ('More than', 'More than'), ('More than and equals to', 'More than and equals to')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='quantity_trigger',
            field=models.CharField(choices=[('Less than and equals to', 'Less than and equals to'), ('Equals to', 'Equals to'), ('Less than', 'Less than'), (None, '-------'), ('More than', 'More than'), ('More than and equals to', 'More than and equals to')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='delivered_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='payment_method',
            field=models.CharField(choices=[('Bank Transfer/Cheque', 'Bank Transfer/Cheque'), ('COD', 'COD')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Pending', 'Pending'), ('Partially Delivered', 'Partially Delivered')], default='Pending', max_length=128),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='type',
            field=models.CharField(choices=[('Quotation', 'Quotation'), ('Purchase', 'Purchase')], max_length=128),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='prefix',
            field=models.CharField(choices=[('+55', '+55 (Brazil)'), ('+966', '+966 (Saudi Arabia)'), ('+34', '+34 (Spain)'), ('+20', '+20 (Egypt)'), ('+971', '+971 (UAE)'), ('+65', '+65 (Singapore)'), ('+61', '+61 (Australia)'), ('+7', '+7 (Russia)'), ('+1', '+1 (US)'), ('+1', '+1 (Canada)'), ('+44', '+44 (UK)'), ('+91', '+91 (India)'), ('+52', '+52 (Mexico)'), ('+64', '+64 (New Zealand)'), ('+81', '+81 (Japan)'), ('+86', '+86 (China)'), ('+49', '+49 (Germany)'), ('+33', '+33 (France)'), ('+39', '+39 (Italy)'), ('+82', '+82 (South Korea)')], max_length=250),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='discount_type',
            field=models.CharField(choices=[(None, '-------'), ('Fixed Amount', 'Fixed Amount'), ('Rate(%)', 'Rate(%)')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='status',
            field=models.CharField(choices=[('Ended', 'Ended'), ('Cancelled', 'Cancelled'), ('Ready to start', 'Ready to start'), ('Paused', 'Paused'), ('Valid', 'Valid')], max_length=128),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='voucher_type',
            field=models.CharField(choices=[('Free Gift', 'Free Gift'), ('Product Combo', 'Product Combo'), ('Discount Voucher', 'Discount Voucher'), ('Manual Discount', 'Manual Discount')], max_length=128),
        ),
    ]
