# Generated by Django 3.2.16 on 2024-09-12 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0076_auto_20240911_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='warehouse_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='amount_trigger',
            field=models.CharField(choices=[('Less than', 'Less than'), ('More than and equals to', 'More than and equals to'), ('More than', 'More than'), ('Equals to', 'Equals to'), ('Less than and equals to', 'Less than and equals to'), (None, '-------')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='quantity_trigger',
            field=models.CharField(choices=[('Less than', 'Less than'), ('More than and equals to', 'More than and equals to'), ('More than', 'More than'), ('Equals to', 'Equals to'), ('Less than and equals to', 'Less than and equals to'), (None, '-------')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'COD'), ('Bank Transfer/Cheque', 'Bank Transfer/Cheque')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Partially Delivered', 'Partially Delivered'), ('Pending', 'Pending')], default='Pending', max_length=128),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='type',
            field=models.CharField(choices=[('Purchase', 'Purchase'), ('Quotation', 'Quotation')], max_length=128),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='prefix',
            field=models.CharField(choices=[('+7', '+7 (Russia)'), ('+81', '+81 (Japan)'), ('+33', '+33 (France)'), ('+49', '+49 (Germany)'), ('+1', '+1 (Canada)'), ('+966', '+966 (Saudi Arabia)'), ('+64', '+64 (New Zealand)'), ('+971', '+971 (UAE)'), ('+1', '+1 (US)'), ('+52', '+52 (Mexico)'), ('+65', '+65 (Singapore)'), ('+44', '+44 (UK)'), ('+34', '+34 (Spain)'), ('+82', '+82 (South Korea)'), ('+86', '+86 (China)'), ('+91', '+91 (India)'), ('+55', '+55 (Brazil)'), ('+20', '+20 (Egypt)'), ('+39', '+39 (Italy)'), ('+61', '+61 (Australia)')], max_length=250),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='discount_type',
            field=models.CharField(choices=[('Rate(%)', 'Rate(%)'), (None, '-------'), ('Fixed Amount', 'Fixed Amount')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='status',
            field=models.CharField(choices=[('Ended', 'Ended'), ('Ready to start', 'Ready to start'), ('Cancelled', 'Cancelled'), ('Valid', 'Valid'), ('Paused', 'Paused')], max_length=128),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='voucher_type',
            field=models.CharField(choices=[('Discount Voucher', 'Discount Voucher'), ('Free Gift', 'Free Gift'), ('Manual Discount', 'Manual Discount'), ('Product Combo', 'Product Combo')], max_length=128),
        ),
    ]
