# Generated by Django 3.2.16 on 2024-09-12 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0077_auto_20240912_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountvoucher',
            name='amount_trigger',
            field=models.CharField(choices=[('Equals to', 'Equals to'), ('Less than', 'Less than'), ('More than and equals to', 'More than and equals to'), ('Less than and equals to', 'Less than and equals to'), (None, '-------'), ('More than', 'More than')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='quantity_trigger',
            field=models.CharField(choices=[('Equals to', 'Equals to'), ('Less than', 'Less than'), ('More than and equals to', 'More than and equals to'), ('Less than and equals to', 'Less than and equals to'), (None, '-------'), ('More than', 'More than')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(choices=[('Pending Delivery', 'Pending Delivery'), ('Partially Delivered', 'Partially Delivered'), ('Delivering', 'Delivering'), ('Delivered', 'Delivered'), ('Handling', 'Handling'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Out of Stock', 'Out of Stock'), ('Partial Out of Stock', 'Partial Out of Stock')], default='Pending', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='delivery_status',
            field=models.CharField(choices=[('Pending Delivery', 'Pending Delivery'), ('Partially Delivered', 'Partially Delivered'), ('Delivering', 'Delivering'), ('Delivered', 'Delivered'), ('Handling', 'Handling'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Out of Stock', 'Out of Stock'), ('Partial Out of Stock', 'Partial Out of Stock')], default='Pending', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Pending', 'Pending'), ('Partially Delivered', 'Partially Delivered')], default='Pending', max_length=128),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='prefix',
            field=models.CharField(choices=[('+34', '+34 (Spain)'), ('+971', '+971 (UAE)'), ('+44', '+44 (UK)'), ('+1', '+1 (US)'), ('+39', '+39 (Italy)'), ('+7', '+7 (Russia)'), ('+966', '+966 (Saudi Arabia)'), ('+82', '+82 (South Korea)'), ('+64', '+64 (New Zealand)'), ('+61', '+61 (Australia)'), ('+33', '+33 (France)'), ('+91', '+91 (India)'), ('+86', '+86 (China)'), ('+81', '+81 (Japan)'), ('+1', '+1 (Canada)'), ('+49', '+49 (Germany)'), ('+52', '+52 (Mexico)'), ('+55', '+55 (Brazil)'), ('+20', '+20 (Egypt)'), ('+65', '+65 (Singapore)')], max_length=250),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='discount_type',
            field=models.CharField(choices=[(None, '-------'), ('Fixed Amount', 'Fixed Amount'), ('Rate(%)', 'Rate(%)')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='status',
            field=models.CharField(choices=[('Ended', 'Ended'), ('Paused', 'Paused'), ('Ready to start', 'Ready to start'), ('Valid', 'Valid'), ('Cancelled', 'Cancelled')], max_length=128),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='voucher_type',
            field=models.CharField(choices=[('Manual Discount', 'Manual Discount'), ('Product Combo', 'Product Combo'), ('Free Gift', 'Free Gift'), ('Discount Voucher', 'Discount Voucher')], max_length=128),
        ),
    ]
