# Generated by Django 3.2.16 on 2024-09-12 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0078_auto_20240912_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountvoucher',
            name='amount_trigger',
            field=models.CharField(choices=[('Less than', 'Less than'), ('Equals to', 'Equals to'), ('More than', 'More than'), (None, '-------'), ('More than and equals to', 'More than and equals to'), ('Less than and equals to', 'Less than and equals to')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='quantity_trigger',
            field=models.CharField(choices=[('Less than', 'Less than'), ('Equals to', 'Equals to'), ('More than', 'More than'), (None, '-------'), ('More than and equals to', 'More than and equals to'), ('Less than and equals to', 'Less than and equals to')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Pending Delivery', 'Pending Delivery'), ('Partially Delivered', 'Partially Delivered'), ('Delivering', 'Delivering'), ('Delivered', 'Delivered'), ('Handling', 'Handling'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Out of Stock', 'Out of Stock'), ('Partial Out of Stock', 'Partial Out of Stock')], default='Pending', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='delivery_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Pending Delivery', 'Pending Delivery'), ('Partially Delivered', 'Partially Delivered'), ('Delivering', 'Delivering'), ('Delivered', 'Delivered'), ('Handling', 'Handling'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Out of Stock', 'Out of Stock'), ('Partial Out of Stock', 'Partial Out of Stock')], default='Pending', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='payment_method',
            field=models.CharField(choices=[('Bank Transfer/Cheque', 'Bank Transfer/Cheque'), ('COD', 'COD')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('Partially Delivered', 'Partially Delivered'), ('Delivered', 'Delivered'), ('Pending', 'Pending')], default='Pending', max_length=128),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='prefix',
            field=models.CharField(choices=[('+91', '+91 (India)'), ('+39', '+39 (Italy)'), ('+61', '+61 (Australia)'), ('+966', '+966 (Saudi Arabia)'), ('+65', '+65 (Singapore)'), ('+52', '+52 (Mexico)'), ('+55', '+55 (Brazil)'), ('+44', '+44 (UK)'), ('+82', '+82 (South Korea)'), ('+1', '+1 (Canada)'), ('+971', '+971 (UAE)'), ('+7', '+7 (Russia)'), ('+34', '+34 (Spain)'), ('+81', '+81 (Japan)'), ('+33', '+33 (France)'), ('+1', '+1 (US)'), ('+86', '+86 (China)'), ('+49', '+49 (Germany)'), ('+64', '+64 (New Zealand)'), ('+20', '+20 (Egypt)')], max_length=250),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='discount_type',
            field=models.CharField(choices=[('Fixed Amount', 'Fixed Amount'), ('Rate(%)', 'Rate(%)'), (None, '-------')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='status',
            field=models.CharField(choices=[('Ended', 'Ended'), ('Cancelled', 'Cancelled'), ('Ready to start', 'Ready to start'), ('Valid', 'Valid'), ('Paused', 'Paused')], max_length=128),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='voucher_type',
            field=models.CharField(choices=[('Free Gift', 'Free Gift'), ('Product Combo', 'Product Combo'), ('Manual Discount', 'Manual Discount'), ('Discount Voucher', 'Discount Voucher')], max_length=128),
        ),
    ]
