# Generated by Django 3.2.16 on 2024-09-12 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0079_auto_20240912_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountvoucher',
            name='amount_trigger',
            field=models.CharField(choices=[('Equals to', 'Equals to'), ('Less than', 'Less than'), (None, '-------'), ('More than and equals to', 'More than and equals to'), ('More than', 'More than'), ('Less than and equals to', 'Less than and equals to')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='quantity_trigger',
            field=models.CharField(choices=[('Equals to', 'Equals to'), ('Less than', 'Less than'), (None, '-------'), ('More than and equals to', 'More than and equals to'), ('More than', 'More than'), ('Less than and equals to', 'Less than and equals to')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Partially Delivered', 'Partially Delivered'), ('Pending', 'Pending')], default='Pending', max_length=128),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='prefix',
            field=models.CharField(choices=[('+81', '+81 (Japan)'), ('+39', '+39 (Italy)'), ('+64', '+64 (New Zealand)'), ('+52', '+52 (Mexico)'), ('+33', '+33 (France)'), ('+82', '+82 (South Korea)'), ('+1', '+1 (US)'), ('+1', '+1 (Canada)'), ('+65', '+65 (Singapore)'), ('+49', '+49 (Germany)'), ('+7', '+7 (Russia)'), ('+34', '+34 (Spain)'), ('+971', '+971 (UAE)'), ('+91', '+91 (India)'), ('+20', '+20 (Egypt)'), ('+86', '+86 (China)'), ('+55', '+55 (Brazil)'), ('+44', '+44 (UK)'), ('+966', '+966 (Saudi Arabia)'), ('+61', '+61 (Australia)')], max_length=250),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='discount_type',
            field=models.CharField(choices=[('Rate(%)', 'Rate(%)'), (None, '-------'), ('Fixed Amount', 'Fixed Amount')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='status',
            field=models.CharField(choices=[('Paused', 'Paused'), ('Valid', 'Valid'), ('Cancelled', 'Cancelled'), ('Ended', 'Ended'), ('Ready to start', 'Ready to start')], max_length=128),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='voucher_type',
            field=models.CharField(choices=[('Product Combo', 'Product Combo'), ('Manual Discount', 'Manual Discount'), ('Free Gift', 'Free Gift'), ('Discount Voucher', 'Discount Voucher')], max_length=128),
        ),
    ]
