# Generated by Django 3.2.16 on 2024-09-13 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0080_auto_20240912_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitems',
            name='delivered_quantity',
        ),
        migrations.RemoveField(
            model_name='orderitems',
            name='delivery_date',
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='amount_trigger',
            field=models.CharField(choices=[('Less than and equals to', 'Less than and equals to'), ('More than and equals to', 'More than and equals to'), ('More than', 'More than'), ('Less than', 'Less than'), (None, '-------'), ('Equals to', 'Equals to')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='quantity_trigger',
            field=models.CharField(choices=[('Less than and equals to', 'Less than and equals to'), ('More than and equals to', 'More than and equals to'), ('More than', 'More than'), ('Less than', 'Less than'), (None, '-------'), ('Equals to', 'Equals to')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'COD'), ('Bank Transfer/Cheque', 'Bank Transfer/Cheque')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('Partially Delivered', 'Partially Delivered'), ('Pending', 'Pending'), ('Delivered', 'Delivered')], default='Pending', max_length=128),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='prefix',
            field=models.CharField(choices=[('+91', '+91 (India)'), ('+971', '+971 (UAE)'), ('+61', '+61 (Australia)'), ('+966', '+966 (Saudi Arabia)'), ('+34', '+34 (Spain)'), ('+86', '+86 (China)'), ('+20', '+20 (Egypt)'), ('+81', '+81 (Japan)'), ('+52', '+52 (Mexico)'), ('+44', '+44 (UK)'), ('+33', '+33 (France)'), ('+65', '+65 (Singapore)'), ('+49', '+49 (Germany)'), ('+64', '+64 (New Zealand)'), ('+82', '+82 (South Korea)'), ('+1', '+1 (US)'), ('+1', '+1 (Canada)'), ('+39', '+39 (Italy)'), ('+55', '+55 (Brazil)'), ('+7', '+7 (Russia)')], max_length=250),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='discount_type',
            field=models.CharField(choices=[('Rate(%)', 'Rate(%)'), ('Fixed Amount', 'Fixed Amount'), (None, '-------')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='status',
            field=models.CharField(choices=[('Ready to start', 'Ready to start'), ('Paused', 'Paused'), ('Cancelled', 'Cancelled'), ('Valid', 'Valid'), ('Ended', 'Ended')], max_length=128),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='voucher_type',
            field=models.CharField(choices=[('Discount Voucher', 'Discount Voucher'), ('Product Combo', 'Product Combo'), ('Manual Discount', 'Manual Discount'), ('Free Gift', 'Free Gift')], max_length=128),
        ),
        migrations.CreateModel(
            name='DeliverOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('deliver_id', models.CharField(blank=True, max_length=128, null=True)),
                ('delivered_quantity', models.IntegerField(default=0)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.order')),
                ('order_items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.orderitems')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
