# Generated by Django 3.2.16 on 2024-09-13 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0083_auto_20240913_0938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverorder',
            name='delivered_quantity',
        ),
        migrations.RemoveField(
            model_name='deliverorder',
            name='delivery_date',
        ),
        migrations.RemoveField(
            model_name='deliverorder',
            name='order_items',
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='amount_trigger',
            field=models.CharField(choices=[('Less than and equals to', 'Less than and equals to'), (None, '-------'), ('Less than', 'Less than'), ('Equals to', 'Equals to'), ('More than', 'More than'), ('More than and equals to', 'More than and equals to')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='quantity_trigger',
            field=models.CharField(choices=[('Less than and equals to', 'Less than and equals to'), (None, '-------'), ('Less than', 'Less than'), ('Equals to', 'Equals to'), ('More than', 'More than'), ('More than and equals to', 'More than and equals to')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Partially Delivered', 'Partially Delivered'), ('Pending', 'Pending')], default='Pending', max_length=128),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='type',
            field=models.CharField(choices=[('Quotation', 'Quotation'), ('Purchase', 'Purchase')], max_length=128),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='prefix',
            field=models.CharField(choices=[('+81', '+81 (Japan)'), ('+65', '+65 (Singapore)'), ('+44', '+44 (UK)'), ('+82', '+82 (South Korea)'), ('+61', '+61 (Australia)'), ('+7', '+7 (Russia)'), ('+966', '+966 (Saudi Arabia)'), ('+20', '+20 (Egypt)'), ('+55', '+55 (Brazil)'), ('+86', '+86 (China)'), ('+52', '+52 (Mexico)'), ('+33', '+33 (France)'), ('+49', '+49 (Germany)'), ('+64', '+64 (New Zealand)'), ('+34', '+34 (Spain)'), ('+91', '+91 (India)'), ('+971', '+971 (UAE)'), ('+1', '+1 (US)'), ('+39', '+39 (Italy)'), ('+1', '+1 (Canada)')], max_length=250),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='discount_type',
            field=models.CharField(choices=[('Rate(%)', 'Rate(%)'), (None, '-------'), ('Fixed Amount', 'Fixed Amount')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='status',
            field=models.CharField(choices=[('Cancelled', 'Cancelled'), ('Valid', 'Valid'), ('Paused', 'Paused'), ('Ready to start', 'Ready to start'), ('Ended', 'Ended')], max_length=128),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='voucher_type',
            field=models.CharField(choices=[('Product Combo', 'Product Combo'), ('Discount Voucher', 'Discount Voucher'), ('Free Gift', 'Free Gift'), ('Manual Discount', 'Manual Discount')], max_length=128),
        ),
        migrations.CreateModel(
            name='DeliverOrderitems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('delivered_quantity', models.IntegerField(default=0)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('order_items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.orderitems')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
