# Generated by Django 3.2.16 on 2024-09-13 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0085_auto_20240913_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverorder',
            name='order',
        ),
        migrations.AddField(
            model_name='deliverorderitems',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.order'),
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='amount_trigger',
            field=models.CharField(choices=[('Equals to', 'Equals to'), ('More than and equals to', 'More than and equals to'), ('Less than and equals to', 'Less than and equals to'), ('Less than', 'Less than'), ('More than', 'More than'), (None, '-------')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='quantity_trigger',
            field=models.CharField(choices=[('Equals to', 'Equals to'), ('More than and equals to', 'More than and equals to'), ('Less than and equals to', 'Less than and equals to'), ('Less than', 'Less than'), ('More than', 'More than'), (None, '-------')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('Partially Delivered', 'Partially Delivered'), ('Delivered', 'Delivered'), ('Pending', 'Pending')], default='Pending', max_length=128),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='type',
            field=models.CharField(choices=[('Quotation', 'Quotation'), ('Purchase', 'Purchase')], max_length=128),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='prefix',
            field=models.CharField(choices=[('+39', '+39 (Italy)'), ('+971', '+971 (UAE)'), ('+1', '+1 (US)'), ('+55', '+55 (Brazil)'), ('+52', '+52 (Mexico)'), ('+61', '+61 (Australia)'), ('+82', '+82 (South Korea)'), ('+20', '+20 (Egypt)'), ('+34', '+34 (Spain)'), ('+81', '+81 (Japan)'), ('+1', '+1 (Canada)'), ('+44', '+44 (UK)'), ('+65', '+65 (Singapore)'), ('+7', '+7 (Russia)'), ('+91', '+91 (India)'), ('+86', '+86 (China)'), ('+64', '+64 (New Zealand)'), ('+966', '+966 (Saudi Arabia)'), ('+49', '+49 (Germany)'), ('+33', '+33 (France)')], max_length=250),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='discount_type',
            field=models.CharField(choices=[(None, '-------'), ('Fixed Amount', 'Fixed Amount'), ('Rate(%)', 'Rate(%)')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='status',
            field=models.CharField(choices=[('Cancelled', 'Cancelled'), ('Paused', 'Paused'), ('Valid', 'Valid'), ('Ended', 'Ended'), ('Ready to start', 'Ready to start')], max_length=128),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='voucher_type',
            field=models.CharField(choices=[('Manual Discount', 'Manual Discount'), ('Product Combo', 'Product Combo'), ('Discount Voucher', 'Discount Voucher'), ('Free Gift', 'Free Gift')], max_length=128),
        ),
    ]
