# Generated by Django 3.2.16 on 2024-09-13 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0086_auto_20240913_1210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliverorder',
            old_name='deliver_id',
            new_name='delivery_id',
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='amount_trigger',
            field=models.CharField(choices=[('Less than', 'Less than'), ('Equals to', 'Equals to'), (None, '-------'), ('More than', 'More than'), ('More than and equals to', 'More than and equals to'), ('Less than and equals to', 'Less than and equals to')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='quantity_trigger',
            field=models.CharField(choices=[('Less than', 'Less than'), ('Equals to', 'Equals to'), (None, '-------'), ('More than', 'More than'), ('More than and equals to', 'More than and equals to'), ('Less than and equals to', 'Less than and equals to')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Delivered', 'Delivered'), ('Partially Delivered', 'Partially Delivered')], default='Pending', max_length=128),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='prefix',
            field=models.CharField(choices=[('+64', '+64 (New Zealand)'), ('+7', '+7 (Russia)'), ('+1', '+1 (Canada)'), ('+65', '+65 (Singapore)'), ('+1', '+1 (US)'), ('+39', '+39 (Italy)'), ('+44', '+44 (UK)'), ('+55', '+55 (Brazil)'), ('+971', '+971 (UAE)'), ('+34', '+34 (Spain)'), ('+20', '+20 (Egypt)'), ('+86', '+86 (China)'), ('+52', '+52 (Mexico)'), ('+82', '+82 (South Korea)'), ('+49', '+49 (Germany)'), ('+61', '+61 (Australia)'), ('+91', '+91 (India)'), ('+966', '+966 (Saudi Arabia)'), ('+33', '+33 (France)'), ('+81', '+81 (Japan)')], max_length=250),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='discount_type',
            field=models.CharField(choices=[('Rate(%)', 'Rate(%)'), ('Fixed Amount', 'Fixed Amount'), (None, '-------')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='status',
            field=models.CharField(choices=[('Ready to start', 'Ready to start'), ('Valid', 'Valid'), ('Paused', 'Paused'), ('Ended', 'Ended'), ('Cancelled', 'Cancelled')], max_length=128),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='voucher_type',
            field=models.CharField(choices=[('Product Combo', 'Product Combo'), ('Free Gift', 'Free Gift'), ('Discount Voucher', 'Discount Voucher'), ('Manual Discount', 'Manual Discount')], max_length=128),
        ),
    ]
