# Generated by Django 3.2.16 on 2024-09-13 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0087_auto_20240913_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_id',
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='amount_trigger',
            field=models.CharField(choices=[('More than', 'More than'), ('Less than and equals to', 'Less than and equals to'), ('Equals to', 'Equals to'), (None, '-------'), ('More than and equals to', 'More than and equals to'), ('Less than', 'Less than')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='quantity_trigger',
            field=models.CharField(choices=[('More than', 'More than'), ('Less than and equals to', 'Less than and equals to'), ('Equals to', 'Equals to'), (None, '-------'), ('More than and equals to', 'More than and equals to'), ('Less than', 'Less than')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('Partially Delivered', 'Partially Delivered'), ('Delivered', 'Delivered'), ('Pending', 'Pending')], default='Pending', max_length=128),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='prefix',
            field=models.CharField(choices=[('+20', '+20 (Egypt)'), ('+82', '+82 (South Korea)'), ('+7', '+7 (Russia)'), ('+64', '+64 (New Zealand)'), ('+1', '+1 (Canada)'), ('+91', '+91 (India)'), ('+39', '+39 (Italy)'), ('+34', '+34 (Spain)'), ('+1', '+1 (US)'), ('+65', '+65 (Singapore)'), ('+55', '+55 (Brazil)'), ('+61', '+61 (Australia)'), ('+33', '+33 (France)'), ('+971', '+971 (UAE)'), ('+966', '+966 (Saudi Arabia)'), ('+44', '+44 (UK)'), ('+49', '+49 (Germany)'), ('+86', '+86 (China)'), ('+52', '+52 (Mexico)'), ('+81', '+81 (Japan)')], max_length=250),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='status',
            field=models.CharField(choices=[('Paused', 'Paused'), ('Ended', 'Ended'), ('Cancelled', 'Cancelled'), ('Valid', 'Valid'), ('Ready to start', 'Ready to start')], max_length=128),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='voucher_type',
            field=models.CharField(choices=[('Manual Discount', 'Manual Discount'), ('Discount Voucher', 'Discount Voucher'), ('Product Combo', 'Product Combo'), ('Free Gift', 'Free Gift')], max_length=128),
        ),
    ]
