# Generated by Django 3.2.16 on 2024-09-16 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0088_auto_20240913_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverorderitems',
            name='order',
        ),
        migrations.AddField(
            model_name='deliverorder',
            name='delivery_fee',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='deliverorder',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.order'),
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='amount_trigger',
            field=models.CharField(choices=[(None, '-------'), ('Less than', 'Less than'), ('Less than and equals to', 'Less than and equals to'), ('More than and equals to', 'More than and equals to'), ('Equals to', 'Equals to'), ('More than', 'More than')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='quantity_trigger',
            field=models.CharField(choices=[(None, '-------'), ('Less than', 'Less than'), ('Less than and equals to', 'Less than and equals to'), ('More than and equals to', 'More than and equals to'), ('Equals to', 'Equals to'), ('More than', 'More than')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Pending', 'Pending'), ('Partially Delivered', 'Partially Delivered')], default='Pending', max_length=128),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='prefix',
            field=models.CharField(choices=[('+971', '+971 (UAE)'), ('+34', '+34 (Spain)'), ('+39', '+39 (Italy)'), ('+20', '+20 (Egypt)'), ('+1', '+1 (Canada)'), ('+65', '+65 (Singapore)'), ('+86', '+86 (China)'), ('+91', '+91 (India)'), ('+82', '+82 (South Korea)'), ('+64', '+64 (New Zealand)'), ('+7', '+7 (Russia)'), ('+55', '+55 (Brazil)'), ('+966', '+966 (Saudi Arabia)'), ('+61', '+61 (Australia)'), ('+33', '+33 (France)'), ('+44', '+44 (UK)'), ('+49', '+49 (Germany)'), ('+81', '+81 (Japan)'), ('+52', '+52 (Mexico)'), ('+1', '+1 (US)')], max_length=250),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='discount_type',
            field=models.CharField(choices=[(None, '-------'), ('Fixed Amount', 'Fixed Amount'), ('Rate(%)', 'Rate(%)')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='status',
            field=models.CharField(choices=[('Ready to start', 'Ready to start'), ('Cancelled', 'Cancelled'), ('Ended', 'Ended'), ('Paused', 'Paused'), ('Valid', 'Valid')], max_length=128),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='voucher_type',
            field=models.CharField(choices=[('Product Combo', 'Product Combo'), ('Discount Voucher', 'Discount Voucher'), ('Manual Discount', 'Manual Discount'), ('Free Gift', 'Free Gift')], max_length=128),
        ),
    ]
