# Generated by Django 3.2.16 on 2024-09-16 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0089_auto_20240916_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_fee',
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='amount_trigger',
            field=models.CharField(choices=[('Equals to', 'Equals to'), ('Less than', 'Less than'), ('More than and equals to', 'More than and equals to'), ('More than', 'More than'), (None, '-------'), ('Less than and equals to', 'Less than and equals to')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='quantity_trigger',
            field=models.CharField(choices=[('Equals to', 'Equals to'), ('Less than', 'Less than'), ('More than and equals to', 'More than and equals to'), ('More than', 'More than'), (None, '-------'), ('Less than and equals to', 'Less than and equals to')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Partially Delivered', 'Partially Delivered'), ('Pending', 'Pending')], default='Pending', max_length=128),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='type',
            field=models.CharField(choices=[('Purchase', 'Purchase'), ('Quotation', 'Quotation')], max_length=128),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='prefix',
            field=models.CharField(choices=[('+91', '+91 (India)'), ('+1', '+1 (US)'), ('+44', '+44 (UK)'), ('+86', '+86 (China)'), ('+64', '+64 (New Zealand)'), ('+55', '+55 (Brazil)'), ('+81', '+81 (Japan)'), ('+971', '+971 (UAE)'), ('+39', '+39 (Italy)'), ('+49', '+49 (Germany)'), ('+61', '+61 (Australia)'), ('+20', '+20 (Egypt)'), ('+52', '+52 (Mexico)'), ('+1', '+1 (Canada)'), ('+33', '+33 (France)'), ('+966', '+966 (Saudi Arabia)'), ('+82', '+82 (South Korea)'), ('+65', '+65 (Singapore)'), ('+34', '+34 (Spain)'), ('+7', '+7 (Russia)')], max_length=250),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='discount_type',
            field=models.CharField(choices=[('Rate(%)', 'Rate(%)'), ('Fixed Amount', 'Fixed Amount'), (None, '-------')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='status',
            field=models.CharField(choices=[('Paused', 'Paused'), ('Cancelled', 'Cancelled'), ('Ready to start', 'Ready to start'), ('Ended', 'Ended'), ('Valid', 'Valid')], max_length=128),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='voucher_type',
            field=models.CharField(choices=[('Free Gift', 'Free Gift'), ('Discount Voucher', 'Discount Voucher'), ('Manual Discount', 'Manual Discount'), ('Product Combo', 'Product Combo')], max_length=128),
        ),
    ]
