# Generated by Django 3.2.16 on 2024-09-16 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0091_auto_20240916_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverorderitems',
            name='delivery_date',
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='amount_trigger',
            field=models.CharField(choices=[('Equals to', 'Equals to'), (None, '-------'), ('Less than and equals to', 'Less than and equals to'), ('Less than', 'Less than'), ('More than', 'More than'), ('More than and equals to', 'More than and equals to')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='quantity_trigger',
            field=models.CharField(choices=[('Equals to', 'Equals to'), (None, '-------'), ('Less than and equals to', 'Less than and equals to'), ('Less than', 'Less than'), ('More than', 'More than'), ('More than and equals to', 'More than and equals to')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Partially Delivered', 'Partially Delivered'), ('Pending', 'Pending')], default='Pending', max_length=128),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='type',
            field=models.CharField(choices=[('Purchase', 'Purchase'), ('Quotation', 'Quotation')], max_length=128),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='prefix',
            field=models.CharField(choices=[('+91', '+91 (India)'), ('+39', '+39 (Italy)'), ('+81', '+81 (Japan)'), ('+1', '+1 (US)'), ('+49', '+49 (Germany)'), ('+65', '+65 (Singapore)'), ('+7', '+7 (Russia)'), ('+1', '+1 (Canada)'), ('+966', '+966 (Saudi Arabia)'), ('+55', '+55 (Brazil)'), ('+82', '+82 (South Korea)'), ('+33', '+33 (France)'), ('+64', '+64 (New Zealand)'), ('+61', '+61 (Australia)'), ('+20', '+20 (Egypt)'), ('+52', '+52 (Mexico)'), ('+971', '+971 (UAE)'), ('+86', '+86 (China)'), ('+44', '+44 (UK)'), ('+34', '+34 (Spain)')], max_length=250),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='discount_type',
            field=models.CharField(choices=[('Rate(%)', 'Rate(%)'), (None, '-------'), ('Fixed Amount', 'Fixed Amount')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='status',
            field=models.CharField(choices=[('Ended', 'Ended'), ('Cancelled', 'Cancelled'), ('Paused', 'Paused'), ('Valid', 'Valid'), ('Ready to start', 'Ready to start')], max_length=128),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='voucher_type',
            field=models.CharField(choices=[('Free Gift', 'Free Gift'), ('Product Combo', 'Product Combo'), ('Manual Discount', 'Manual Discount'), ('Discount Voucher', 'Discount Voucher')], max_length=128),
        ),
    ]
