# Generated by Django 3.2.16 on 2024-09-19 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0092_auto_20240916_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverorder',
            name='cancel_delivery_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliverorder',
            name='delivery_status',
            field=models.CharField(blank=True, choices=[('Cancelled', 'Cancelled')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='amount_trigger',
            field=models.CharField(choices=[('Less than and equals to', 'Less than and equals to'), ('Equals to', 'Equals to'), (None, '-------'), ('Less than', 'Less than'), ('More than and equals to', 'More than and equals to'), ('More than', 'More than')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='quantity_trigger',
            field=models.CharField(choices=[('Less than and equals to', 'Less than and equals to'), ('Equals to', 'Equals to'), (None, '-------'), ('Less than', 'Less than'), ('More than and equals to', 'More than and equals to'), ('More than', 'More than')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'COD'), ('Bank Transfer/Cheque', 'Bank Transfer/Cheque')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Delivered', 'Delivered'), ('Partially Delivered', 'Partially Delivered')], default='Pending', max_length=128),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='prefix',
            field=models.CharField(choices=[('+1', '+1 (US)'), ('+49', '+49 (Germany)'), ('+34', '+34 (Spain)'), ('+61', '+61 (Australia)'), ('+33', '+33 (France)'), ('+7', '+7 (Russia)'), ('+39', '+39 (Italy)'), ('+971', '+971 (UAE)'), ('+20', '+20 (Egypt)'), ('+81', '+81 (Japan)'), ('+65', '+65 (Singapore)'), ('+52', '+52 (Mexico)'), ('+1', '+1 (Canada)'), ('+86', '+86 (China)'), ('+82', '+82 (South Korea)'), ('+44', '+44 (UK)'), ('+966', '+966 (Saudi Arabia)'), ('+55', '+55 (Brazil)'), ('+64', '+64 (New Zealand)'), ('+91', '+91 (India)')], max_length=250),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='discount_type',
            field=models.CharField(choices=[(None, '-------'), ('Fixed Amount', 'Fixed Amount'), ('Rate(%)', 'Rate(%)')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='status',
            field=models.CharField(choices=[('Ended', 'Ended'), ('Valid', 'Valid'), ('Cancelled', 'Cancelled'), ('Ready to start', 'Ready to start'), ('Paused', 'Paused')], max_length=128),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='voucher_type',
            field=models.CharField(choices=[('Manual Discount', 'Manual Discount'), ('Free Gift', 'Free Gift'), ('Discount Voucher', 'Discount Voucher'), ('Product Combo', 'Product Combo')], max_length=128),
        ),
    ]
