# Generated by Django 3.2.16 on 2024-09-19 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0093_auto_20240919_1503'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliverorder',
            old_name='delivery_status',
            new_name='delivered_order_status',
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='amount_trigger',
            field=models.CharField(choices=[(None, '-------'), ('Equals to', 'Equals to'), ('Less than and equals to', 'Less than and equals to'), ('More than', 'More than'), ('Less than', 'Less than'), ('More than and equals to', 'More than and equals to')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='quantity_trigger',
            field=models.CharField(choices=[(None, '-------'), ('Equals to', 'Equals to'), ('Less than and equals to', 'Less than and equals to'), ('More than', 'More than'), ('Less than', 'Less than'), ('More than and equals to', 'More than and equals to')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='payment_method',
            field=models.CharField(choices=[('Bank Transfer/Cheque', 'Bank Transfer/Cheque'), ('COD', 'COD')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Partially Delivered', 'Partially Delivered'), ('Pending', 'Pending')], default='Pending', max_length=128),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='type',
            field=models.CharField(choices=[('Quotation', 'Quotation'), ('Purchase', 'Purchase')], max_length=128),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='prefix',
            field=models.CharField(choices=[('+64', '+64 (New Zealand)'), ('+39', '+39 (Italy)'), ('+86', '+86 (China)'), ('+65', '+65 (Singapore)'), ('+20', '+20 (Egypt)'), ('+82', '+82 (South Korea)'), ('+61', '+61 (Australia)'), ('+34', '+34 (Spain)'), ('+81', '+81 (Japan)'), ('+91', '+91 (India)'), ('+33', '+33 (France)'), ('+7', '+7 (Russia)'), ('+55', '+55 (Brazil)'), ('+966', '+966 (Saudi Arabia)'), ('+971', '+971 (UAE)'), ('+52', '+52 (Mexico)'), ('+44', '+44 (UK)'), ('+49', '+49 (Germany)'), ('+1', '+1 (US)'), ('+1', '+1 (Canada)')], max_length=250),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='status',
            field=models.CharField(choices=[('Valid', 'Valid'), ('Ended', 'Ended'), ('Cancelled', 'Cancelled'), ('Ready to start', 'Ready to start'), ('Paused', 'Paused')], max_length=128),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='voucher_type',
            field=models.CharField(choices=[('Free Gift', 'Free Gift'), ('Discount Voucher', 'Discount Voucher'), ('Product Combo', 'Product Combo'), ('Manual Discount', 'Manual Discount')], max_length=128),
        ),
    ]
