# Generated by Django 3.2.16 on 2024-09-20 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0094_auto_20240919_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountvoucher',
            name='amount_trigger',
            field=models.CharField(choices=[('Equals to', 'Equals to'), ('Less than and equals to', 'Less than and equals to'), ('Less than', 'Less than'), ('More than and equals to', 'More than and equals to'), (None, '-------'), ('More than', 'More than')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='quantity_trigger',
            field=models.CharField(choices=[('Equals to', 'Equals to'), ('Less than and equals to', 'Less than and equals to'), ('Less than', 'Less than'), ('More than and equals to', 'More than and equals to'), (None, '-------'), ('More than', 'More than')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'COD'), ('Bank Transfer/Cheque', 'Bank Transfer/Cheque')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('Partially Delivered', 'Partially Delivered'), ('Delivered', 'Delivered'), ('Pending', 'Pending')], default='Pending', max_length=128),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='prefix',
            field=models.CharField(choices=[('+52', '+52 (Mexico)'), ('+971', '+971 (UAE)'), ('+55', '+55 (Brazil)'), ('+44', '+44 (UK)'), ('+61', '+61 (Australia)'), ('+33', '+33 (France)'), ('+82', '+82 (South Korea)'), ('+86', '+86 (China)'), ('+49', '+49 (Germany)'), ('+65', '+65 (Singapore)'), ('+64', '+64 (New Zealand)'), ('+20', '+20 (Egypt)'), ('+1', '+1 (Canada)'), ('+7', '+7 (Russia)'), ('+91', '+91 (India)'), ('+81', '+81 (Japan)'), ('+39', '+39 (Italy)'), ('+1', '+1 (US)'), ('+966', '+966 (Saudi Arabia)'), ('+34', '+34 (Spain)')], max_length=250),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='discount_type',
            field=models.CharField(choices=[('Fixed Amount', 'Fixed Amount'), ('Rate(%)', 'Rate(%)'), (None, '-------')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='status',
            field=models.CharField(choices=[('Valid', 'Valid'), ('Ready to start', 'Ready to start'), ('Ended', 'Ended'), ('Cancelled', 'Cancelled'), ('Paused', 'Paused')], max_length=128),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='voucher_type',
            field=models.CharField(choices=[('Product Combo', 'Product Combo'), ('Manual Discount', 'Manual Discount'), ('Discount Voucher', 'Discount Voucher'), ('Free Gift', 'Free Gift')], max_length=128),
        ),
        migrations.CreateModel(
            name='AfterSalesOrderitems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('failed_delivery_quantity', models.IntegerField(default=0)),
                ('redelivery_quantity', models.IntegerField(default=0)),
                ('overdelivery_quantity', models.IntegerField(default=0)),
                ('return_quantity', models.IntegerField(default=0)),
                ('after_sales_delivery_date', models.DateField(blank=True, null=True)),
                ('after_sales_delivery_fee', models.FloatField(default=0)),
                ('after_sales_warehouse_comment', models.CharField(blank=True, max_length=255, null=True)),
                ('deliver_order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.deliverorderitems')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
