# Generated by Django 3.2.16 on 2024-09-20 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0095_auto_20240920_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverorder',
            name='self_id',
            field=models.ForeignKey(blank=True, help_text='Add deliver id when after sales is created for this deliver id.', null=True, on_delete=django.db.models.deletion.CASCADE, to='home.deliverorder'),
        ),
        migrations.AddField(
            model_name='deliverorderitems',
            name='failed_delivery_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deliverorderitems',
            name='overdelivery_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deliverorderitems',
            name='redelivery_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deliverorderitems',
            name='return_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='amount_trigger',
            field=models.CharField(choices=[('Less than', 'Less than'), ('More than', 'More than'), ('Equals to', 'Equals to'), ('More than and equals to', 'More than and equals to'), (None, '-------'), ('Less than and equals to', 'Less than and equals to')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='quantity_trigger',
            field=models.CharField(choices=[('Less than', 'Less than'), ('More than', 'More than'), ('Equals to', 'Equals to'), ('More than and equals to', 'More than and equals to'), (None, '-------'), ('Less than and equals to', 'Less than and equals to')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('Partially Delivered', 'Partially Delivered'), ('Pending', 'Pending'), ('Delivered', 'Delivered')], default='Pending', max_length=128),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='type',
            field=models.CharField(choices=[('Purchase', 'Purchase'), ('Quotation', 'Quotation')], max_length=128),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='prefix',
            field=models.CharField(choices=[('+20', '+20 (Egypt)'), ('+81', '+81 (Japan)'), ('+91', '+91 (India)'), ('+49', '+49 (Germany)'), ('+7', '+7 (Russia)'), ('+971', '+971 (UAE)'), ('+86', '+86 (China)'), ('+33', '+33 (France)'), ('+1', '+1 (US)'), ('+44', '+44 (UK)'), ('+39', '+39 (Italy)'), ('+64', '+64 (New Zealand)'), ('+52', '+52 (Mexico)'), ('+1', '+1 (Canada)'), ('+61', '+61 (Australia)'), ('+34', '+34 (Spain)'), ('+82', '+82 (South Korea)'), ('+966', '+966 (Saudi Arabia)'), ('+65', '+65 (Singapore)'), ('+55', '+55 (Brazil)')], max_length=250),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='discount_type',
            field=models.CharField(choices=[(None, '-------'), ('Fixed Amount', 'Fixed Amount'), ('Rate(%)', 'Rate(%)')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='status',
            field=models.CharField(choices=[('Paused', 'Paused'), ('Valid', 'Valid'), ('Ready to start', 'Ready to start'), ('Cancelled', 'Cancelled'), ('Ended', 'Ended')], max_length=128),
        ),
        migrations.DeleteModel(
            name='AfterSalesOrderitems',
        ),
    ]
