# Generated by Django 3.2.16 on 2024-09-23 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0096_auto_20240920_1649'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliverorder',
            old_name='self_id',
            new_name='self_deliver_order',
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='amount_trigger',
            field=models.CharField(choices=[('Equals to', 'Equals to'), ('More than and equals to', 'More than and equals to'), (None, '-------'), ('More than', 'More than'), ('Less than', 'Less than'), ('Less than and equals to', 'Less than and equals to')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='quantity_trigger',
            field=models.CharField(choices=[('Equals to', 'Equals to'), ('More than and equals to', 'More than and equals to'), (None, '-------'), ('More than', 'More than'), ('Less than', 'Less than'), ('Less than and equals to', 'Less than and equals to')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='payment_method',
            field=models.CharField(choices=[('Bank Transfer/Cheque', 'Bank Transfer/Cheque'), ('COD', 'COD')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Partially Delivered', 'Partially Delivered'), ('Pending', 'Pending')], default='Pending', max_length=128),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='prefix',
            field=models.CharField(choices=[('+1', '+1 (US)'), ('+7', '+7 (Russia)'), ('+971', '+971 (UAE)'), ('+65', '+65 (Singapore)'), ('+91', '+91 (India)'), ('+81', '+81 (Japan)'), ('+1', '+1 (Canada)'), ('+33', '+33 (France)'), ('+86', '+86 (China)'), ('+20', '+20 (Egypt)'), ('+39', '+39 (Italy)'), ('+82', '+82 (South Korea)'), ('+34', '+34 (Spain)'), ('+966', '+966 (Saudi Arabia)'), ('+49', '+49 (Germany)'), ('+55', '+55 (Brazil)'), ('+61', '+61 (Australia)'), ('+52', '+52 (Mexico)'), ('+44', '+44 (UK)'), ('+64', '+64 (New Zealand)')], max_length=250),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='discount_type',
            field=models.CharField(choices=[('Rate(%)', 'Rate(%)'), ('Fixed Amount', 'Fixed Amount'), (None, '-------')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='status',
            field=models.CharField(choices=[('Ready to start', 'Ready to start'), ('Cancelled', 'Cancelled'), ('Valid', 'Valid'), ('Paused', 'Paused'), ('Ended', 'Ended')], max_length=128),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='voucher_type',
            field=models.CharField(choices=[('Manual Discount', 'Manual Discount'), ('Discount Voucher', 'Discount Voucher'), ('Free Gift', 'Free Gift'), ('Product Combo', 'Product Combo')], max_length=128),
        ),
    ]
