# Generated by Django 3.2.16 on 2024-10-10 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0097_auto_20240923_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverorderitems',
            name='self_deliver_order_item',
            field=models.ForeignKey(blank=True, help_text='Add deliver order item id when after sales is created for this deliver order item.', null=True, on_delete=django.db.models.deletion.CASCADE, to='home.deliverorderitems'),
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='amount_trigger',
            field=models.CharField(choices=[('More than', 'More than'), ('Less than', 'Less than'), ('Equals to', 'Equals to'), ('Less than and equals to', 'Less than and equals to'), ('More than and equals to', 'More than and equals to'), (None, '-------')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='quantity_trigger',
            field=models.CharField(choices=[('More than', 'More than'), ('Less than', 'Less than'), ('Equals to', 'Equals to'), ('Less than and equals to', 'Less than and equals to'), ('More than and equals to', 'More than and equals to'), (None, '-------')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'COD'), ('Bank Transfer/Cheque', 'Bank Transfer/Cheque')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Delivered', 'Delivered'), ('Partially Delivered', 'Partially Delivered')], default='Pending', max_length=128),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='prefix',
            field=models.CharField(choices=[('+49', '+49 (Germany)'), ('+82', '+82 (South Korea)'), ('+7', '+7 (Russia)'), ('+86', '+86 (China)'), ('+39', '+39 (Italy)'), ('+44', '+44 (UK)'), ('+65', '+65 (Singapore)'), ('+1', '+1 (US)'), ('+1', '+1 (Canada)'), ('+971', '+971 (UAE)'), ('+61', '+61 (Australia)'), ('+91', '+91 (India)'), ('+55', '+55 (Brazil)'), ('+34', '+34 (Spain)'), ('+81', '+81 (Japan)'), ('+20', '+20 (Egypt)'), ('+64', '+64 (New Zealand)'), ('+966', '+966 (Saudi Arabia)'), ('+52', '+52 (Mexico)'), ('+33', '+33 (France)')], max_length=250),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='status',
            field=models.CharField(choices=[('Valid', 'Valid'), ('Ready to start', 'Ready to start'), ('Paused', 'Paused'), ('Cancelled', 'Cancelled'), ('Ended', 'Ended')], max_length=128),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='voucher_type',
            field=models.CharField(choices=[('Product Combo', 'Product Combo'), ('Discount Voucher', 'Discount Voucher'), ('Manual Discount', 'Manual Discount'), ('Free Gift', 'Free Gift')], max_length=128),
        ),
    ]
