# Generated by Django 3.2.16 on 2025-04-15 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0098_auto_20241010_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountvoucher',
            name='amount_trigger',
            field=models.CharField(choices=[('More than and equals to', 'More than and equals to'), ('Equals to', 'Equals to'), ('Less than', 'Less than'), (None, '-------'), ('More than', 'More than'), ('Less than and equals to', 'Less than and equals to')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='quantity_trigger',
            field=models.CharField(choices=[('More than and equals to', 'More than and equals to'), ('Equals to', 'Equals to'), ('Less than', 'Less than'), (None, '-------'), ('More than', 'More than'), ('Less than and equals to', 'Less than and equals to')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='payment_method',
            field=models.CharField(choices=[('Bank Transfer/Cheque', 'Bank Transfer/Cheque'), ('COD', 'COD')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('Partially Delivered', 'Partially Delivered'), ('Delivered', 'Delivered'), ('Pending', 'Pending')], default='Pending', max_length=128),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='prefix',
            field=models.CharField(choices=[('+39', '+39 (Italy)'), ('+1', '+1 (Canada)'), ('+61', '+61 (Australia)'), ('+33', '+33 (France)'), ('+34', '+34 (Spain)'), ('+49', '+49 (Germany)'), ('+64', '+64 (New Zealand)'), ('+966', '+966 (Saudi Arabia)'), ('+91', '+91 (India)'), ('+82', '+82 (South Korea)'), ('+44', '+44 (UK)'), ('+7', '+7 (Russia)'), ('+971', '+971 (UAE)'), ('+86', '+86 (China)'), ('+65', '+65 (Singapore)'), ('+20', '+20 (Egypt)'), ('+81', '+81 (Japan)'), ('+1', '+1 (US)'), ('+55', '+55 (Brazil)'), ('+52', '+52 (Mexico)')], max_length=250),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='discount_type',
            field=models.CharField(choices=[('Fixed Amount', 'Fixed Amount'), (None, '-------'), ('Rate(%)', 'Rate(%)')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='status',
            field=models.CharField(choices=[('Valid', 'Valid'), ('Ended', 'Ended'), ('Ready to start', 'Ready to start'), ('Cancelled', 'Cancelled'), ('Paused', 'Paused')], max_length=128),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='voucher_type',
            field=models.CharField(choices=[('Manual Discount', 'Manual Discount'), ('Product Combo', 'Product Combo'), ('Free Gift', 'Free Gift'), ('Discount Voucher', 'Discount Voucher')], max_length=128),
        ),
    ]
