# Generated by Django 3.2.16 on 2025-04-21 07:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0099_auto_20250415_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountvoucher',
            name='amount_trigger',
            field=models.CharField(choices=[('More than and equals to', 'More than and equals to'), ('Less than', 'Less than'), ('Less than and equals to', 'Less than and equals to'), (None, '-------'), ('More than', 'More than'), ('Equals to', 'Equals to')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='quantity_trigger',
            field=models.CharField(choices=[('More than and equals to', 'More than and equals to'), ('Less than', 'Less than'), ('Less than and equals to', 'Less than and equals to'), (None, '-------'), ('More than', 'More than'), ('Equals to', 'Equals to')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'COD'), ('Bank Transfer/Cheque', 'Bank Transfer/Cheque')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Delivered', 'Delivered'), ('Partially Delivered', 'Partially Delivered')], default='Pending', max_length=128),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='type',
            field=models.CharField(choices=[('Quotation', 'Quotation'), ('Purchase', 'Purchase')], max_length=128),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='prefix',
            field=models.CharField(choices=[('+1', '+1 (Canada)'), ('+64', '+64 (New Zealand)'), ('+49', '+49 (Germany)'), ('+33', '+33 (France)'), ('+20', '+20 (Egypt)'), ('+44', '+44 (UK)'), ('+52', '+52 (Mexico)'), ('+81', '+81 (Japan)'), ('+1', '+1 (US)'), ('+34', '+34 (Spain)'), ('+61', '+61 (Australia)'), ('+82', '+82 (South Korea)'), ('+7', '+7 (Russia)'), ('+971', '+971 (UAE)'), ('+39', '+39 (Italy)'), ('+91', '+91 (India)'), ('+65', '+65 (Singapore)'), ('+966', '+966 (Saudi Arabia)'), ('+55', '+55 (Brazil)'), ('+86', '+86 (China)')], max_length=250),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='discount_type',
            field=models.CharField(choices=[('Fixed Amount', 'Fixed Amount'), ('Rate(%)', 'Rate(%)'), (None, '-------')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='status',
            field=models.CharField(choices=[('Ready to start', 'Ready to start'), ('Valid', 'Valid'), ('Paused', 'Paused'), ('Ended', 'Ended'), ('Cancelled', 'Cancelled')], max_length=128),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='voucher_type',
            field=models.CharField(choices=[('Product Combo', 'Product Combo'), ('Free Gift', 'Free Gift'), ('Discount Voucher', 'Discount Voucher'), ('Manual Discount', 'Manual Discount')], max_length=128),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=50, unique=True, verbose_name='Transaction ID')),
                ('transaction_type', models.CharField(choices=[('Payment', 'Payment'), ('Refund', 'Refund'), ('Adjustment', 'Adjustment'), ('Discount', 'Discount')], max_length=50, verbose_name='Transaction Type')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('currency', models.CharField(default='HKD', max_length=10, verbose_name='Currency')),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True, verbose_name='Payment Method')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Awaiting Approval', 'Awaiting Approval'), ('Approved', 'Approved'), ('Completed', 'Completed'), ('Failed', 'Failed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=50, verbose_name='Status')),
                ('payment_status', models.CharField(choices=[('Unpaid', 'Unpaid'), ('Partial', 'Partial'), ('Paid', 'Paid')], default='Unpaid', max_length=50, verbose_name='Payment Status')),
                ('customer_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Customer ID')),
                ('customer_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Customer Name')),
                ('sales_person', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sales Person')),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Upload Date')),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Refund Amount')),
                ('refund_date', models.DateTimeField(blank=True, null=True, verbose_name='Refund Date')),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Net Amount')),
                ('delivery_date', models.DateTimeField(blank=True, null=True, verbose_name='Delivery Date')),
                ('transaction_date', models.DateTimeField(auto_now_add=True, verbose_name='Transaction Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='transaction_attachments/', verbose_name='Attachment')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='home.order', verbose_name='Order')),
                ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='home.orderitems', verbose_name='Order Item')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
            },
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_date'], name='home_transa_transac_4abcd0_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['order_id'], name='home_transa_order_i_e488ce_idx'),
        ),
    ]
