# Generated by Django 3.2.16 on 2025-04-24 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0100_auto_20250421_0703'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='優惠券代碼')),
                ('type', models.CharField(choices=[('滿減券', '滿減券'), ('折扣券', '折扣券'), ('兌換券', '兌換券')], max_length=50, verbose_name='類型')),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='折扣值')),
                ('min_spend', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='最低消費額')),
                ('start_date', models.DateField(verbose_name='開始日期')),
                ('end_date', models.DateField(verbose_name='結束日期')),
                ('usage_limit', models.PositiveIntegerField(verbose_name='使用次數限制')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='已使用次數')),
            ],
            options={
                'verbose_name': '優惠券',
                'verbose_name_plural': '優惠券',
                'db_table': 'coupon',
            },
        ),
        migrations.CreateModel(
            name='DiscountScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128, verbose_name='方案名稱')),
                ('type', models.CharField(choices=[('滿減', '滿減'), ('折扣', '折扣'), ('贈品', '贈品')], max_length=50, verbose_name='類型')),
                ('condition_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='條件金額')),
                ('start_date', models.DateField(verbose_name='開始日期')),
                ('end_date', models.DateField(verbose_name='結束日期')),
                ('usage_limit', models.PositiveIntegerField(blank=True, null=True, verbose_name='使用次數限制')),
                ('status', models.CharField(choices=[('啟用', '啟用'), ('停用', '停用')], default='啟用', max_length=20, verbose_name='狀態')),
            ],
            options={
                'verbose_name': '優惠方案',
                'verbose_name_plural': '優惠方案',
                'db_table': 'discount_scheme',
            },
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='促銷碼')),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='折扣值')),
                ('start_date', models.DateField(verbose_name='開始日期')),
                ('end_date', models.DateField(verbose_name='結束日期')),
                ('usage_limit', models.PositiveIntegerField(verbose_name='使用次數限制')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='已使用次數')),
            ],
            options={
                'verbose_name': '促銷碼',
                'verbose_name_plural': '促銷碼',
                'db_table': 'promo_code',
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128, verbose_name='活動名稱')),
                ('type', models.CharField(choices=[('限時折扣', '限時折扣'), ('買一送一', '買一送一'), ('組合套餐', '組合套餐')], max_length=50, verbose_name='類型')),
                ('start_date', models.DateTimeField(verbose_name='開始時間')),
                ('end_date', models.DateTimeField(verbose_name='結束時間')),
                ('description', models.TextField(verbose_name='活動描述')),
            ],
            options={
                'verbose_name': '促銷活動',
                'verbose_name_plural': '促銷活動',
                'db_table': 'promotion',
            },
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='amount_trigger',
            field=models.CharField(choices=[('Less than', 'Less than'), (None, '-------'), ('Less than and equals to', 'Less than and equals to'), ('Equals to', 'Equals to'), ('More than and equals to', 'More than and equals to'), ('More than', 'More than')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='quantity_trigger',
            field=models.CharField(choices=[('Less than', 'Less than'), (None, '-------'), ('Less than and equals to', 'Less than and equals to'), ('Equals to', 'Equals to'), ('More than and equals to', 'More than and equals to'), ('More than', 'More than')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='payment_method',
            field=models.CharField(choices=[('Bank Transfer/Cheque', 'Bank Transfer/Cheque'), ('COD', 'COD')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('Partially Delivered', 'Partially Delivered'), ('Pending', 'Pending'), ('Delivered', 'Delivered')], default='Pending', max_length=128),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='prefix',
            field=models.CharField(choices=[('+82', '+82 (South Korea)'), ('+65', '+65 (Singapore)'), ('+971', '+971 (UAE)'), ('+7', '+7 (Russia)'), ('+55', '+55 (Brazil)'), ('+64', '+64 (New Zealand)'), ('+20', '+20 (Egypt)'), ('+86', '+86 (China)'), ('+1', '+1 (Canada)'), ('+61', '+61 (Australia)'), ('+44', '+44 (UK)'), ('+1', '+1 (US)'), ('+52', '+52 (Mexico)'), ('+39', '+39 (Italy)'), ('+33', '+33 (France)'), ('+966', '+966 (Saudi Arabia)'), ('+91', '+91 (India)'), ('+49', '+49 (Germany)'), ('+34', '+34 (Spain)'), ('+81', '+81 (Japan)')], max_length=250),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='discount_type',
            field=models.CharField(choices=[(None, '-------'), ('Rate(%)', 'Rate(%)'), ('Fixed Amount', 'Fixed Amount')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='status',
            field=models.CharField(choices=[('Ended', 'Ended'), ('Ready to start', 'Ready to start'), ('Cancelled', 'Cancelled'), ('Paused', 'Paused'), ('Valid', 'Valid')], max_length=128),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='voucher_type',
            field=models.CharField(choices=[('Discount Voucher', 'Discount Voucher'), ('Free Gift', 'Free Gift'), ('Product Combo', 'Product Combo'), ('Manual Discount', 'Manual Discount')], max_length=128),
        ),
    ]
