# Generated by Django 3.2.16 on 2025-05-08 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0101_auto_20250424_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountvoucher',
            name='amount_trigger',
            field=models.CharField(choices=[('Equals to', 'Equals to'), ('Less than and equals to', 'Less than and equals to'), ('More than', 'More than'), ('Less than', 'Less than'), (None, '-------'), ('More than and equals to', 'More than and equals to')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='quantity_trigger',
            field=models.CharField(choices=[('Equals to', 'Equals to'), ('Less than and equals to', 'Less than and equals to'), ('More than', 'More than'), ('Less than', 'Less than'), (None, '-------'), ('More than and equals to', 'More than and equals to')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='type',
            field=models.CharField(choices=[('Purchase', 'Purchase'), ('Quotation', 'Quotation')], max_length=128),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='prefix',
            field=models.CharField(choices=[('+82', '+82 (South Korea)'), ('+65', '+65 (Singapore)'), ('+1', '+1 (US)'), ('+1', '+1 (Canada)'), ('+966', '+966 (Saudi Arabia)'), ('+61', '+61 (Australia)'), ('+49', '+49 (Germany)'), ('+86', '+86 (China)'), ('+55', '+55 (Brazil)'), ('+52', '+52 (Mexico)'), ('+33', '+33 (France)'), ('+34', '+34 (Spain)'), ('+20', '+20 (Egypt)'), ('+44', '+44 (UK)'), ('+39', '+39 (Italy)'), ('+91', '+91 (India)'), ('+971', '+971 (UAE)'), ('+81', '+81 (Japan)'), ('+7', '+7 (Russia)'), ('+64', '+64 (New Zealand)')], max_length=250),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='discount_type',
            field=models.CharField(choices=[('Rate(%)', 'Rate(%)'), (None, '-------'), ('Fixed Amount', 'Fixed Amount')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='status',
            field=models.CharField(choices=[('Ended', 'Ended'), ('Valid', 'Valid'), ('Cancelled', 'Cancelled'), ('Paused', 'Paused'), ('Ready to start', 'Ready to start')], max_length=128),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='voucher_type',
            field=models.CharField(choices=[('Discount Voucher', 'Discount Voucher'), ('Product Combo', 'Product Combo'), ('Free Gift', 'Free Gift'), ('Manual Discount', 'Manual Discount')], max_length=128),
        ),
    ]
