# Generated by Django 3.2.16 on 2025-07-06 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0102_auto_20250508_0659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountvoucher',
            name='amount_trigger',
            field=models.CharField(choices=[('More than', 'More than'), ('Less than and equals to', 'Less than and equals to'), ('Less than', 'Less than'), ('More than and equals to', 'More than and equals to'), ('Equals to', 'Equals to'), (None, '-------')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='discountvoucher',
            name='quantity_trigger',
            field=models.CharField(choices=[('More than', 'More than'), ('Less than and equals to', 'Less than and equals to'), ('Less than', 'Less than'), ('More than and equals to', 'More than and equals to'), ('Equals to', 'Equals to'), (None, '-------')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Partially Delivered', 'Partially Delivered'), ('Delivered', 'Delivered')], default='Pending', max_length=128),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='prefix',
            field=models.CharField(choices=[('+966', '+966 (Saudi Arabia)'), ('+971', '+971 (UAE)'), ('+82', '+82 (South Korea)'), ('+52', '+52 (Mexico)'), ('+44', '+44 (UK)'), ('+61', '+61 (Australia)'), ('+86', '+86 (China)'), ('+64', '+64 (New Zealand)'), ('+7', '+7 (Russia)'), ('+1', '+1 (US)'), ('+33', '+33 (France)'), ('+55', '+55 (Brazil)'), ('+20', '+20 (Egypt)'), ('+1', '+1 (Canada)'), ('+34', '+34 (Spain)'), ('+91', '+91 (India)'), ('+81', '+81 (Japan)'), ('+39', '+39 (Italy)'), ('+49', '+49 (Germany)'), ('+65', '+65 (Singapore)')], max_length=250),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='discount_type',
            field=models.CharField(choices=[('Fixed Amount', 'Fixed Amount'), (None, '-------'), ('Rate(%)', 'Rate(%)')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='status',
            field=models.CharField(choices=[('Ready to start', 'Ready to start'), ('Ended', 'Ended'), ('Paused', 'Paused'), ('Cancelled', 'Cancelled'), ('Valid', 'Valid')], max_length=128),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='voucher_type',
            field=models.CharField(choices=[('Manual Discount', 'Manual Discount'), ('Free Gift', 'Free Gift'), ('Discount Voucher', 'Discount Voucher'), ('Product Combo', 'Product Combo')], max_length=128),
        ),
    ]
