# Generated by Django 3.2.16 on 2024-03-06 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('staff', 'staff'), ('admin', 'admin'), ('seller', 'seller')], default='seller', max_length=128),
        ),
    ]
