# Generated by Django 3.2.16 on 2024-03-07 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('staff', 'staff'), ('seller', 'seller'), ('admin', 'admin')], default='seller', max_length=128),
        ),
    ]
