# Generated by Django 3.2.16 on 2024-03-15 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('seller', 'seller'), ('staff', 'staff')], default='seller', max_length=128),
        ),
    ]
