# Generated by Django 3.2.16 on 2024-03-15 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('seller', 'seller'), ('staff', 'staff'), ('admin', 'admin')], default='seller', max_length=128),
        ),
    ]
