# Generated by Django 3.2.16 on 2024-04-03 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_auto_20240403_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissions',
            name='is_permission',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='permissions',
            name='role',
            field=models.CharField(choices=[('seller', 'seller'), ('staff', 'staff'), ('admin', 'admin')], default='seller', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('seller', 'seller'), ('staff', 'staff'), ('admin', 'admin')], default='seller', max_length=128),
        ),
    ]
