# Generated by Django 3.2.16 on 2024-07-26 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_auto_20240403_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissions',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='permissions',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('seller', 'seller'), ('staff', 'staff')], default='seller', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('seller', 'seller'), ('staff', 'staff')], default='seller', max_length=128),
        ),
    ]
