# Generated by Django 3.2.16 on 2025-04-21 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_auto_20250415_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissions',
            name='role',
            field=models.CharField(choices=[('seller', 'seller'), ('admin', 'admin'), ('staff', 'staff')], default='seller', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('seller', 'seller'), ('admin', 'admin'), ('staff', 'staff')], default='seller', max_length=128),
        ),
    ]
