# Generated by Django 3.2.16 on 2025-04-24 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_auto_20250421_0703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissions',
            name='role',
            field=models.CharField(choices=[('staff', 'staff'), ('seller', 'seller'), ('admin', 'admin')], default='seller', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('staff', 'staff'), ('seller', 'seller'), ('admin', 'admin')], default='seller', max_length=128),
        ),
    ]
