# Generated by Django 3.2.16 on 2025-05-08 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_auto_20250424_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissions',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('seller', 'seller'), ('staff', 'staff')], default='seller', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('seller', 'seller'), ('staff', 'staff')], default='seller', max_length=128),
        ),
    ]
