# Generated by Django 3.2.16 on 2025-07-06 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_auto_20250508_0659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissions',
            name='role',
            field=models.CharField(choices=[('seller', 'seller'), ('staff', 'staff'), ('admin', 'admin')], default='seller', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('seller', 'seller'), ('staff', 'staff'), ('admin', 'admin')], default='seller', max_length=128),
        ),
    ]
